//Copyright 2025 Chikirev Sirguy, Unirail Group. All rights reserved.
//
//This file is part of the AdHoc protocol runtime library.
//
//Licensed under the PolyForm Shield License 1.0.0. The full text is distributed with this
//file as LICENSE.md and is published at https://polyformproject.org/licenses/shield/1.0.0
//
//In short: you may use, modify and distribute this software for any purpose, except to
//provide a product that competes with the software, or with any product the licensor
//provides using the software. Competition is judged by function, not by form.
//
//The plain-text notice lines the license requires you to pass on - the Required Notice and
//the Licensor Line of Business - are in the NOTICE file distributed with this library.
//Keep LICENSE.md and NOTICE with any copy of this software that you distribute.
//
//Code generated by the AdHoc generator is NOT part of the Licensed Work and carries no
//restrictions whatsoever - see the header of any generated file.
//
//Provided as is, without any warranty or condition.
//
//Commercial licenses that remove the noncompete restriction are available.
//For licensing and inquiries: al8v5C6HU4UtqE9@gmail.com

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;

namespace org.unirail.collections;

///<summary>
///A specialized dictionary that maps keys of type K (restricted to one byte type) to values of type V.
///Allows associating null values with any key.
///<para>
///The map employs two internal strategies for storing values to optimize for both space and performance:
///<list type="number">
///<item>
///  <b>Compressed (Rank-Based) Strategy:</b> used when fewer than 128 keys have non-null values.
///  Stores only non-null values in a compact array, using a bitset to track keys with non-null values.
///</item>
///<item>
///  <b>Flat (One-to-One) Strategy:</b> Activated when 128 or more keys have non-null values.
///  Uses a fixed-size array of 256 elements for direct O(1) access, with each index corresponding to a byte key.
///</item>
///</list>
///The transition between strategies occurs automatically when the 128th non-null value is added.
///</para>
///
///<para><b>Benchmark vs <c>Dictionary&lt;byte,int&gt;</c></b> (full byte domain 0..255 → flat strategy,
///1M random Contains/Get probes, .NET 9, Release; median of 5 runs):</para>
///<code>
///Insert         Search             Get        Indexer       Iterate         Delete         Churn
///ByteMap&lt;byte,int&gt;  27 526 882  1 749 038 029   1 101 477 553  1 096 663 011    59 733 333     18 436 214    28 535 032   ops/sec
///Dictionary                 0.87           0.05            0.36           0.34          0.93           0.83          0.73   x
///</code>
///<para><b>Memory profile (Insert, 256 keys, full byte domain (flat strategy)):</b>
///<list type="bullet">
///<item><c>ByteMap</c> allocates <b>8.91 B/op</b> (Insert, 256 keys, full byte domain (flat strategy) of 256 records)</item>
///<item><c>Dictionary</c> allocates <b>23.41 B/op</b></item>
///<item><c>ByteMap</c> saves <b>~14 500 B per 1 000 records</b> vs Dictionary</item>
///</list>
///</para>
///<para>
///Ratio &gt; 1 ⇒ <c>Dictionary</c> faster, &lt; 1 ⇒ <c>ByteMap</c> faster. ByteMap now wins <b>every</b> scenario:
///~20× faster on Search (bitset Get vs hash-and-chain walk), ~3× faster on TryGetValue and indexer get,
///~1.4× faster on Churn, ~1.2× faster on Delete, and edges Dictionary by ~15% on Insert and ~8% on Iterate.
///The Insert win comes from inlining the compressed-mode array shift (skipping the BitList.Resize call's
///parameter-validation overhead) and a lockstep keys+nullsVal walk during the compressed→flat transition.
///The Iterate win comes from segment-cached enumeration (TZCNT + bit-clear per element, value resolution
///via a single shift+AND against the cached <c>nullsVal</c> segment).
///</para>
///<para>See <c>Tests/Benchmarks/ByteMapBenchmark.cs</c> for the full scenarios and an HTML report.</para>
///</summary>
///<typeparam name="K">The key type, must be a struct (one byte type).</typeparam>
///<typeparam name="V">The value type, can be any type.</typeparam>
public class ByteMap<K, V> : IDictionary<K, V>, IReadOnlyDictionary<K, V>, IEquatable<ByteMap<K, V>>
    where K : unmanaged
{
    protected ByteSet<K> keys;     //Bit array tracking all present keys (0-255 range)
    protected ByteSet<K> nullsVal; //Bit array tracking keys with non-null values
    protected V[] values;          //Array storing non-null values
    protected static EqualityComparer<V> equal_hash_V = EqualityComparer<V>.Default;

    //Lazily-initialized wrapper collections, cached so repeated `Keys` / `Values` calls
    //don't allocate a fresh wrapper each time (matches Dictionary<TKey,TValue>'s behavior).
    private KeyCollection? _keysCollection;
    private ValueCollection? _valuesCollection;

    ///<summary>
    ///Initializes a new instance of ByteMap with default capacity, validating that K is either one byte type.
    ///Starts with the Compressed (Rank-Based) Strategy.
    ///</summary>
    ///<exception cref="ArgumentException">Thrown if K is not one byte type.</exception>
    public ByteMap()
    {
        if (Unsafe.SizeOf<K>() != 1)
            throw new ArgumentException("ByteSet only supports one byte type as key types.");

        nullsVal = [];
        keys = [];
        values = new V[16];
    }

    public ByteMap(int capacity)
    {
        ArgumentOutOfRangeException.ThrowIfGreaterThan(capacity, 256);
        ArgumentOutOfRangeException.ThrowIfNegative(value: capacity);
        if (Unsafe.SizeOf<K>() != 1)
            throw new ArgumentException("ByteSet only supports one byte type as key types.");

        nullsVal = [];
        keys = [];
        values = new V[capacity <= 0 ? 16 : (int)BitOperations.RoundUpToPowerOf2((uint)capacity)];
    }

    ///<summary>
    ///Indicates whether the map is using the Flat (One-to-One) Strategy.
    ///</summary>
    public bool IsFlat
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => values.Length == 256;
    }

    ///<summary>
    ///Determines whether the specified ByteMap is equal to the current instance.
    ///</summary>
    ///<param name="other">The ByteMap to compare with the current instance.</param>
    ///<returns>True if the maps are equal, false otherwise.</returns>
    public bool Equals(ByteMap<K, V>? other)
    {
        if (other == this)
            return true;
        if (other == null ||
            !keys.Equals(other.keys) ||
            Count != other.Count ||
            !nullsVal.Equals(other.nullsVal))
            return false;

        //Iterate the nullsVal subset directly via the segment-cached enumerator
        //instead of chaining Next1 — same order, fewer cycles per element.
        bool thisFlat = IsFlat, otherFlat = other.IsFlat;
        int i = 0;
        foreach (var k in nullsVal)
        {
            var key = k;
            var bKey = Unsafe.As<K, byte>(ref key);
            var lhs = thisFlat ? values[bKey] : values[i];
            var rhs = otherFlat ? other.values[bKey] : other.values[i];
            if (!equal_hash_V.Equals(lhs, rhs))
                return false;
            i++;
        }
        return true;
    }

    ///<summary>
    ///Gets or sets the value associated with the specified key.
    ///Returns default(V) if the key is not found.
    ///When setting, a null value marks the key as present with a null value.
    ///</summary>
    public V this[K key]
    {
        //nullsVal[k] == 1 ⇒ keys[k] == 1 by invariant (Add_ always sets keys when setting nullsVal,
        //Remove always clears both), so the redundant keys.Get check is dropped.
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            var _key = Unsafe.As<K, byte>(ref key);
            if (!nullsVal.Get(_key))
                return default!;
            return values[IsFlat ? _key : nullsVal.Rank(_key) - 1];
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => Add_(key, value);
    }

    ///<summary>
    ///Adds or updates a key-value pair in the map.
    ///Handles the transition to the Flat strategy when the 128th non-null value is added.
    ///</summary>
    ///<param name="key">The key to add or update.</param>
    ///<param name="value">The value to associate with the key (can be null).</param>
    ///<returns>True if the key was added, false if it was updated.</returns>
    public bool Add_(K key, V value)
    {
        var _key = Unsafe.As<K, byte>(ref key);

        if (equal_hash_V.Equals(value, default))
        {
            if (nullsVal.Set0(_key) && !IsFlat)
                BitList.Resize(values, values, nullsVal.Rank(_key), nullsVal.Count + 1, -1);
            return keys.Set1(_key);
        }

        if (nullsVal.Get(_key))
        {
            values[IsFlat ? _key : nullsVal.Rank(_key) - 1] = value;
            return false;
        }

        //We've already established nullsVal does NOT contain _key, so the
        //original `&& !nullsVal[_key]` guard on the transition branch was redundant.
        if (IsFlat)
            values[_key] = value;
        else if (nullsVal.Count == 128)
        {
            //Transition Compressed → Flat: walk the 128 nullsVal entries directly
            //(no need to scan all `keys` and re-test nullsVal for each).
            var values_ = new V[256];
            int ii = 0;
            foreach (var k in nullsVal)
            {
                var kk = k;
                values_[Unsafe.As<K, byte>(ref kk)] = values[ii++];
            }
            (values = values_)[_key] = value;
        }
        else
        {
            //Compressed insert: inline the array-resize+shift logic instead of going
            //through BitList.Resize (4 validation branches + a switch on resize sign,
            //most of which are dead for this call shape). The common sequential-append
            //case (r == oldCount, capacity available) collapses to a single array store.
            var oldCount = nullsVal.Count;
            var r = nullsVal.Rank(_key);
            var capacity = values.Length;

            if (oldCount >= capacity)
            {
                //Grow: allocate doubled array, copy prefix [0,r) and shift suffix [r,oldCount).
                var newValues = new V[capacity << 1];
                if (r > 0)
                    Array.Copy(values, 0, newValues, 0, r);
                if (r < oldCount)
                    Array.Copy(values, r, newValues, r + 1, oldCount - r);
                values = newValues;
            }
            else if (r < oldCount)
            {
                //No grow but mid-insert: in-place right shift to open slot at r.
                Array.Copy(values, r, values, r + 1, oldCount - r);
            }
            //r == oldCount && oldCount < capacity: pure append, no copy or alloc needed.
            values[r] = value;
        }

        nullsVal.Set1(_key);
        return keys.Set1(_key);
    }

    ///<summary>Gets the collection of keys in the map.</summary>
    public ICollection<K> Keys => _keysCollection ??= new KeyCollection(this);

    IEnumerable<K> IReadOnlyDictionary<K, V>.Keys => Keys;

    ///<summary>Gets the collection of values in the map.</summary>
    public ICollection<V> Values => _valuesCollection ??= new ValueCollection(this);

    IEnumerable<V> IReadOnlyDictionary<K, V>.Values => Values;

    ///<summary>Gets the number of key-value pairs in the map.</summary>
    public int Count
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => keys.Count;
    }

    ///<summary>Gets the current capacity of the values array.</summary>
    public int Capacity
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => values.Length;
    }

    ///<summary>Gets a value indicating whether the map is read-only (always false).</summary>
    public bool IsReadOnly
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => false;
    }

    ///<summary>Adds a key-value pair to the map.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Add(K key, V value) => this[key] = value;

    ///<summary>Adds a key-value pair from a KeyValuePair structure.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Add(KeyValuePair<K, V> item) => this[item.Key] = item.Value;

    ///<summary>Checks if the specified key exists in the map.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool ContainsKey(K key)
    {
        var _key = Unsafe.As<K, byte>(ref key);
        return keys.Get(_key);
    }

    ///<summary>Removes the specified key and its associated value from the map.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool Remove(K key)
    {
        var _key = Unsafe.As<K, byte>(ref key);
        if (!keys.Set0(_key))
            return false;

        if (nullsVal.Set0(_key) && !IsFlat)
            BitList.Resize(values, values, nullsVal.Rank(_key), nullsVal.Count + 1, -1);
        return true;
    }

    ///<summary>Removes a specific key-value pair if it exists.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool Remove(KeyValuePair<K, V> item)
    {
        if (!TryGetValue(item.Key, out var current) || !equal_hash_V.Equals(current, item.Value))
            return false;
        return Remove(item.Key);
    }

    ///<summary>Tries to get the value associated with the specified key.</summary>
    ///<remarks>
    ///Reordered hot path: <c>nullsVal ⊆ keys</c> by invariant, so a hit on <c>nullsVal</c> proves
    ///the key is present without consulting <c>keys</c>. The most common case (key with non-null
    ///value) thus costs a single bitset lookup. The slow paths still distinguish "present with
    ///default value" from "absent".
    ///</remarks>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool TryGetValue(K key, out V value)
    {
        var _key = Unsafe.As<K, byte>(ref key);
        if (nullsVal.Get(_key))
        {
            value = values[IsFlat ? _key : nullsVal.Rank(_key) - 1];
            return true;
        }
        if (keys.Get(_key))
        {
            value = default!;
            return true;
        }
        value = default!;
        return false;
    }

    ///<summary>
    ///Gets a reference to the value associated with the specified key, adding a provided default value if the key does not exist.
    ///</summary>
    ///<param name="key">The key to search for.</param>
    ///<param name="defaultValue">The value to add if the key does not exist.</param>
    ///<param name="exists">When this method returns, contains <c>true</c> if the key already existed; otherwise, <c>false</c>.</param>
    ///<returns>A reference to the value associated with the specified key.</returns>
    ///<remarks>
    ///Note: Do not add or remove items from the map while holding this reference, as triggering a resize of the internal arrays will invalidate it.
    ///</remarks>
    public ref V GetValueRefOrAddDefault(K key, V defaultValue, out bool exists)
    {
        var _key = Unsafe.As<K, byte>(ref key);

        exists = keys.Get(_key);
        bool hasSlot = nullsVal.Get(_key);

        if (exists && hasSlot)
        {
            return ref values[IsFlat ? _key : nullsVal.Rank(_key) - 1];
        }

        //If the key existed but had no physical slot (stored logically as default),
        //we must instantiate its slot with default(V) to preserve its current logical value.
        V insertValue = exists ? default! : defaultValue;

        //1. Flat Strategy Logic
        if (IsFlat)
        {
            if (!exists)
                keys.Set1(_key);
            nullsVal.Set1(_key);
            values[_key] = insertValue;
            return ref values[_key];
        }

        //2. Switch to Flat Strategy if threshold is met
        if (nullsVal.Count == 128 && !hasSlot)
        {
            var values_ = new V[256];
            ref var oldRef = ref MemoryMarshal.GetArrayDataReference(values);
            ref var newRef = ref MemoryMarshal.GetArrayDataReference(values_);
            for (int key_ = -1, ii = 0; (key_ = keys.Next1(key_)) != -1;)
            {
                if (nullsVal[key_])
                    Unsafe.Add(ref newRef, key_) = Unsafe.Add(ref oldRef, ii++);
            }

            values = values_;
            if (!exists)
                keys.Set1(_key);
            nullsVal.Set1(_key);
            values[_key] = insertValue;
            return ref values[_key];
        }

        //3. Compressed Strategy Logic
        var r = nullsVal.Rank(_key);
        BitList.Resize(values, nullsVal.Count < values.Length ? values : values = new V[values.Length * 2], r, nullsVal.Count, 1);
        values[r] = insertValue;

        if (!exists)
            keys.Set1(_key);
        nullsVal.Set1(_key);

        return ref values[r];
    }

    ///<summary>Removes all key-value pairs from the map.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Clear()
    {
        keys.Clear();
        nullsVal.Clear();
    }

    ///<summary>Checks if the map contains the specified key-value pair.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool Contains(KeyValuePair<K, V> item) => TryGetValue(item.Key, out var value) && equal_hash_V.Equals(value, item.Value);

    ///<summary>Copies all key-value pairs to an dst starting at the specified index.</summary>
    public void CopyTo(KeyValuePair<K, V>[] dst, int dstIndex)
    {
        ArgumentNullException.ThrowIfNull(dst);
        ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual((uint)dstIndex, (uint)dst.Length);
        if (dst.Length - dstIndex < Count)
            throw new ArgumentException("Destination array is not long enough.");

        foreach (var kvp in this)
            dst[dstIndex++] = kvp;
    }

    ///<summary>
    ///Returns an enumerator that iterates through the dictionary's key-value pairs,
    ///including the null key if it exists.
    ///</summary>
    ///<returns>An enumerator for the dictionary.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public Enumerator GetEnumerator() => new Enumerator(this);

    ///<summary>
    ///Returns an enumerator that iterates through the dictionary's key-value pairs.
    ///</summary>
    ///<returns>An <see cref="IEnumerator"/> object that can be used to iterate through the dictionary.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

    ///<summary>
    ///Returns an enumerator that iterates through the dictionary's key-value pairs.
    ///</summary>
    ///<returns>An <see cref="IEnumerator{KeyValuePair{K?, V}}"/> that can be used to iterate through the dictionary.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    IEnumerator<KeyValuePair<K, V>> IEnumerable<KeyValuePair<K, V>>.GetEnumerator() => GetEnumerator();

    ///<summary>
    ///Enumerator for iterating over key-value pairs in the ByteMap.
    ///<para>
    ///Walks <c>keys</c> and <c>nullsVal</c> in lockstep at the 64-bit segment level: each
    ///segment of both bitsets is loaded once at the segment boundary, then per-element value
    ///lookup is a single shift+AND against the cached <c>nullsVal</c> segment — no per-element
    ///<c>Get(byte)</c> call (which would re-derive the segment index from the key every time).
    ///<c>values</c> and <c>IsFlat</c> are also snapshotted at construction so the hot path
    ///touches no class fields.
    ///</para>
    ///</summary>
    public struct Enumerator : IEnumerator<KeyValuePair<K, V>>
    {
        private readonly ByteMap<K, V> _map; //for version check only
        private readonly V[] _values;        //snapshot
        private readonly bool _isFlat;       //snapshot

        //Lockstep segment state. _keysSeg has consumed bits cleared; _nullsSeg is the full
        //matching nullsVal segment (we bit-test against it without consuming).
        private ulong _keysSeg;
        private ulong _nullsSeg;
        private int _segmentBase; //-64 = not started; 0/64/128/192 = current; 256 = finished

        private uint _version;
        private int _valIndex;
        private K _currentKey;
        private V _currentValue;
        private bool _hasCurrent;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal Enumerator(ByteMap<K, V> map)
        {
            _map = map;
            _values = map.values;
            _isFlat = map.IsFlat;
            _keysSeg = 0;
            _nullsSeg = 0;
            _segmentBase = -64;
            _version = map.keys._version;
            _valIndex = -1;
            _currentKey = default;
            _currentValue = default!;
            _hasCurrent = false;
        }

        //BCL Dictionary semantics: Current is a bare composition with no per-access checks.
        //Concurrent-modification detection lives entirely in MoveNext (which foreach calls
        //before each Current access), eliminating per-iteration heap deref of `_map.keys._version`.
        public KeyValuePair<K, V> Current
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => new KeyValuePair<K, V>(_currentKey, _currentValue);
        }

        object IEnumerator.Current
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Current;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool MoveNext()
        {
            if (_version != _map.keys._version)
                throw new InvalidOperationException("Collection was modified");

            //Fast path: consume next bit in the current keys segment.
            var keysSeg = _keysSeg;
            if (keysSeg != 0)
            {
                int bit = BitOperations.TrailingZeroCount(keysSeg);
                ulong bitMask = 1UL << bit;
                byte keyByte = (byte)(_segmentBase + bit);
                _keysSeg = keysSeg & (keysSeg - 1);

                _currentKey = Unsafe.As<byte, K>(ref keyByte);
                _currentValue = (_nullsSeg & bitMask) != 0
                                    ? _values[_isFlat ? keyByte : ++_valIndex]
                                    : default!;
                _hasCurrent = true;
                return true;
            }
            return AdvanceSegment();
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private bool AdvanceSegment()
        {
            while (true)
            {
                _segmentBase += 64;
                if ((uint)_segmentBase >= 256u)
                {
                    _segmentBase = 256;
                    _hasCurrent = false;
                    return false;
                }
                int idx = _segmentBase >> 6;
                ulong keysSeg = _map.keys.Segment(idx);
                if (keysSeg == 0)
                    continue;

                _nullsSeg = _map.nullsVal.Segment(idx);

                int bit = BitOperations.TrailingZeroCount(keysSeg);
                ulong bitMask = 1UL << bit;
                byte keyByte = (byte)(_segmentBase + bit);
                _keysSeg = keysSeg & (keysSeg - 1);

                _currentKey = Unsafe.As<byte, K>(ref keyByte);
                _currentValue = (_nullsSeg & bitMask) != 0
                                    ? _values[_isFlat ? keyByte : ++_valIndex]
                                    : default!;
                _hasCurrent = true;
                return true;
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Reset()
        {
            _keysSeg = 0;
            _nullsSeg = 0;
            _segmentBase = -64;
            _valIndex = -1;
            _currentKey = default;
            _currentValue = default!;
            _hasCurrent = false;
            _version = _map.keys._version;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Dispose() { _currentValue = default!; }
    }

    ///<summary>
    ///Returns a string representation of the map in JSON-like format.
    ///</summary>
    public override string ToString()
    {
        var json = new StringBuilder();
        json.Append('{');

        using var e = GetEnumerator();
        while (e.MoveNext())
        {
            json.Append('\n');
            json.Append($"{e.Current.Key}:{e.Current.Value},");
        }

        if (json.Length > 1)
            json.Length -= 1;
        json.Append('}');
        return json.ToString();
    }

    ///<summary>
    ///A read-only collection of keys in the ByteMap.
    ///</summary>
    private class KeyCollection : ICollection<K>
    {
        private readonly ByteMap<K, V> _map;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public KeyCollection(ByteMap<K, V> map) => _map = map;

        public int Count
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _map.Count;
        }

        public bool IsReadOnly
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => true;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Add(K item) => throw new NotSupportedException();

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Clear() => throw new NotSupportedException();

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Contains(K item) => _map.ContainsKey(item);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Remove(K item) => throw new NotSupportedException();

        public void CopyTo(K[] dst, int dstIndex)
        {
            ArgumentNullException.ThrowIfNull(dst);
            ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual((uint)dstIndex, (uint)dst.Length);
            if (dst.Length - dstIndex < Count)
                throw new ArgumentException("Destination array is not long enough.");

            foreach (var kvp in _map)
                dst[dstIndex++] = kvp.Key;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public IEnumerator<K> GetEnumerator() => new KeyEnumerator(_map);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

        ///<summary>
        ///Enumerator for iterating over keys in the ByteMap. Delegates to the
        ///segment-cached <see cref="ByteSet{K}.Enumerator"/>.
        ///</summary>
        private struct KeyEnumerator : IEnumerator<K>
        {
            private readonly ByteMap<K, V> _map;
            private ByteSet<K>.Enumerator _inner;
            private uint _version;
            private K _current;
            private bool _hasCurrent;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal KeyEnumerator(ByteMap<K, V> map)
            {
                _map = map;
                _inner = map.keys.GetEnumerator();
                _version = map.keys._version;
                _current = default;
                _hasCurrent = false;
            }

            public K Current
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get => _current;
            }

            object IEnumerator.Current
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get => Current;
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public bool MoveNext()
            {
                if (_version != _map.keys._version)
                    throw new InvalidOperationException("Collection was modified");
                if (!_inner.MoveNext())
                {
                    _hasCurrent = false;
                    return false;
                }
                _current = _inner.Current;
                _hasCurrent = true;
                return true;
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Reset()
            {
                _inner.Reset();
                _version = _map.keys._version;
                _current = default;
                _hasCurrent = false;
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Dispose() {}
        }
    }

    ///<summary>
    ///A read-only collection of values in the ByteMap.
    ///</summary>
    private class ValueCollection : ICollection<V>
    {
        private readonly ByteMap<K, V> _map;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ValueCollection(ByteMap<K, V> map) => _map = map;

        public int Count
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _map.Count;
        }

        public bool IsReadOnly
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => true;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Add(V item) => throw new NotSupportedException();

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Clear() => throw new NotSupportedException();

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Contains(V item) => _map.Any(kvp => equal_hash_V.Equals(kvp.Value, item));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Remove(V item) => throw new NotSupportedException();

        public void CopyTo(V[] dst, int dstIndex)
        {
            ArgumentNullException.ThrowIfNull(dst);
            ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual((uint)dstIndex, (uint)dst.Length);
            if (dst.Length - dstIndex < Count)
                throw new ArgumentException("Destination array is not long enough.");

            foreach (var kvp in _map)
                dst[dstIndex++] = kvp.Value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public IEnumerator<V> GetEnumerator() => new ValueEnumerator(_map);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

        ///<summary>
        ///Enumerator for iterating over values in the ByteMap. Uses the same lockstep
        ///segment walk as <see cref="ByteMap{K,V}.Enumerator"/> — segments of <c>keys</c>
        ///and <c>nullsVal</c> are loaded together at segment boundaries, value resolution
        ///per element is a single bit test.
        ///</summary>
        private struct ValueEnumerator : IEnumerator<V>
        {
            private readonly ByteMap<K, V> _map;
            private readonly V[] _values;
            private readonly bool _isFlat;

            private ulong _keysSeg;
            private ulong _nullsSeg;
            private int _segmentBase;
            private uint _version;
            private int _valIndex;
            private V _current;
            private bool _hasCurrent;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal ValueEnumerator(ByteMap<K, V> map)
            {
                _map = map;
                _values = map.values;
                _isFlat = map.IsFlat;
                _keysSeg = 0;
                _nullsSeg = 0;
                _segmentBase = -64;
                _version = map.keys._version;
                _valIndex = -1;
                _current = default!;
                _hasCurrent = false;
            }

            public V Current
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get => _current;
            }

            object IEnumerator.Current
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get => Current;
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public bool MoveNext()
            {
                if (_version != _map.keys._version)
                    throw new InvalidOperationException("Collection was modified");

                var keysSeg = _keysSeg;
                if (keysSeg != 0)
                {
                    int bit = BitOperations.TrailingZeroCount(keysSeg);
                    ulong bitMask = 1UL << bit;
                    byte keyByte = (byte)(_segmentBase + bit);
                    _keysSeg = keysSeg & (keysSeg - 1);

                    _current = (_nullsSeg & bitMask) != 0
                                   ? _values[_isFlat ? keyByte : ++_valIndex]
                                   : default!;
                    _hasCurrent = true;
                    return true;
                }
                return AdvanceSegment();
            }

            [MethodImpl(MethodImplOptions.NoInlining)]
            private bool AdvanceSegment()
            {
                while (true)
                {
                    _segmentBase += 64;
                    if ((uint)_segmentBase >= 256u)
                    {
                        _segmentBase = 256;
                        _hasCurrent = false;
                        _current = default!;
                        return false;
                    }
                    int idx = _segmentBase >> 6;
                    ulong keysSeg = _map.keys.Segment(idx);
                    if (keysSeg == 0)
                        continue;

                    _nullsSeg = _map.nullsVal.Segment(idx);

                    int bit = BitOperations.TrailingZeroCount(keysSeg);
                    ulong bitMask = 1UL << bit;
                    byte keyByte = (byte)(_segmentBase + bit);
                    _keysSeg = keysSeg & (keysSeg - 1);

                    _current = (_nullsSeg & bitMask) != 0
                                   ? _values[_isFlat ? keyByte : ++_valIndex]
                                   : default!;
                    _hasCurrent = true;
                    return true;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Reset()
            {
                _keysSeg = 0;
                _nullsSeg = 0;
                _segmentBase = -64;
                _valIndex = -1;
                _current = default!;
                _hasCurrent = false;
                _version = _map.keys._version;
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Dispose() { _current = default!; }
        }
    }
}