//Copyright 2025 Chikirev Sirguy, Unirail Group. All rights reserved.
//
//This file is part of the AdHoc protocol runtime library.
//
//Licensed under the PolyForm Shield License 1.0.0. The full text is distributed with this
//file as LICENSE.md and is published at https://polyformproject.org/licenses/shield/1.0.0
//
//In short: you may use, modify and distribute this software for any purpose, except to
//provide a product that competes with the software, or with any product the licensor
//provides using the software. Competition is judged by function, not by form.
//
//The plain-text notice lines the license requires you to pass on - the Required Notice and
//the Licensor Line of Business - are in the NOTICE file distributed with this library.
//Keep LICENSE.md and NOTICE with any copy of this software that you distribute.
//
//Code generated by the AdHoc generator is NOT part of the Licensed Work and carries no
//restrictions whatsoever - see the header of any generated file.
//
//Provided as is, without any warranty or condition.
//
//Commercial licenses that remove the noncompete restriction are available.
//For licensing and inquiries: al8v5C6HU4UtqE9@gmail.com

using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace org.unirail.collections;

///<summary>
///A generic dictionary with reference-type keys, optimized for top throughput and minimal GC pressure.
///<para><b>Storage layout (selected design — single Entry array + side _links):</b></para>
///<para>
///A single <see cref="Entry"/> array is split into two regions:
///<list type="bullet">
///<item><b>Hi-region</b> [<c>_entries.Length - _hiSize .. _entries.Length</c>) — chain terminators
///(entries placed when their bucket was empty).</item>
///<item><b>Lo-region</b> [<c>0 .. _loSize</c>) — collision-chain entries. Their successor index lives
///in a separate <c>_links</c> array sized only to <c>_loSize</c>, so memory is paid only for actual
///collisions.</item>
///</list>
///Chain termination is detected implicitly via <c>_loSize &lt;= i</c> while walking — no sentinel
///and no per-hop region flag needed.
///</para>
///
///<para><b>Alternative considered: Option D — split <c>LoEntry</c>/<c>HiEntry</c> types</b></para>
///<para>
///Inlining <c>next</c> into a typed <c>LoEntry</c> struct would save one cache-line load per chain
///hop on collision walks. Prototyped and benchmarked against this layout for <c>Map&lt;string,int&gt;</c>:
///every method regressed — including the forced-collision case Option D was meant to win, where the
///measured throughput dropped 20%. The locality of a single shared <c>_entries</c> array beats the
///theoretical inlined-next saving, because typical workloads have short chains (Poisson-weighted
///average ~1.76 at 75% load) that don't amortize the dispatch overhead between two typed regions.
///The same outcome was observed earlier on <c>PrimitiveKeyMap</c>, so Option D is rejected for both
///class and unmanaged key maps.
///</para>
///
///<para><b>Benchmark vs <c>Dictionary&lt;string,int&gt;</c></b> (N = 100 000, 15-char string keys, .NET 9, Release;
///median of 7–10 runs):</para>
///<code>
///Insert       Search          Get          Iterate       Delete       Churn
///Map&lt;string,int&gt;       26 335 591   48 785 927   35 753 505    1 305 000 000   20 000 000   16 100 000   ops/sec
///Dictionary                  0.97         0.83         0.98             0.91         1.11         1.46   x
///</code>
///<para><b>Memory profile (grow-from-empty Insert, 100 000 string keys):</b>
///<list type="bullet">
///<item><c>Map</c> allocates <b>57.68 B/op</b> (grow-from-empty Insert of 100 000 records)</item>
///<item><c>Dictionary</c> allocates <b>84.52 B/op</b></item>
///<item><c>Map</c> saves <b>~26 840 B per 1 000 records</b> vs Dictionary</item>
///</list>
///</para>
///<para>
///Ratio &gt; 1 ⇒ <c>Dictionary</c> faster, &lt; 1 ⇒ <c>Map</c> faster. Map matches or beats Dictionary
///on read-heavy paths (Search/Get/Insert) and <b>beats Dictionary on Iterate by ~10%</b> (structural
///advantage of the packed dual-region layout — entries occupy
///<c>[0..loSize) ∪ [Length-hiSize..Length)</c>, no holes within either region). Remove/churn gap to
///Dictionary's freelist-O(1) closed dramatically: Remove went from 1.64× to 1.10× behind, Churn
///from 1.89× to 1.48× behind. The win came from skipping the JIT-emitted array-bounds checks
///during the chain walks — <c>Unsafe.Add</c> + <c>MemoryMarshal.GetArrayDataReference</c> on
///<c>_entries</c>/<c>_links</c>: every chain hop was paying for a bounds check we'd already proven
///safe. The remaining churn gap is structural: Map's <c>Move</c> still walks the moved entry's
///chain to rewire its predecessor's link (vs Dictionary's O(1) freelist add).
///</para>
///<para>See <c>Tests/Benchmarks/MapBenchmark.cs</c> for the full scenarios and an HTML report.</para>
///</summary>
///<typeparam name="K">The reference-type key.</typeparam>
///<typeparam name="V">The value type.</typeparam>
[DebuggerDisplay("Count = {Count}")]
public class Map<K, V> : IDictionary<K, V>, IReadOnlyDictionary<K, V>, IEquatable<Map<K, V>>
    where K : class
{
    private struct Entry
    {
        public int hash;
        public K key;
        public V value;
    }

    private uint[]? _buckets;
    private Entry[]? _entries;
    private uint[]? _links; //0-based indices into _entries for collision chains.

    //_entries split:
    //  Lo-region [0 .. _loSize)               — collision-chain elements
    //  Hi-region [Length-_hiSize .. Length)   — chain terminators (no successor)
    private int _hiSize;
    private int _loSize;

    private int _version;

    private uint _mask;

    //null = use EqualityComparer<K>.Default. Routing every key compare through a non-null
    //IEqualityComparer<K> field forces an interface call the JIT cannot devirtualize, costing
    //19-35% across all key-compare hot paths. The branch on null lets the JIT specialize for
    //sealed K (string, etc.) by going through the static Default singleton.
    private readonly IEqualityComparer<K>? _customComparer;

    private KeysCollection? _keys;
    private ValuesCollection? _values;

    private const int DefaultCapacity = 4;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private int KeyHash(K key) => _customComparer == null ? EqualityComparer<K>.Default.GetHashCode(key) : _customComparer.GetHashCode(key);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private bool KeyEquals(K a, K b) => _customComparer == null ? EqualityComparer<K>.Default.Equals(a, b) : _customComparer.Equals(a, b);

    ///<summary>The effective comparer in use (caller-provided, or <see cref="EqualityComparer{K}.Default"/>).</summary>
    public IEqualityComparer<K> Comparer
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => _customComparer ?? EqualityComparer<K>.Default;
    }
#region Constructors
    public Map() : this(0, null) {}
    public Map(int capacity) : this(capacity, null) {}
    public Map(IDictionary<K, V> dictionary) : this(dictionary, null) {}
    public Map(IEqualityComparer<K>? comparer) : this(0, comparer) {}

    public Map(int capacity, IEqualityComparer<K>? comparer)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(capacity);
        _customComparer = comparer;
        if (capacity > 0)
            Initialize(capacity);
    }

    public Map(IDictionary<K, V> dictionary, IEqualityComparer<K>? comparer)
        : this(dictionary?.Count ?? 0, comparer)
    {
        ArgumentNullException.ThrowIfNull(dictionary);
        AddRange(dictionary);
    }
#endregion

    private void AddRange(IEnumerable<KeyValuePair<K, V>> enumerable)
    {
        foreach (var pair in enumerable)
            Add(pair.Key, pair.Value);
    }

    public int Count
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => _loSize + _hiSize;
    }

    public bool IsReadOnly
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => false;
    }

    public V this[K key]
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            ArgumentNullException.ThrowIfNull(key);
            ref var entry = ref FindEntry(key);
            if (Unsafe.IsNullRef(ref entry))
                throw new KeyNotFoundException("The given key was not present in the dictionary.");
            return entry.value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        //TryInsert performs the null check; calling it again here would be a redundant branch.
        set => TryInsert(key, value, true);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Add(K key, V value)
    {
        if (!TryInsert(key, value, false))
            throw new ArgumentException("An item with the same key has already been added.");
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Add(KeyValuePair<K, V> item) => Add(item.Key, item.Value);

    ///<summary>Attempts to add the specified key and value. Returns false if the key already exists.</summary>
    ///<remarks>Native implementation. Avoids the BCL <c>IDictionary&lt;K,V&gt;</c> extension method's
    ///double dispatch (ContainsKey + Add).</remarks>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool TryAdd(K key, V value) => TryInsert(key, value, false);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private bool TryInsert(K key, V value, bool overwrite)
    {
        ArgumentNullException.ThrowIfNull(key);

        if (_buckets == null)
            Initialize(DefaultCapacity);

        var entries = _entries!;
        if (entries.Length <= _loSize + _hiSize)
        {
            Resize(entries.Length * 2);
            entries = _entries!;
        }

        var hashCode = KeyHash(key);
        ref var bucket = ref GetBucket((uint)hashCode);
        ref var entries0 = ref MemoryMarshal.GetArrayDataReference(entries);

        int dstIndex;
        if (bucket == 0)
            dstIndex = entries.Length - 1 - _hiSize++; //Empty bucket → place in hi-region.
        else
        {
            //Cache links0 only for the read-only chain walk. The post-walk lo-insert may
            //call Array.Resize(ref _links, ...) which would invalidate this ref, so the
            //write below uses the _links! field directly.
            ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
            var loSize = _loSize;
            for (uint i = bucket - 1, collisions = 0;;)
            {
                ref var entry = ref Unsafe.Add(ref entries0, i);
                if (entry.hash == hashCode && KeyEquals(entry.key, key))
                {
                    if (!overwrite)
                        return false;
                    entry.value = value;
                    _version++;
                    return false;
                }

                if (loSize <= i)
                    break; //Reached hi-region terminator without match.
                i = Unsafe.Add(ref links0, i);
                if (loSize + 1 < collisions++)
                    throw new InvalidOperationException("Concurrent operations not supported.");
            }

            //Push new entry on chain head in lo-region.
            if (_links!.Length == (dstIndex = _loSize++))
                Array.Resize(ref _links, Math.Max(16, Math.Min(_buckets!.Length, _links.Length * 2)));
            _links[dstIndex] = bucket - 1;
        }

        ref var newEntry = ref Unsafe.Add(ref entries0, dstIndex);
        newEntry.hash = hashCode;
        newEntry.key = key;
        newEntry.value = value;
        bucket = (uint)(dstIndex + 1);
        _version++;
        return true;
    }

    public void Clear()
    {
        if (Count == 0)
            return;
        _version++;
        if (_buckets != null)
            Array.Clear(_buckets, 0, _buckets.Length);
        _loSize = _hiSize = 0;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool ContainsKey(K key)
    {
        ArgumentNullException.ThrowIfNull(key);
        return !Unsafe.IsNullRef(ref FindEntry(key));
    }

    public bool ContainsValue(V value)
    {
        var cmp = EqualityComparer<V>.Default;
        for (var i = 0; i < _loSize; i++)
            if (cmp.Equals(_entries![i].value, value))
                return true;
        if (_hiSize == 0)
            return false;
        for (var i = _entries!.Length - _hiSize; i < _entries.Length; i++)
            if (cmp.Equals(_entries![i].value, value))
                return true;
        return false;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool TryGetValue(K key, [MaybeNullWhen(false)] out V value)
    {
        ArgumentNullException.ThrowIfNull(key);
        ref var entry = ref FindEntry(key);
        if (Unsafe.IsNullRef(ref entry))
        {
            value = default;
            return false;
        }

        value = entry.value;
        return true;
    }

    ///<summary>
    ///Internal entry-finder. Returns a ref to the entry on hit, or a null ref on miss
    ///(<see cref="Unsafe.IsNullRef{T}"/>). Marked AggressiveInlining so callers (TryGetValue,
    ///ContainsKey, indexer) inline the body — empirically the best variant tested.
    ///</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private ref Entry FindEntry(K key)
    {
        if (_loSize + _hiSize == 0)
            return ref Unsafe.NullRef<Entry>();

        var hashCode = KeyHash(key);
        var i = (int)GetBucket((uint)hashCode) - 1;
        if (i == -1)
            return ref Unsafe.NullRef<Entry>();

        ref var entry = ref _entries![i];
        for (var collisions = 0; entry.hash != hashCode || !KeyEquals(entry.key, key); entry = ref _entries![i = (int)_links![i]])
        {
            if (_loSize <= i)
                return ref Unsafe.NullRef<Entry>();
            if (_loSize < ++collisions)
                throw new InvalidOperationException("Hash collision chain is unexpectedly long. Possible data corruption.");
        }

        return ref entry;
    }

    public ICollection<K> Keys
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => _keys ??= new KeysCollection(this);
    }

    public ICollection<V> Values
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => _values ??= new ValuesCollection(this);
    }

    IEnumerable<K> IReadOnlyDictionary<K, V>.Keys
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => Keys;
    }

    IEnumerable<V> IReadOnlyDictionary<K, V>.Values
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => Values;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private ref uint GetBucket(uint hashCode) => ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_buckets!), hashCode &_mask);

    private int Initialize(int capacity, int linksHint = 16)
    {
        _version++;
        var size = GetPowerOfTwo(capacity);
        _buckets = new uint[size];
        _entries = new Entry[size];
        _links = new uint[Math.Min(size, linksHint)];
        _loSize = _hiSize = 0;
        _mask = (uint)(size - 1);
        return size;
    }

    ///<summary>
    ///Gets a reference to the value associated with the specified key, adding a provided default value if the key does not exist.
    ///</summary>
    ///<remarks>Do not add or remove items while holding this reference; a resize will invalidate it.</remarks>
    public ref V GetValueRefOrAddDefault(K key, V defaultValue, out bool exists)
    {
        ArgumentNullException.ThrowIfNull(key);
        if (_buckets == null)
            Initialize(DefaultCapacity);

        var entries = _entries!;
        if (entries.Length <= _loSize + _hiSize)
        {
            Resize(entries.Length * 2);
            entries = _entries!;
        }

        var hashCode = KeyHash(key);
        ref var bucket = ref GetBucket((uint)hashCode);
        ref var entries0 = ref MemoryMarshal.GetArrayDataReference(entries);

        int dstIndex;
        if (bucket == 0)
            dstIndex = entries.Length - 1 - _hiSize++;
        else
        {
            //Cache links0 only for the read-only chain walk. Post-walk insert may
            //Array.Resize(_links) and invalidate this ref, so the write uses _links! directly.
            ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
            var loSize = _loSize;
            for (uint i = bucket - 1, collisions = 0;;)
            {
                ref var entry = ref Unsafe.Add(ref entries0, i);
                if (entry.hash == hashCode && KeyEquals(entry.key, key))
                {
                    exists = true;
                    return ref entry.value;
                }

                if (loSize <= i)
                    break;
                i = Unsafe.Add(ref links0, i);
                if (loSize + 1 < collisions++)
                    throw new InvalidOperationException("Concurrent operations not supported.");
            }

            if (_links!.Length == (dstIndex = _loSize++))
                Array.Resize(ref _links, Math.Max(16, Math.Min(_buckets!.Length, _links.Length * 2)));
            _links[dstIndex] = bucket - 1;
        }

        ref var newEntry = ref Unsafe.Add(ref entries0, dstIndex);
        newEntry.hash = hashCode;
        newEntry.key = key;
        newEntry.value = defaultValue;
        bucket = (uint)(dstIndex + 1);
        _version++;
        exists = false;
        return ref newEntry.value;
    }

    ///<summary>
    ///Rebuilds the table at <paramref name="newSize"/>, re-inserting every old entry.
    ///<para>
    ///<b>Memory win — pre-size <c>_links</c> once.</b> The previous implementation called a per-entry
    ///<c>Copy</c> helper that doubled <c>_links</c> from 16 → 32 → 64 → … → roundUpPowerOf2(N) as
    ///entries streamed in. For a Resize that re-inserts ~75 000 lo-entries (typical at 100k load),
    ///that's ~13 <c>Array.Resize</c> calls allocating cumulatively <b>~1 MB</b> of arrays that all
    ///become garbage, plus the final ~512 KB kept array. By passing the precise <c>linksHint</c> to
    ///<c>Initialize</c>, we make <b>zero</b> intermediate allocations and the kept array is right-sized.
    ///</para>
    ///<para><b>Speed win — hoist hot fields.</b> The per-entry rebuild loop reads <c>_buckets</c>,
    ///<c>_mask</c>, <c>_hiSize</c>, <c>_loSize</c> on every iteration. The JIT cannot hoist them
    ///across the <c>_hiSize++</c>/<c>_loSize++</c> writes (it cannot prove the writes don't alias
    ///other field loads), so they compile to repeated memory loads. We hoist them into locals
    ///(<c>buckets0</c>, <c>mask</c>, <c>hiSize</c>, <c>loSize</c>) and write back at the end.
    ///Combined with cached <c>Unsafe.Add</c> refs and no JIT bounds checks, the loop body reduces
    ///to register-only work plus the unavoidable memory writes.</para>
    ///</summary>
    private int Resize(int newSize)
    {
        _version++;
        var oldEntries = _entries;
        var oldLoSize = _loSize;
        var oldHiSize = _hiSize;
        var oldEnd = oldEntries!.Length;
        var oldHiStart = oldEnd - oldHiSize;

        //Pass the precise linksHint so Initialize sizes _links to fit all surviving entries
        //worst-case (every old entry could re-collide into lo). No throwaway 16-element alloc.
        var totalEntries = oldLoSize + oldHiSize;
        Initialize(newSize, totalEntries);

        ref var oldEntries0 = ref MemoryMarshal.GetArrayDataReference(oldEntries);
        ref var entries0 = ref MemoryMarshal.GetArrayDataReference(_entries!);
        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        ref var buckets0 = ref MemoryMarshal.GetArrayDataReference(_buckets!);
        var mask = _mask;
        var newEnd = _entries!.Length;
        var loSize = 0;
        var hiSize = 0;

        //Re-insert lo region [0..oldLoSize)
        for (var i = 0; i < oldLoSize; i++)
        {
            ref var entry = ref Unsafe.Add(ref oldEntries0, i);
            ref var bucket = ref Unsafe.Add(ref buckets0, (nint)((uint)entry.hash & mask));
            var prev = (int)bucket - 1;
            int dstIndex;

            if (prev == -1)
                dstIndex = newEnd - 1 - hiSize++;
            else
            {
                dstIndex = loSize++; //pre-sized: never resizes here
                Unsafe.Add(ref links0, dstIndex) = (uint)prev;
            }

            Unsafe.Add(ref entries0, dstIndex) = entry;
            bucket = (uint)(dstIndex + 1);
        }

        //Re-insert hi region [oldHiStart..oldEnd)
        for (var i = oldHiStart; i < oldEnd; i++)
        {
            ref var entry = ref Unsafe.Add(ref oldEntries0, i);
            ref var bucket = ref Unsafe.Add(ref buckets0, (nint)((uint)entry.hash & mask));
            var prev = (int)bucket - 1;
            int dstIndex;

            if (prev == -1)
                dstIndex = newEnd - 1 - hiSize++;
            else
            {
                dstIndex = loSize++;
                Unsafe.Add(ref links0, dstIndex) = (uint)prev;
            }

            Unsafe.Add(ref entries0, dstIndex) = entry;
            bucket = (uint)(dstIndex + 1);
        }

        _loSize = loSize;
        _hiSize = hiSize;
        return newSize;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void Move(int src, int dst, ref Entry dstEntry)
    {
        _version++;
        if (src == dst)
            return;

        //Skip the array-bounds checks: src < _entries.Length and the chain-walked
        //indices are bounded by the same. Same trick the BCL uses internally.
        ref var entries0 = ref MemoryMarshal.GetArrayDataReference(_entries!);
        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        ref var srcEntry = ref Unsafe.Add(ref entries0, src);
        ref var srcBucket = ref GetBucket((uint)srcEntry.hash);
        var index = (int)srcBucket - 1;

        if (index == src)
            srcBucket = (uint)(dst + 1);
        else
        {
            //Walk the source's chain until we find the link that points at `src`,
            //then rewire it to `dst` in O(1) at that link. Chain length is the
            //structural cost vs Dictionary's freelist O(1) — unavoidable without
            //adding a back-pointer per Entry (4 bytes/entry memory cost).
            ref var link = ref Unsafe.Add(ref links0, index);
            while (link != src)
            {
                index = (int)link;
                link = ref Unsafe.Add(ref links0, index);
            }

            link = (uint)dst;
        }

        if (src < _loSize)
            Unsafe.Add(ref links0, dst) = Unsafe.Add(ref links0, src);

        dstEntry = srcEntry;
    }

    ///<summary>
    ///Removes <paramref name="key"/> if present.
    ///<para>Index-based chain walk (no <c>ref</c> aliasing across iterations) so the JIT can keep
    ///the loop in registers. The walker tracks the immediate predecessor (<c>prev</c>) and the
    ///pre-predecessor (<c>prevPrev</c>) so the hi-terminator migration case can rewire the back-pointer
    ///in O(1) instead of re-walking. Hot fields (<c>_entries</c>, <c>_links</c>, <c>_loSize</c>) are
    ///hoisted into locals.</para>
    ///</summary>
    public bool Remove(K key)
    {
        ArgumentNullException.ThrowIfNull(key);
        if (_loSize + _hiSize == 0)
            return false;

        var hashCode = KeyHash(key);
        ref var bucket = ref GetBucket((uint)hashCode);
        var idx = (int)bucket - 1;
        if (idx < 0)
            return false;

        //Hoist hot fields and snapshot raw array data refs so the chain walk avoids
        //per-element bounds checks. Same Unsafe.Add trick used in MoveNext — we already
        //know each idx came from `bucket - 1` or a `links[i]` chain-link, both bounded
        //by _entries.Length, so the JIT-emitted bounds check is provably redundant.
        var loSize = _loSize;
        ref var entries0 = ref MemoryMarshal.GetArrayDataReference(_entries!);

        //Chain length 1: the only entry sits in hi-region (the original empty-bucket placement).
        //Bucket goes empty; compact hi-region by moving the newest hi entry into the hole.
        ref var e = ref Unsafe.Add(ref entries0, idx);
        if (loSize <= idx)
        {
            if (e.hash != hashCode || !KeyEquals(e.key, key))
                return false;
            Move(_entries!.Length - _hiSize, idx, ref e);
            _hiSize--;
            bucket = 0;
            return true;
        }

        //Walk the lo-portion of the chain. Track prev/prevPrev as plain indices.
        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        var prev = -1;     //immediate predecessor (-1 means current is at chain head; bucket points to it)
        var prevPrev = -1; //predecessor's predecessor (-1 means prev is at chain head)

        for (var collisions = 0; e.hash != hashCode || !KeyEquals(e.key, key); prevPrev = prev, e = ref Unsafe.Add(ref entries0, idx = (int)Unsafe.Add(ref links0, prev = idx)))
        {
            if (idx >= loSize)
                return false; //chain terminator without match
            if (++collisions > loSize)
                throw new InvalidOperationException("Hash collision chain is unexpectedly long. Possible data corruption.");
        }

        var lastLo = loSize - 1;
        if (idx < loSize)
        {
            //Standard removal: rewire (prev or bucket) → next; compact lo by swap-with-last.
            //Single read of the matched entry's link; both branches consume `next`.
            var next = Unsafe.Add(ref links0, idx);
            if (prev < 0)
                bucket = next + 1;
            else
                Unsafe.Add(ref links0, prev) = next;
            Move(lastLo, idx, ref e);
        }
        else
        {
            //Found at hi-terminator with chain length ≥ 2. Migrate prev (lo) into the hi slot
            //so the chain still terminates in hi; prev's lo slot becomes the hole.
            ref var prevEntry = ref Unsafe.Add(ref entries0, prev);
            e = prevEntry;
            if (prevPrev < 0)
                bucket = (uint)(idx + 1);
            else
                Unsafe.Add(ref links0, prevPrev) = (uint)idx;
            Move(lastLo, prev, ref prevEntry);
        }

        _loSize = lastLo;
        return true;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool Remove(KeyValuePair<K, V> item) => TryGetValue(item.Key, out var value) && EqualityComparer<V>.Default.Equals(value, item.Value) && Remove(item.Key);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool Contains(KeyValuePair<K, V> item) => TryGetValue(item.Key, out var value) && EqualityComparer<V>.Default.Equals(value, item.Value);

    public void CopyTo(KeyValuePair<K, V>[] dst, int dstIndex)
    {
        ArgumentNullException.ThrowIfNull(dst);
        ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual((uint)dstIndex, (uint)dst.Length);
        if (dst.Length - dstIndex < Count)
            throw new ArgumentException("Destination array is not long enough.");

        if (_entries == null)
            return;

        for (var i = 0; i < _loSize; i++)
        {
            ref var entry = ref _entries[i];
            dst[dstIndex++] = new KeyValuePair<K, V>(entry.key, entry.value);
        }

        if (_hiSize == 0)
            return;
        for (var i = _entries.Length - _hiSize; i < _entries.Length; i++)
        {
            ref var entry = ref _entries[i];
            dst[dstIndex++] = new KeyValuePair<K, V>(entry.key, entry.value);
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static int GetPowerOfTwo(int capacity) => capacity <= DefaultCapacity ? DefaultCapacity : (int)BitOperations.RoundUpToPowerOf2((uint)capacity);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public Enumerator GetEnumerator() => new(this);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    IEnumerator<KeyValuePair<K, V>> IEnumerable<KeyValuePair<K, V>>.GetEnumerator() => GetEnumerator();

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

    public struct Enumerator : IEnumerator<KeyValuePair<K, V>>
    {
        //Snapshot the layout at construction so MoveNext only reads instance fields when
        //version-checking. Field reads on a heap object cost a load + a possible cache miss
        //per call; locals stay in registers across the iteration. Same approach the BCL
        //Dictionary enumerator uses.
        private readonly Map<K, V> _map;
        private readonly Entry[]? _entries;
        private readonly int _loEnd;   //_loSize at construction
        private readonly int _hiStart; //_entries.Length - _hiSize at construction
        private readonly int _hiEnd;   //_entries.Length at construction

        private readonly int _version;

        //_index uses a single sentinel — _hiEnd — for "finished" so MoveNext doesn't need
        //a separate -2 check on the hot path. Initial -1 is the "not started" state; any
        //value in [0, _loEnd) ∪ [_hiStart, _hiEnd) is the current entry index.
        private int _index;
        private KeyValuePair<K, V> _current;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal Enumerator(Map<K, V> map)
        {
            _map = map;
            _version = map._version;
            _entries = map._entries;
            _loEnd = map._loSize;
            _hiEnd = _entries?.Length ?? 0;
            _hiStart = _hiEnd - map._hiSize;
            _index = -1;
            _current = default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool MoveNext()
        {
            if (_version != _map._version)
                throw new InvalidOperationException("Collection was modified during enumeration.");

            //Single linear walk: 0 .. _loEnd, then _hiStart .. _hiEnd. Fold the
            //"already finished" detection into the same `i >= _hiEnd` test that
            //signals end-of-iteration, eliminating the separate -2 check.
            int i = _index + 1;
            if (i == _loEnd)
                i = _hiStart; //bridge fires at most once per enumeration
            if (i >= _hiEnd)
            {
                _index = _hiEnd;
                return false;
            }

            //Skip the array-bounds check: we just verified `i < _hiEnd ≤ _entries.Length`,
            //so the JIT-generated `_entries![i]` bounds check is provably redundant.
            //MemoryMarshal.GetArrayDataReference + Unsafe.Add lets us skip it.
            ref var entry = ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_entries!), i);
            _current = new KeyValuePair<K, V>(entry.key, entry.value);
            _index = i;
            return true;
        }

        //Matches BCL Dictionary: Current is a bare field read with no checks.
        //Concurrent-modification detection lives entirely in MoveNext, which is what
        //foreach calls before each Current access — sufficient to catch real-world misuse,
        //and removing the per-iteration heap deref of `_map._version` here halves the
        //version-check cost of foreach iteration.
        public KeyValuePair<K, V> Current
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _current;
        }

        object? IEnumerator.Current
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Current;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Reset()
        {
            if (_version != _map._version)
                throw new InvalidOperationException("Collection was modified during enumeration.");
            _index = -1;
            _current = default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Dispose() {}
    }

    public int EnsureCapacity(int capacity)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(capacity);
        var currentCapacity = _entries?.Length ?? 0;
        if (currentCapacity >= capacity)
            return currentCapacity;
        _version++;
        return _buckets == null ? Initialize(capacity) : Resize(GetPowerOfTwo(capacity));
    }

    public void TrimExcess()
    {
        var count = Count;
        if (count == 0)
        {
            Initialize(0);
            _version++;
            return;
        }

        if (_entries != null && GetPowerOfTwo(count) < _entries.Length)
            Resize(GetPowerOfTwo(count));
    }
#region Equality
    public bool Equals(Map<K, V>? other)
    {
        if (other == null || Count != other.Count || !Comparer.Equals(other.Comparer))
            return false;
        foreach (var pair in this)
            if (!other.TryGetValue(pair.Key, out var otherValue) || !EqualityComparer<V>.Default.Equals(pair.Value, otherValue))
                return false;
        return true;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public override bool Equals(object? obj) => Equals(obj as Map<K, V>);

    public override int GetHashCode()
    {
        var hashCode = Comparer.GetHashCode();
        for (var i = 0; i < _loSize; i++)
        {
            var entry = _entries![i];
            hashCode ^= entry.hash ^ (entry.value?.GetHashCode() ?? 0);
        }

        if (_hiSize == 0)
            return hashCode;
        for (var i = _entries!.Length - _hiSize; i < _entries.Length; i++)
        {
            var entry = _entries[i];
            hashCode ^= entry.hash ^ (entry.value?.GetHashCode() ?? 0);
        }

        return hashCode;
    }
#endregion
#region Helper Collections
    [DebuggerDisplay("Count = {Count}")]
    public sealed class KeysCollection : ICollection<K>, IReadOnlyCollection<K>
    {
        private readonly Map<K, V> map;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public KeysCollection(Map<K, V> map) => this.map = map;

        public int Count
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => map.Count;
        }
        public bool IsReadOnly
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => true;
        }

        public void CopyTo(K[] dst, int dstIndex)
        {
            ArgumentNullException.ThrowIfNull(dst);
            ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual((uint)dstIndex, (uint)dst.Length);
            if (dst.Length - dstIndex < Count)
                throw new ArgumentException("Destination array is not long enough.");
            foreach (var item in map)
                dst[dstIndex++] = item.Key;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Contains(K item) => map.ContainsKey(item);
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Enumerator GetEnumerator() => new(map);
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        IEnumerator<K> IEnumerable<K>.GetEnumerator() => GetEnumerator();
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        void ICollection<K>.Add(K item) => throw new NotSupportedException();
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        bool ICollection<K>.Remove(K item) => throw new NotSupportedException();
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        void ICollection<K>.Clear() => throw new NotSupportedException();

        public struct Enumerator : IEnumerator<K>
        {
            private Map<K, V>.Enumerator _dictEnumerator;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal Enumerator(Map<K, V> dictionary) => _dictEnumerator = dictionary.GetEnumerator();

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public bool MoveNext() => _dictEnumerator.MoveNext();
            public K Current
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get => _dictEnumerator.Current.Key;
            }
            object? IEnumerator.Current
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get => Current;
            }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Dispose() => _dictEnumerator.Dispose();
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Reset() => _dictEnumerator.Reset();
        }
    }

    [DebuggerDisplay("Count = {Count}")]
    public sealed class ValuesCollection : ICollection<V>, IReadOnlyCollection<V>
    {
        private readonly Map<K, V> map;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ValuesCollection(Map<K, V> map) => this.map = map;

        public int Count
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => map.Count;
        }
        public bool IsReadOnly
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => true;
        }

        public void CopyTo(V[] dst, int dstIndex)
        {
            ArgumentNullException.ThrowIfNull(dst);
            ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual((uint)dstIndex, (uint)dst.Length);
            if (dst.Length - dstIndex < Count)
                throw new ArgumentException("Destination array is not long enough.");
            foreach (var item in map)
                dst[dstIndex++] = item.Value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Contains(V item) => map.ContainsValue(item);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Enumerator GetEnumerator() => new(map);
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        IEnumerator<V> IEnumerable<V>.GetEnumerator() => GetEnumerator();
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        void ICollection<V>.Add(V item) => throw new NotSupportedException();
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        bool ICollection<V>.Remove(V item) => throw new NotSupportedException();
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        void ICollection<V>.Clear() => throw new NotSupportedException();

        public struct Enumerator : IEnumerator<V>
        {
            private Map<K, V>.Enumerator _dictEnumerator;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal Enumerator(Map<K, V> dictionary) => _dictEnumerator = dictionary.GetEnumerator();

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public bool MoveNext() => _dictEnumerator.MoveNext();
            public V Current
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get => _dictEnumerator.Current.Value;
            }
            object? IEnumerator.Current
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get => Current;
            }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Dispose() => _dictEnumerator.Dispose();
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Reset() => _dictEnumerator.Reset();
        }
    }
#endregion
}