//Copyright 2025 Chikirev Sirguy, Unirail Group. All rights reserved.
//
//This file is part of the AdHoc protocol runtime library.
//
//Licensed under the PolyForm Shield License 1.0.0. The full text is distributed with this
//file as LICENSE.md and is published at https://polyformproject.org/licenses/shield/1.0.0
//
//In short: you may use, modify and distribute this software for any purpose, except to
//provide a product that competes with the software, or with any product the licensor
//provides using the software. Competition is judged by function, not by form.
//
//The plain-text notice lines the license requires you to pass on - the Required Notice and
//the Licensor Line of Business - are in the NOTICE file distributed with this library.
//Keep LICENSE.md and NOTICE with any copy of this software that you distribute.
//
//Code generated by the AdHoc generator is NOT part of the Licensed Work and carries no
//restrictions whatsoever - see the header of any generated file.
//
//Provided as is, without any warranty or condition.
//
//Commercial licenses that remove the noncompete restriction are available.
//For licensing and inquiries: al8v5C6HU4UtqE9@gmail.com

using System;
using System.Collections;
using System.Collections.Generic;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace org.unirail.collections;

///<summary>
///Represents a set of unique nullable primitive values of type <typeparamref name="K"/>.
///This set implementation uses a hash table and is optimized for nullable primitive types.
///It supports the inclusion of a single null value.
///
///<para><b>Benchmark vs <c>HashSet&lt;int?&gt;</c></b> (N = 100 000 random int keys, .NET 9, Release):</para>
///<code>
///Insert       Search hit    Search miss      Iterate        Delete
///NullablePrimitiveSet&lt;int?&gt;  68 936 313  161 565 803    157 338 728  1 169 922 408    18 030 410   ops/sec
///HashSet                          0.34         0.21          0.24          0.82          1.03   x
///</code>
///<para><b>Memory profile (Insert, 100 000 random int keys):</b>
///<list type="bullet">
///<item><c>NullablePrimitiveSet</c> allocates <b>26.23 B/op</b> (Insert, 100 000 random int keys of 100 000 records)</item>
///<item><c>HashSet</c> allocates <b>60.38 B/op</b></item>
///<item><c>NullablePrimitiveSet</c> saves <b>~34 150 B per 1 000 records</b> vs HashSet</item>
///</list>
///</para>
///<para>
///Ratio &gt; 1 ⇒ <c>HashSet</c> faster, &lt; 1 ⇒ NullablePrimitiveSet faster. NullablePrimitiveSet is
///<b>~5× faster on reads</b> and ~3× faster on Insert vs <c>HashSet&lt;int?&gt;</c> (which pays
///nullable-wrapping overhead per lookup). NullablePrimitiveSet now also wins Iterate (~1.2×); Delete is parity.
///</para>
///<para>See <c>Tests/Benchmarks/NullableSetBenchmark.cs</c> for the full scenarios and an HTML report.</para>
///</summary>
///<typeparam name="K">The type of the primitive values in the set. Must be an unmanaged type.</typeparam>
public class NullablePrimitiveSet<K> : ISet<K?>, IReadOnlyCollection<K?>
    where K : unmanaged
{
    private uint[]? _buckets;
    private K[]? _keys;
    private uint[]? _links; //0-based indices into _keys for collision chains.

    //The _keys array is split into two regions to optimize for non-colliding entries:
    //1. Lo-Region (indices 0 to _loSize-1): Stores keys that have caused a hash collision.
    //2. Hi-Region (indices _keys.Length - _hiSize to _keys.Length-1): Stores keys that have not caused a collision.
    private int _hiSize; //Number of active entries in the high region.
    private int _loSize; //Number of active entries in the low region.

    private int _version;
    private uint _mask;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private ref uint GetBucket(uint hashCode) => ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_buckets!), hashCode &_mask);

    private bool _hasNullKey;

    private const int DefaultCapacity = 4;

    public NullablePrimitiveSet() : this(0) {}

    public NullablePrimitiveSet(int capacity)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(capacity);
        if (capacity > 0)
            Initialize(capacity);
    }

    public NullablePrimitiveSet(IEnumerable<K?> collection) : this(collection is ICollection<K?> coll ? coll.Count : 0)
    {
        ArgumentNullException.ThrowIfNull(collection);
        AddRange(collection);
    }

    private void AddRange(IEnumerable<K?> enumerable)
    {
        foreach (var key in enumerable)
            Add(key);
    }

    public int Count
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => _loSize + _hiSize + (_hasNullKey ? 1 : 0);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool Add(K? key)
    {
        if (!key.HasValue)
        {
            if (_hasNullKey)
                return false;
            _hasNullKey = true;
            _version++;
            return true;
        }

        var kv = key.Value;

        if (_buckets == null)
            Initialize(DefaultCapacity);

        var keys = _keys!;
        if (keys.Length <= _loSize + _hiSize)
        {
            Resize(keys.Length * 2);
            keys = _keys!;
        }

        ref var bucket = ref GetBucket((uint)kv.GetHashCode());
        var index = (int)bucket - 1;

        ref var keysRef = ref MemoryMarshal.GetArrayDataReference(keys);
        int dstIndex;

        if (index == -1) //Bucket is empty: place new entry in hi-region
            dstIndex = keys.Length - 1 - _hiSize++;
        else
        {
            ref var linksRef = ref MemoryMarshal.GetArrayDataReference(_links!);
            var loSize = _loSize;
            for (int i = index, collisions = 0;;)
            {
                if (EqualityComparer<K>.Default.Equals(Unsafe.Add(ref keysRef, i), kv))
                    return false;

                if (loSize <= i)
                    break;
                i = (int)Unsafe.Add(ref linksRef, i);

                if (loSize + 1 < collisions++)
                    throw new InvalidOperationException("Concurrent operations not supported.");
            }

            if (_links!.Length == (dstIndex = _loSize++))
                Array.Resize(ref _links, Math.Max(16, Math.Min(_buckets!.Length, _links.Length * 2)));

            //Re-fetch links ref (Array.Resize may have allocated a new array).
            Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_links!), dstIndex) = (uint)index;
        }

        Unsafe.Add(ref keysRef, dstIndex) = kv;
        bucket = (uint)(dstIndex + 1);
        _version++;
        return true;
    }

    void ICollection<K?>.Add(K? key) => Add(key);

    public void Clear()
    {
        if (Count == 0)
            return;

        _hasNullKey = false;
        _version++;

        if (_buckets != null)
            Array.Clear(_buckets, 0, _buckets.Length);
        _loSize = 0;
        _hiSize = 0;
    }

    public bool Contains(K? key)
    {
        if (!key.HasValue)
            return _hasNullKey;
        var kv = key.Value;

        if (_loSize + _hiSize == 0)
            return false;

        var i = (int)GetBucket((uint)kv.GetHashCode()) - 1;
        if (i == -1)
            return false;

        ref var keysRef = ref MemoryMarshal.GetArrayDataReference(_keys!);
        ref var linksRef = ref MemoryMarshal.GetArrayDataReference(_links!);
        var loSize = _loSize;

        for (var collisions = 0;;)
        {
            if (EqualityComparer<K>.Default.Equals(Unsafe.Add(ref keysRef, i), kv))
                return true;

            if (loSize <= i)
                return false; //terminal entity
            i = (int)Unsafe.Add(ref linksRef, i);

            if (loSize < ++collisions)
                throw new InvalidOperationException("Hash collision chain is unexpectedly long. Possible data corruption.");
        }
    }

    public void CopyTo(K?[] dst, int dstIndex)
    {
        ArgumentNullException.ThrowIfNull(dst);
        ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual((uint)dstIndex, (uint)dst.Length);
        if (dst.Length - dstIndex < Count)
            throw new ArgumentException("Destination array is not long enough.");

        if (_hasNullKey)
            dst[dstIndex++] = null;

        if (_keys == null)
            return;

        ref var keysRef = ref MemoryMarshal.GetArrayDataReference(_keys);
        ref var dstRef = ref MemoryMarshal.GetArrayDataReference(dst);

        //Copy lo-region
        var loSize = _loSize;
        for (var i = 0; i < loSize; i++)
            Unsafe.Add(ref dstRef, dstIndex++) = Unsafe.Add(ref keysRef, i);

        var hiSize = _hiSize;
        if (hiSize == 0)
            return;

        //Copy hi-region
        var len = _keys.Length;
        for (var i = len - hiSize; i < len; i++)
            Unsafe.Add(ref dstRef, dstIndex++) = Unsafe.Add(ref keysRef, i);
    }

    private int Initialize(int capacity, int linksHint = 16)
    {
        _version++;

        var size = GetPowerOfTwo(capacity);
        _buckets = new uint[size];
        _keys = new K[size];
        _links = new uint[Math.Min(size, linksHint)];
        _loSize = _hiSize = 0;
        _mask = (uint)(size - 1);

        return size;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static int GetPowerOfTwo(int capacity) => capacity <= DefaultCapacity ? DefaultCapacity : (int)BitOperations.RoundUpToPowerOf2((uint)capacity);

    private int Resize(int newSize)
    {
        _version++;
        var oldKeys = _keys;
        var oldLoSize = _loSize;
        var oldHiSize = _hiSize;
        var oldEnd = oldKeys!.Length;
        var oldHiStart = oldEnd - oldHiSize;

        var totalEntries = oldLoSize + oldHiSize;
        Initialize(newSize, totalEntries);

        ref var oldKeys0 = ref MemoryMarshal.GetArrayDataReference(oldKeys);
        ref var keys0 = ref MemoryMarshal.GetArrayDataReference(_keys!);
        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        ref var buckets0 = ref MemoryMarshal.GetArrayDataReference(_buckets!);
        var mask = _mask;
        var newEnd = _keys!.Length;
        var loSize = 0;
        var hiSize = 0;

        for (var i = 0; i < oldLoSize; i++)
        {
            var key = Unsafe.Add(ref oldKeys0, i);
            ref var bucket = ref Unsafe.Add(ref buckets0, (nint)((uint)key.GetHashCode() & mask));
            var prev = (int)bucket - 1;
            int dstIndex;

            if (prev == -1)
                dstIndex = newEnd - 1 - hiSize++;
            else
            {
                dstIndex = loSize++;
                Unsafe.Add(ref links0, dstIndex) = (uint)prev;
            }

            Unsafe.Add(ref keys0, dstIndex) = key;
            bucket = (uint)(dstIndex + 1);
        }

        for (var i = oldHiStart; i < oldEnd; i++)
        {
            var key = Unsafe.Add(ref oldKeys0, i);
            ref var bucket = ref Unsafe.Add(ref buckets0, (nint)((uint)key.GetHashCode() & mask));
            var prev = (int)bucket - 1;
            int dstIndex;

            if (prev == -1)
                dstIndex = newEnd - 1 - hiSize++;
            else
            {
                dstIndex = loSize++;
                Unsafe.Add(ref links0, dstIndex) = (uint)prev;
            }

            Unsafe.Add(ref keys0, dstIndex) = key;
            bucket = (uint)(dstIndex + 1);
        }

        _loSize = loSize;
        _hiSize = hiSize;
        return newSize;
    }
    //Moves data from src index to dst index and updates all links pointing to src.
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void Move(int src, int dst, ref K dstKey)
    {
        //Move is private and called only from Remove (three sites). Centralizing the
        //version bump here removes the duplicated `_version++` from each Remove branch
        //and still bumps once per Remove (including the src == dst early-return case).
        _version++;
        if (src == dst)
            return;

        //Skip the array-bounds checks: src < _keys.Length and the chain-walked
        //indices are bounded by the same. Same trick the BCL uses internally.
        ref var keys0 = ref MemoryMarshal.GetArrayDataReference(_keys!);
        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        ref var srcKey = ref Unsafe.Add(ref keys0, src);
        ref var srcBucket = ref GetBucket((uint)srcKey.GetHashCode());
        var index = (int)srcBucket - 1;

        if (index == src)
            srcBucket = (uint)(dst + 1);
        else
        {
            ref var link = ref Unsafe.Add(ref links0, index);
            while (link != src)
            {
                index = (int)link;
                link = ref Unsafe.Add(ref links0, index);
            }
            link = (uint)dst;
        }

        if (src < _loSize)
            Unsafe.Add(ref links0, dst) = Unsafe.Add(ref links0, src);

        dstKey = srcKey;
    }

    public bool Remove(K? key)
    {
        if (!key.HasValue)
        {
            if (!_hasNullKey)
                return false;
            _hasNullKey = false;
            _version++;
            return true;
        }

        var kv = key.Value;
        if (_loSize + _hiSize == 0)
            return false;

        ref var bucket = ref GetBucket((uint)kv.GetHashCode());
        var idx = (int)bucket - 1;
        if (idx < 0)
            return false;

        var loSize = _loSize;
        ref var keys0 = ref MemoryMarshal.GetArrayDataReference(_keys!);

        ref var k = ref Unsafe.Add(ref keys0, idx);
        if (loSize <= idx)
        {
            if (!EqualityComparer<K>.Default.Equals(k, kv))
                return false;
            Move(_keys!.Length - _hiSize, idx, ref k);
            _hiSize--;
            bucket = 0;
            return true;
        }

        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        var prev = -1;
        var prevPrev = -1;

        for (var collisions = 0;
             !EqualityComparer<K>.Default.Equals(k, kv);
             prevPrev = prev,
                 k = ref Unsafe.Add(ref keys0, idx = (int)Unsafe.Add(ref links0, prev = idx)))
        {
            if (idx >= loSize)
                return false;
            if (++collisions > loSize)
                throw new InvalidOperationException("Hash collision chain is unexpectedly long. Possible data corruption.");
        }

        var lastLo = loSize - 1;
        if (idx < loSize)
        {
            //Standard removal: rewire (prev or bucket) → next; compact lo by swap-with-last.
            //Single read of the matched entry's link; both branches consume `next`.
            var next = Unsafe.Add(ref links0, idx);
            if (prev < 0)
                bucket = next + 1;
            else
                Unsafe.Add(ref links0, prev) = next;
            Move(lastLo, idx, ref k);
        }
        else
        {
            //Found at hi-terminator with chain length ≥ 2. Migrate prev (lo) into the hi slot
            //so the chain still terminates in hi; prev's lo slot becomes the hole.
            ref var prevKey = ref Unsafe.Add(ref keys0, prev);
            k = prevKey;
            if (prevPrev < 0)
                bucket = (uint)(idx + 1);
            else
                Unsafe.Add(ref links0, prevPrev) = (uint)idx;
            Move(lastLo, prev, ref prevKey);
        }

        _loSize = lastLo;
        return true;
    }

    public Enumerator GetEnumerator() => new(this);
    IEnumerator<K?> IEnumerable<K?>.GetEnumerator() => GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

    public struct Enumerator : IEnumerator<K?>
    {
        //Snapshot the layout at construction so MoveNext only reads instance fields when
        //version-checking. Field reads on the heap object cost a load + a possible cache
        //miss per call; locals stay in registers across the iteration. Same approach as
        //<see cref="NullablePrimitiveKeyMap{K,V}.Enumerator"/> — the previous implementation
        //read `_set._loSize`, `_set._hiSize`, `_set._keys.Length`, `_set.Count`, and
        //`_set._hasNullKey` on EVERY MoveNext, plus emitted JIT bounds checks on
        //`_set._keys[i]`. That's why Iterate trailed BCL HashSet on this collection.
        private readonly NullablePrimitiveSet<K> _set;
        private readonly K[]? _keys;
        private readonly int _loEnd;   //_loSize at construction
        private readonly int _hiStart; //_keys.Length - _hiSize at construction
        private readonly int _hiEnd;   //_keys.Length at construction
        private readonly int _version;

        //Sentinel values for _index:
        //  -2 = null-key pending (will yield it on next MoveNext)
        //  -1 = null-key already yielded (or never had one); regular walk has not started
        //  -3 = finished (terminal — MoveNext keeps returning false)
        //  [0, _loEnd) ∪ [_hiStart, _hiEnd) = current key index in _keys
        private int _index;
        private K? _current;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal Enumerator(NullablePrimitiveSet<K> set)
        {
            _set = set;
            _version = set._version;
            _keys = set._keys;
            _loEnd = set._loSize;
            _hiEnd = _keys?.Length ?? 0;
            _hiStart = _hiEnd - set._hiSize;
            _index = set._hasNullKey ? -2 : -1;
            _current = default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool MoveNext()
        {
            if (_version != _set._version)
                throw new InvalidOperationException("Collection was modified during enumeration.");

            //First call when a null key is present: yield null and switch into the
            //regular-walk state. Branch is taken at most once per enumeration.
            if (_index == -2)
            {
                _current = null;
                _index = -1;
                return true;
            }

            if (_index == -3)
                return false; //already finished

            //Single linear walk: 0 .. _loEnd, then _hiStart .. _hiEnd. The lo→hi bridge
            //fires at most once; the i >= _hiEnd test folds end-of-iteration detection.
            var i = _index + 1;
            if (i == _loEnd)
                i = _hiStart;
            if (i >= _hiEnd)
            {
                _index = -3;
                return false;
            }

            //Skip the array-bounds check: we just verified i < _hiEnd ≤ _keys.Length.
            var key = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_keys!), i);
            _current = key;
            _index = i;
            return true;
        }

        //BCL HashSet semantics: bare field read. Concurrent-modification detection
        //lives in MoveNext; a stale Current after invalidation is acceptable.
        public K? Current
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _current;
        }

        object? IEnumerator.Current => Current;

        public void Reset()
        {
            if (_version != _set._version)
                throw new InvalidOperationException("Collection was modified during enumeration.");
            _index = _set._hasNullKey ? -2 : -1;
            _current = default;
        }

        public void Dispose() {}
    }
#region ISet Explicit / Remaining Implementation
    public bool IsReadOnly => false;

    public void ExceptWith(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        if (Count == 0)
            return;
        if (other is NullablePrimitiveSet<K> otherSet && otherSet.Count == 0)
            return;

        foreach (var key in other)
            Remove(key);
    }

    public void IntersectWith(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);

        var t = new NullablePrimitiveSet<K>();
        foreach (var key in other)
            if (Contains(key))
                t.Add(key);

        _buckets = t._buckets;
        _keys = t._keys;
        _links = t._links;
        _hiSize = t._hiSize;
        _loSize = t._loSize;
        _version++;
        _mask = t._mask;
        _hasNullKey = t._hasNullKey;
    }

    public void SymmetricExceptWith(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        if (other == this)
        {
            Clear();
            return;
        }

        foreach (var key in other)
            if (!Remove(key))
                Add(key);
    }

    public void UnionWith(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        foreach (var key in other)
            Add(key);
    }

    public bool IsProperSubsetOf(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        var otherCollection = other as ICollection<K?> ?? new HashSet<K?>(other);
        return Count < otherCollection.Count && IsSubsetOf(otherCollection);
    }

    public bool IsProperSupersetOf(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        var otherCollection = other as ICollection<K?> ?? new HashSet<K?>(other);
        return Count > otherCollection.Count && IsSupersetOf(otherCollection);
    }

    public bool IsSubsetOf(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        if (Count == 0)
            return true;
        var otherAsSet = other as ISet<K?> ?? new HashSet<K?>(other);
        if (Count > otherAsSet.Count)
            return false;

        foreach (var key in this)
            if (!otherAsSet.Contains(key))
                return false;
        return true;
    }

    public bool IsSupersetOf(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        if (other is ICollection<K?> { Count : 0 })
            return true;

        foreach (var key in other)
            if (!Contains(key))
                return false;
        return true;
    }

    public bool Overlaps(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        if (Count == 0)
            return false;

        foreach (var key in other)
            if (Contains(key))
                return true;
        return false;
    }

    public bool SetEquals(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        var otherAsSet = other as ISet<K?> ?? new HashSet<K?>(other);
        return Count == otherAsSet.Count && IsSupersetOf(otherAsSet);
    }
#endregion

    public int EnsureCapacity(int capacity)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(capacity);
        var currentCapacity = _keys?.Length ?? 0;
        if (currentCapacity >= capacity)
            return currentCapacity;
        _version++;
        if (_buckets == null)
            return Initialize(capacity);
        var newSize = GetPowerOfTwo(capacity);
        Resize(newSize);
        return newSize;
    }

    public void TrimExcess()
    {
        var count = Count;
        if (count == 0)
        {
            Initialize(0);
            return;
        }

        if (_keys != null)
        {
            var newSize = GetPowerOfTwo(count);
            if (newSize < _keys.Length)
            {
                Resize(newSize);
            }
        }
    }
}