//Copyright 2025 Chikirev Sirguy, Unirail Group. All rights reserved.
//
//This file is part of the AdHoc protocol runtime library.
//
//Licensed under the PolyForm Shield License 1.0.0. The full text is distributed with this
//file as LICENSE.md and is published at https://polyformproject.org/licenses/shield/1.0.0
//
//In short: you may use, modify and distribute this software for any purpose, except to
//provide a product that competes with the software, or with any product the licensor
//provides using the software. Competition is judged by function, not by form.
//
//The plain-text notice lines the license requires you to pass on - the Required Notice and
//the Licensor Line of Business - are in the NOTICE file distributed with this library.
//Keep LICENSE.md and NOTICE with any copy of this software that you distribute.
//
//Code generated by the AdHoc generator is NOT part of the Licensed Work and carries no
//restrictions whatsoever - see the header of any generated file.
//
//Provided as is, without any warranty or condition.
//
//Commercial licenses that remove the noncompete restriction are available.
//For licensing and inquiries: al8v5C6HU4UtqE9@gmail.com

using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace org.unirail.collections;

///<summary>
///A highly optimized dictionary for nullable 2-byte unmanaged keys (e.g., ushort, char).
///It uses a bitset and a value array ("flat") strategy for dense data and a custom hash table for sparse data.
///This class is not thread-safe.
///
///<para><b>Benchmark vs <c>Dictionary&lt;ushort?,int&gt;</c></b> (N = 50 000 unique ushort keys → flat mode,
///.NET 9, Release):</para>
///<code>
///Insert         Search           Get        Iterate         Delete
///NullableTwoBytesKeyMap&lt;ushort?,int&gt;   57 835 944  1 180 836 707   821 018 062  385 547 477    41 539 082   ops/sec
///Dictionary                                  0.38           0.03          0.05         2.17          0.53   x
///</code>
///<para><b>Memory profile (Insert, 50 000 unique random ushort keys (transitions to flat strategy)):</b>
///<list type="bullet">
///<item><c>NullableTwoBytesKeyMap</c> allocates <b>19.85 B/op</b> (Insert, 50 000 unique random ushort keys (transitions to flat strategy) of 50 000 records)</item>
///<item><c>Dictionary</c> allocates <b>58.18 B/op</b></item>
///<item><c>NullableTwoBytesKeyMap</c> saves <b>~38 330 B per 1 000 records</b> vs Dictionary</item>
///</list>
///</para>
///<para>
///Ratio &gt; 1 ⇒ <c>Dictionary</c> faster, &lt; 1 ⇒ NullableTwoBytesKeyMap faster. In flat mode this
///class is <b>33× faster on Search</b>, 22× on TryGetValue, 2.6× on Insert, 1.9× on Delete.
///Dictionary wins Iterate (2.17×) due to its contiguous entry layout vs flat-bitset scan.
///</para>
///<para>See <c>Tests/Benchmarks/NullableTwoBytesBenchmark.cs</c> for the full scenarios and an HTML report.</para>
///</summary>
public class NullableTwoBytesKeyMap<K, V> : IDictionary<K?, V>, IReadOnlyDictionary<K?, V>
    where K : unmanaged
{
    private struct Entry
    {
        public K key;
        public V value;
    }

    private V[]? _flatValues; //Value storage for flat mode.

    private ushort[]? _buckets;
    private Entry[]? _entries;
    private ushort[]? _links; //0-based indices into _entries for collision chains.

    //The _entries array is split into two regions to optimize for non-colliding entries:
    //1. Lo-Region (indices 0 to _loSize-1): Stores entries that have caused a hash collision.
    //2. Hi-Region (indices _entries.Length - _hiSize to _entries.Length-1): Stores entries that have not caused a collision.
    private int _hiSize; //Number of active entries in the high region.
    private int _loSize; //Number of active entries in the low region.

    private int _flatCount;
    private int _version;
    private uint _mask;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private ref ushort GetBucket(uint hashCode) => ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_buckets!), hashCode &_mask);

    private bool _hasNullKey;
    private V _nullKeyValue = default!;

    private const int DefaultCapacity = 4;
    protected const int VALUES_SIZE = 0x10000;         //65536
    protected const int NULLS_SIZE = VALUES_SIZE / 64; //1024
    public const int flatStrategyThreshold = 0x7FFF;   //Max capacity for hash phase

    private ulong[]? _nulls; //Bitset for flat mode presence.
    public bool IsFlatStrategy => _nulls != null;

    private KeyCollection? _keys;
    private ValueCollection? _values;

    public NullableTwoBytesKeyMap() : this(0) {}

    public NullableTwoBytesKeyMap(int capacity)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(capacity);
        if (Unsafe.SizeOf<K>() != 2)
            throw new InvalidOperationException($"The Key type {typeof(K).Name} is {Unsafe.SizeOf<K>()} bytes, but must be 2 bytes.");

        if (capacity > 0)
            Initialize(capacity);
    }

    public NullableTwoBytesKeyMap(IDictionary<K?, V> dictionary) : this(dictionary?.Count ?? 0)
    {
        ArgumentNullException.ThrowIfNull(dictionary);
        if (Unsafe.SizeOf<K>() != 2)
            throw new InvalidOperationException($"The Key type {typeof(K).Name} is {Unsafe.SizeOf<K>()} bytes, but must be 2 bytes.");
        AddRange(dictionary);
    }

    public NullableTwoBytesKeyMap(IEnumerable<KeyValuePair<K?, V>> collection) : this((collection as ICollection<KeyValuePair<K?, V>>)?.Count ?? 0)
    {
        ArgumentNullException.ThrowIfNull(collection);
        if (Unsafe.SizeOf<K>() != 2)
            throw new InvalidOperationException($"The Key type {typeof(K).Name} is {Unsafe.SizeOf<K>()} bytes, but must be 2 bytes.");
        AddRange(collection);
    }

    private void AddRange(IEnumerable<KeyValuePair<K?, V>> enumerable)
    {
        foreach (var pair in enumerable)
            Add(pair.Key, pair.Value);
    }

    public int Count => (IsFlatStrategy ? _flatCount : _loSize + _hiSize) + (_hasNullKey ? 1 : 0);

    public V this[K? key]
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            if (!key.HasValue)
            {
                if (_hasNullKey)
                    return _nullKeyValue;
                throw new KeyNotFoundException();
            }
            var kv = key.Value;
            //Flat strategy fast path.
            if (IsFlatStrategy)
            {
                var k = toUshort(kv);
                if ((_nulls![k >> 6] & 1UL << k) != 0)
                    return _flatValues![k];
                throw new KeyNotFoundException();
            }
            ref var entry = ref FindEntry(toUshort(kv));
            if (Unsafe.IsNullRef(ref entry))
                throw new KeyNotFoundException();
            return entry.value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => TryInsert(key, value, true);
    }

    public void Add(K? key, V value)
    {
        if (!TryInsert(key, value, false))
            throw new ArgumentException("An item with the same key has already been added.");
    }

    void ICollection<KeyValuePair<K?, V>>.Add(KeyValuePair<K?, V> item) => TryInsert(item.Key, item.Value, true);

    ///<summary>Native TryAdd — avoids the BCL IDictionary extension's double dispatch.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool TryAdd(K? key, V value) => TryInsert(key, value, false);

    ///<summary>
    ///Internal entry-finder for hash (non-flat) mode with non-null keys. Returns a ref to the entry
    ///on hit, or a null ref on miss. AggressiveInlining; flat mode and null-key short-circuit
    ///happen at each public method's entry, this helper handles only the chain-walk path.
    ///</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private ref Entry FindEntry(ushort kUshort)
    {
        if (_loSize + _hiSize == 0)
            return ref Unsafe.NullRef<Entry>();

        var i = GetBucket(kUshort) - 1;
        if (i == -1)
            return ref Unsafe.NullRef<Entry>();

        ref var entry = ref _entries![i];
        for (var collisions = 0;
             toUshort(entry.key) != kUshort;
             entry = ref _entries![i = _links![i]])
        {
            if (_loSize <= i)
                return ref Unsafe.NullRef<Entry>();
            if (_loSize < ++collisions)
                throw new InvalidOperationException("Hash collision chain is unexpectedly long. Possible data corruption.");
        }
        return ref entry;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private bool TryInsert(K? key, V value, bool overwrite)
    {
        if (!key.HasValue)
        {
            if (_hasNullKey)
            {
                if (!overwrite)
                    return false;
                _nullKeyValue = value;
                return false;
            }

            _hasNullKey = true;
            _nullKeyValue = value;
            _version++;
            return true;
        }

        while (true)
        {
            var kv = key.Value;

            if (IsFlatStrategy)
            {
                var k = toUshort(kv);
                if ((_nulls![k >> 6] & 1UL << k) != 0) //Key exists
                {
                    if (!overwrite)
                        return false;
                    _flatValues![k] = value;
                    return false;
                }

                _nulls[k >> 6] |= 1UL << k;
                _flatValues![k] = value;
                _flatCount++;
                _version++;
                return true;
            }

            if (_buckets == null)
                Initialize(DefaultCapacity);

            var entries = _entries!;
            if (entries.Length <= _loSize + _hiSize)
            {
                var newSize = entries.Length * 2;
                if (newSize > flatStrategyThreshold && entries.Length < flatStrategyThreshold)
                    newSize = flatStrategyThreshold;
                Resize(newSize);
                if (IsFlatStrategy)
                    continue; //Retry with the new flat strategy
                entries = _entries!;
            }

            var kUshort = toUshort(kv);
            ref var bucket = ref _buckets![(uint)kUshort & _mask];

            int dstIndex;
            if (bucket == 0) //Bucket is empty: Place new entry in the Hi-Region (non-colliding entries).
                dstIndex = entries.Length - 1 - _hiSize++;
            else //Collision detected (bucket is not empty).
            {
                //Traverse a collision chain to check for an existing key or find insertion point.
                for (int i = bucket - 1, collisions = 0;;)
                {
                    ref var entry = ref entries[i];
                    if (toUshort(entry.key) == kUshort)
                    {
                        //Key found: Overwrite if allowed, otherwise return false (add failed).
                        if (!overwrite)
                            return false;
                        entry.value = value;
                        _version++;   //Update version as value changed.
                        return false; //Return false as no *new* entry was added (it was an update).
                    }

                    if (_loSize <= i)
                        break; //the key is not found, jump to the adding the new entry in the collided chain (Lo-Region)

                    i = _links![i];
                    if (_loSize + 1 < collisions++)
                        throw new InvalidOperationException("Concurrent operations not supported.");
                }

                //Key not found in chain: Add new entry to the Lo-Region (colliding entries).
                if (_links!.Length == (dstIndex = _loSize++))
                    Array.Resize(ref _links, Math.Max(16, Math.Min(_buckets!.Length, _links.Length * 2)));
                _links[dstIndex] = (ushort)(bucket - 1); //New entry links to the previous head of the chain.
            }

            ref var newEntry = ref entries[dstIndex];
            newEntry.key = kv;
            newEntry.value = value;

            bucket = (ushort)(dstIndex + 1);
            _version++;  //Update version for successful addition.
            return true; //Item successfully added.
        }
    }

    public void Clear()
    {
        if (Count == 0)
            return;

        _hasNullKey = false;
        _nullKeyValue = default!;
        _version++;

        if (IsFlatStrategy)
        {
            _flatCount = 0;
            Array.Clear(_nulls!);
            if (RuntimeHelpers.IsReferenceOrContainsReferences<V>())
                Array.Clear(_flatValues!);
        }
        else
        {
            if (_buckets != null)
                Array.Clear(_buckets);
            if (RuntimeHelpers.IsReferenceOrContainsReferences<V>() && _loSize + _hiSize > 0)
                Array.Clear(_entries!);
            _loSize = 0;
            _hiSize = 0;
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool ContainsKey(K? key)
    {
        if (!key.HasValue)
            return _hasNullKey;
        var kv = key.Value;
        if (IsFlatStrategy)
        {
            var k = toUshort(kv);
            return (_nulls![k >> 6] & 1UL << k) != 0;
        }
        return !Unsafe.IsNullRef(ref FindEntry(toUshort(kv)));
    }

    public bool ContainsValue(V value)
    {
        if (_hasNullKey && EqualityComparer<V>.Default.Equals(_nullKeyValue, value))
            return true;

        if (IsFlatStrategy)
        {
            var comparer = EqualityComparer<V>.Default;
            for (var i = 0; i < NULLS_SIZE; i++)
            {
                var bits = _nulls![i];
                if (bits == 0)
                    continue; //Skip empty 64-bit segments

                var baseIndex = i << 6; //i * 64
                while (bits != 0)
                {
                    var bitPos = BitOperations.TrailingZeroCount(bits);
                    var index = baseIndex + bitPos;
                    if (comparer.Equals(_flatValues![index], value))
                        return true;
                    bits &= bits - 1; //Clear the least significant set bit
                }
            }

            return false;
        }

        //Iterate lo-region
        for (var i = 0; i < _loSize; i++)
            if (EqualityComparer<V>.Default.Equals(_entries![i].value, value))
                return true;
        if (_hiSize == 0)
            return false;

        //Iterate hi-region
        for (var i = _entries!.Length - _hiSize; i < _entries.Length; i++)
            if (EqualityComparer<V>.Default.Equals(_entries![i].value, value))
                return true;

        return false;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool TryGetValue(K? key, [MaybeNullWhen(false)] out V value)
    {
        if (!key.HasValue)
        {
            if (_hasNullKey)
            {
                value = _nullKeyValue;
                return true;
            }
            value = default;
            return false;
        }
        var kv = key.Value;
        if (IsFlatStrategy)
        {
            var k = toUshort(kv);
            if ((_nulls![k >> 6] & 1UL << k) != 0)
            {
                value = _flatValues![k];
                return true;
            }
            value = default;
            return false;
        }
        ref var entry = ref FindEntry(toUshort(kv));
        if (Unsafe.IsNullRef(ref entry))
        {
            value = default;
            return false;
        }
        value = entry.value;
        return true;
    }

    ///<summary>
    ///Gets a reference to the value associated with the specified key, adding a provided default value if the key does not exist.
    ///</summary>
    ///<param name="key">The key to search for.</param>
    ///<param name="defaultValue">The value to add if the key does not exist.</param>
    ///<param name="exists">When this method returns, contains <c>true</c> if the key already existed; otherwise, <c>false</c>.</param>
    ///<returns>A reference to the value associated with the specified key.</returns>
    ///<remarks>
    ///Note: Do not add or remove items from the map while holding this reference, as triggering a resize of the internal arrays will invalidate it.
    ///</remarks>
    public ref V GetValueRefOrAddDefault(K? key, V defaultValue, out bool exists)
    {
        //1. Handle the null key specifically
        if (!key.HasValue)
        {
            if (_hasNullKey)
            {
                exists = true;
                return ref _nullKeyValue;
            }

            _hasNullKey = true;
            _nullKeyValue = defaultValue;
            _version++;
            exists = false;
            return ref _nullKeyValue;
        }

        //2. Loop to handle transition between Hash and Flat strategies
        while (true)
        {
            var kv = key.Value;

            //Flat Strategy Logic
            if (IsFlatStrategy)
            {
                var k = toUshort(kv);
                if ((_nulls![k >> 6] & 1UL << k) != 0) //Key exists
                {
                    exists = true;
                    return ref _flatValues![k];
                }

                //Key does not exist: Add it
                _nulls[k >> 6] |= 1UL << k;
                _flatValues![k] = defaultValue;
                _flatCount++;
                _version++;
                exists = false;
                return ref _flatValues[k];
            }

            //Hash Strategy Logic
            if (_buckets == null)
                Initialize(DefaultCapacity);

            var entries = _entries!;
            if (entries.Length <= _loSize + _hiSize)
            {
                var newSize = entries.Length * 2;
                if (newSize > flatStrategyThreshold && entries.Length < flatStrategyThreshold)
                    newSize = flatStrategyThreshold;

                Resize(newSize);

                if (IsFlatStrategy)
                    continue; //Retry with the newly activated flat strategy
                entries = _entries!;
            }

            var kUshort = toUshort(kv);
            ref var bucket = ref _buckets![(uint)kUshort & _mask];

            int dstIndex;
            if (bucket == 0) //Bucket is empty: Place new entry in the Hi-Region (non-colliding entries).
                dstIndex = entries.Length - 1 - _hiSize++;
            else //Collision detected (bucket is not empty).
            {
                //Traverse the collision chain to check for an existing key or find insertion point.
                for (int i = bucket - 1, collisions = 0;;)
                {
                    ref var entry = ref entries[i];
                    if (toUshort(entry.key) == kUshort)
                    {
                        //Key found: Return a reference to the existing value.
                        exists = true;
                        return ref entry.value;
                    }

                    if (_loSize <= i)
                        break; //The key is not found, jump to adding the new entry in the collided chain (Lo-Region)

                    i = _links![i];
                    if (_loSize + 1 < collisions++)
                        throw new InvalidOperationException("Concurrent operations not supported.");
                }

                //Key not found in chain: Add new entry to the Lo-Region (colliding entries).
                if (_links!.Length == (dstIndex = _loSize++))
                    Array.Resize(ref _links, Math.Max(16, Math.Min(_buckets!.Length, _links.Length * 2)));
                _links[dstIndex] = (ushort)(bucket - 1); //New entry links to the previous head of the chain.
            }

            //Initialize the new entry with the provided default value
            ref var newEntry = ref entries[dstIndex];
            newEntry.key = kv;
            newEntry.value = defaultValue;

            bucket = (ushort)(dstIndex + 1);
            _version++;
            exists = false;

            //Return a reference to the newly added value
            return ref newEntry.value;
        }
    }

    public void CopyTo(KeyValuePair<K?, V>[] dst, int dstIndex)
    {
        ArgumentNullException.ThrowIfNull(dst);
        ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual((uint)dstIndex, (uint)dst.Length);
        if (dst.Length - dstIndex < Count)
            throw new ArgumentException("Destination array is not long enough.");

        if (_hasNullKey)
            dst[dstIndex++] = new KeyValuePair < K ?, V > (null, _nullKeyValue);

        if (IsFlatStrategy)
            for (var i = -1; (i = next1(i)) != -1;)
                dst[dstIndex++] = new KeyValuePair < K ?, V > (Unsafe.As<int, K>(ref i), _flatValues![i]);
        else
        {
            for (var i = 0; i < _loSize; i++)
            {
                ref var entry = ref _entries![i];
                dst[dstIndex++] = new KeyValuePair < K ?, V > (entry.key, entry.value);
            }

            for (int i = 0, j = _entries!.Length - _hiSize; i < _hiSize; i++, j++)
            {
                ref var entry = ref _entries![j];
                dst[dstIndex++] = new KeyValuePair < K ?, V > (entry.key, entry.value);
            }
        }
    }

    private int Initialize(int capacity, int linksHint = 16)
    {
        _version++;
        _flatCount = 0;

        if (flatStrategyThreshold < capacity)
        {
            _nulls = new ulong[NULLS_SIZE];
            _flatValues = new V[VALUES_SIZE];
            _buckets = null;
            _entries = null;
            _links = null;
            _loSize = _hiSize = 0;
            return VALUES_SIZE;
        }

        _nulls = null;
        _flatValues = null;

        var size = GetPowerOfTwo(capacity);
        _buckets = new ushort[size];
        _entries = new Entry[size];
        _links = new ushort[Math.Min(size, linksHint)];
        _loSize = _hiSize = 0;
        _mask = (uint)(size - 1);

        return size;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static int GetPowerOfTwo(int capacity) => capacity <= DefaultCapacity ? DefaultCapacity : (int)BitOperations.RoundUpToPowerOf2((uint)capacity);

    private int Resize(int newSize)
    {
        _version++;

        if (IsFlatStrategy)
        {
            if (flatStrategyThreshold < newSize)
                return newSize;
            var oldNulls = _nulls!;
            var oldFlatValues = _flatValues!;

            Initialize(newSize);
            for (var token = -1; (token = next1(token, oldNulls)) != -1;)
            {
                var k = Unsafe.As<int, K>(ref token);
                ref var bucket = ref GetBucket(toUshort(k));
                var i = bucket - 1;
                int dstIndex;

                if (i == -1)
                    dstIndex = _entries!.Length - 1 - _hiSize++;
                else
                {
                    if (_links!.Length == (dstIndex = _loSize++))
                        Array.Resize(ref _links, Math.Max(16, Math.Min(_buckets!.Length, _links.Length * 2)));
                    _links[dstIndex] = (ushort)i;
                }

                ref var entry = ref _entries![dstIndex];
                entry.key = k;
                entry.value = oldFlatValues[token];
                bucket = (ushort)(dstIndex + 1);
            }

            return newSize;
        }

        if (flatStrategyThreshold < newSize)
        {
            _nulls = new ulong[NULLS_SIZE];
            _flatValues = new V[VALUES_SIZE];

            for (var i = 0; i < _loSize; i++)
            {
                ref var entry = ref _entries![i];
                var index = toUshort(entry.key);
                _nulls[index >> 6] |= 1UL << index;
                _flatValues[index] = entry.value;
            }

            if (0 < _hiSize)
                for (var i = _entries!.Length - _hiSize; i < _entries.Length; i++)
                {
                    ref var entry = ref _entries![i];
                    var index = toUshort(entry.key);
                    _nulls[index >> 6] |= 1UL << index;
                    _flatValues[index] = entry.value;
                }

            _flatCount = _loSize + _hiSize;
            _buckets = null;
            _entries = null;
            _links = null;
            _loSize = 0;
            _hiSize = 0;
            return newSize;
        }

        //Hash-to-hash resize
        var oldEntries = _entries;
        var oldLoSize = _loSize;
        var oldHiSize = _hiSize;
        var oldEnd = oldEntries!.Length;
        var oldHiStart = oldEnd - oldHiSize;

        var totalEntries = oldLoSize + oldHiSize;
        Initialize(newSize, totalEntries);

        ref var oldEntries0 = ref MemoryMarshal.GetArrayDataReference(oldEntries);
        ref var entries0 = ref MemoryMarshal.GetArrayDataReference(_entries!);
        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        ref var buckets0 = ref MemoryMarshal.GetArrayDataReference(_buckets!);
        var mask = _mask;
        var newEnd = _entries!.Length;
        var loSize = 0;
        var hiSize = 0;

        for (var i = 0; i < oldLoSize; i++)
        {
            ref var entry = ref Unsafe.Add(ref oldEntries0, i);
            ref var bucket = ref Unsafe.Add(ref buckets0, (nint)((uint)toUshort(entry.key) & mask));
            var prev = (int)bucket - 1;
            int dstIndex;

            if (prev == -1)
                dstIndex = newEnd - 1 - hiSize++;
            else
            {
                dstIndex = loSize++;
                Unsafe.Add(ref links0, dstIndex) = (ushort)prev;
            }

            Unsafe.Add(ref entries0, dstIndex) = entry;
            bucket = (ushort)(dstIndex + 1);
        }

        for (var i = oldHiStart; i < oldEnd; i++)
        {
            ref var entry = ref Unsafe.Add(ref oldEntries0, i);
            ref var bucket = ref Unsafe.Add(ref buckets0, (nint)((uint)toUshort(entry.key) & mask));
            var prev = (int)bucket - 1;
            int dstIndex;

            if (prev == -1)
                dstIndex = newEnd - 1 - hiSize++;
            else
            {
                dstIndex = loSize++;
                Unsafe.Add(ref links0, dstIndex) = (ushort)prev;
            }

            Unsafe.Add(ref entries0, dstIndex) = entry;
            bucket = (ushort)(dstIndex + 1);
        }

        _loSize = loSize;
        _hiSize = hiSize;
        return newSize;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void Move(int src, int dst, ref Entry dstEntry)
    {
        //Move is private and called only from Remove (three sites). Centralizing the
        //version bump here removes the duplicated `_version++` from each Remove branch
        //and still bumps once per Remove (including the src == dst early-return case).
        _version++;
        if (src == dst)
            return;

        //Skip the array-bounds checks: src < _entries.Length and the chain-walked
        //indices are bounded by the same. Same trick the BCL uses internally.
        ref var entries0 = ref MemoryMarshal.GetArrayDataReference(_entries!);
        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        ref var srcEntry = ref Unsafe.Add(ref entries0, src);
        ref var srcBucket = ref GetBucket(toUshort(srcEntry.key));
        var index = srcBucket - 1;

        if (index == src)
            srcBucket = (ushort)(dst + 1);
        else
        {
            ref var link = ref Unsafe.Add(ref links0, index);
            while (link != src)
            {
                index = link;
                link = ref Unsafe.Add(ref links0, index);
            }
            link = (ushort)dst;
        }

        if (src < _loSize)
            Unsafe.Add(ref links0, dst) = Unsafe.Add(ref links0, src);

        dstEntry = srcEntry;
    }

    public bool Remove(K? key)
    {
        if (!key.HasValue)
        {
            if (!_hasNullKey)
                return false;
            _hasNullKey = false;
            _nullKeyValue = default!;
            _version++;
            return true;
        }

        var kv = key.Value;

        if (IsFlatStrategy)
        {
            var k = toUshort(kv);
            ref var bitword = ref _nulls![k >> 6];
            var t = bitword;
            if (t == (bitword &= ~(1UL << k)))
                return false;

            if (RuntimeHelpers.IsReferenceOrContainsReferences<V>())
                _flatValues![k] = default!;
            _flatCount--;
            _version++;
            return true;
        }

        if (_loSize + _hiSize == 0)
            return false;

        var kUshort = toUshort(kv);
        ref var bucket = ref GetBucket(kUshort);
        var idx = bucket - 1;
        if (idx < 0)
            return false;

        var loSize = _loSize;
        ref var entries0 = ref MemoryMarshal.GetArrayDataReference(_entries!);

        ref var e = ref Unsafe.Add(ref entries0, idx);
        if (loSize <= idx)
        {
            if (toUshort(e.key) != kUshort)
                return false;
            Move(_entries!.Length - _hiSize, idx, ref e);
            _hiSize--;
            bucket = 0;
            return true;
        }

        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        var prev = -1;
        var prevPrev = -1;

        for (var collisions = 0;
             toUshort(e.key) != kUshort;
             prevPrev = prev,
                 e = ref Unsafe.Add(ref entries0, idx = Unsafe.Add(ref links0, prev = idx)))
        {
            if (idx >= loSize)
                return false;
            if (++collisions > loSize)
                throw new InvalidOperationException("Hash collision chain is unexpectedly long. Possible data corruption.");
        }

        var lastLo = loSize - 1;
        if (idx < loSize)
        {
            //Standard removal: rewire (prev or bucket) → next; compact lo by swap-with-last.
            //Single read of the matched entry's link; both branches consume `next`.
            var next = Unsafe.Add(ref links0, idx);
            if (prev < 0)
                bucket = (ushort)(next + 1);
            else
                Unsafe.Add(ref links0, prev) = next;
            Move(lastLo, idx, ref e);
        }
        else
        {
            //Found at hi-terminator with chain length ≥ 2. Migrate prev (lo) into the hi slot
            //so the chain still terminates in hi; prev's lo slot becomes the hole.
            ref var prevEntry = ref Unsafe.Add(ref entries0, prev);
            e = prevEntry;
            if (prevPrev < 0)
                bucket = (ushort)(idx + 1);
            else
                Unsafe.Add(ref links0, prevPrev) = (ushort)idx;
            Move(lastLo, prev, ref prevEntry);
        }

        _loSize = lastLo;
        return true;
    }

    bool ICollection<KeyValuePair<K?, V>>.Remove(KeyValuePair<K?, V> item) => TryGetValue(item.Key, out var value) && EqualityComparer<V>.Default.Equals(value, item.Value) && Remove(item.Key);

    public Enumerator GetEnumerator() => new(this);
    IEnumerator<KeyValuePair<K?, V>> IEnumerable<KeyValuePair<K?, V>>.GetEnumerator() => GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

    ///<summary>
    ///High-throughput iterator over the map.
    ///<para><b>Null-key handling.</b> When <c>_hasNullKey</c> is set, the (null, value) pair is yielded
    ///first via a small state machine: <c>NotStarted → NullEmitted → InRegular → Finished</c>.
    ///The state lives in <c>_index</c> alone (-1 = pending null, -2 = finished/initial-no-null).</para>
    ///<para><b>Flat-mode design (cached bitset word).</b> The previous implementation called
    ///<c>next1(_index)</c> on every <see cref="MoveNext"/>, which re-computed the word index
    ///<c>(bit+1) &gt;&gt; 6</c>, re-loaded <c>_nulls[index]</c> from the heap, and re-built the mask
    ///<c>~0UL &lt;&lt; (i &amp; 63)</c>. None of that survives across <see cref="MoveNext"/> calls.
    ///The new design keeps the current word and "bits not yet consumed" in the enumerator
    ///struct: each call is just <c>TrailingZeroCount</c> on a register, then <c>bits &amp;= bits - 1</c>
    ///to clear the lowest set bit. The heap is touched once per word (every ~64 items, on
    ///average) instead of once per item.</para>
    ///<para><b>Hash-mode design.</b> Lo-region and hi-region snapshotted at construction so the
    ///instance fields are never re-read during the walk. <c>Unsafe.Add</c> +
    ///<c>MemoryMarshal.GetArrayDataReference</c> skips the JIT-emitted array-bounds check on
    ///<c>_entries</c>; the lo/hi boundary fold collapses the "have I finished" branch to a single
    ///<c>i &gt;= _hiEnd</c> compare.</para>
    ///<para><b>Concurrent-modification semantics.</b> Matches BCL Dictionary: the version check
    ///lives in <see cref="MoveNext"/>; <see cref="Current"/> is a bare field read.</para>
    ///</summary>
    public struct Enumerator : IEnumerator<KeyValuePair<K?, V>>
    {
        private readonly NullableTwoBytesKeyMap<K, V> _map;
        private readonly int _version;

        //Null-key snapshot.
        private readonly bool _hasNullKey;
        private readonly V _nullKeyValue;

        //Hash-mode snapshot (null in flat mode).
        private readonly Entry[]? _entries;
        private readonly int _loEnd;
        private readonly int _hiStart;
        private readonly int _hiEnd;

        //Flat-mode snapshot (null in hash mode).
        private readonly ulong[]? _nulls;
        private readonly V[]? _flatValues;

        //Iteration state.
        private int _wordIdx;         //flat mode: current word index in _nulls
        private ulong _remainingBits; //flat mode: bits not yet consumed in the current word
        private int _index;           //-1 = null key pending, -2 = finished/no-null-yet, else current bit/index
        private KeyValuePair<K?, V> _current;

        internal Enumerator(NullableTwoBytesKeyMap<K, V> map)
        {
            _map = map;
            _version = map._version;
            _hasNullKey = map._hasNullKey;
            _nullKeyValue = map._nullKeyValue;
            _current = default;
            //-1 = null-key pending (yielded next), -2 = no null key (start in regular)
            _index = _hasNullKey ? -1 : -2;
            _wordIdx = -1;
            _remainingBits = 0;

            if (map.IsFlatStrategy)
            {
                _entries = null;
                _loEnd = 0;
                _hiStart = 0;
                _hiEnd = 0;
                _nulls = map._nulls;
                _flatValues = map._flatValues;
            }
            else
            {
                _entries = map._entries;
                _loEnd = map._loSize;
                _hiEnd = _entries?.Length ?? 0;
                _hiStart = _hiEnd - map._hiSize;
                _nulls = null;
                _flatValues = null;
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool MoveNext()
        {
            if (_version != _map._version)
                throw new InvalidOperationException("Collection was modified during enumeration.");

            //Yield the null key first (when present).
            if (_index == -1)
            {
                _current = new KeyValuePair < K ?, V > (null, _nullKeyValue);
                _index = -2; //transition: null emitted, regular iteration begins next call
                return true;
            }

            if (_nulls != null)
                return MoveNextFlat();

            //Hash mode: walk lo-region [0..loEnd), then hi-region [hiStart..hiEnd).
            if (_entries == null)
                return false;
            //_index == -2 on first regular call after null (or initial when no null);
            //map -2 to -1 so the +1 below lands at 0.
            var i = (_index == -2 ? -1 : _index) + 1;
            if (i == _loEnd)
                i = _hiStart;
            if (i >= _hiEnd)
                return false;

            ref var entry = ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_entries), i);
            _current = new KeyValuePair < K ?, V > (entry.key, entry.value);
            _index = i;
            return true;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private bool MoveNextFlat()
        {
            var bits = _remainingBits;
            var wordIdx = _wordIdx;

            //Drain remaining set bits in the current word; advance to the next non-zero word
            //only when the current one is exhausted. The heap is touched once per word.
            if (bits == 0)
            {
                ref var nulls0 = ref MemoryMarshal.GetArrayDataReference(_nulls!);
                do
                {
                    if (++wordIdx >= NULLS_SIZE)
                        return false;
                    bits = Unsafe.Add(ref nulls0, wordIdx);
                } while (bits == 0);
            }

            var trailing = BitOperations.TrailingZeroCount(bits);
            var bitPos = (wordIdx << 6) + trailing;
            var key = Unsafe.As<int, K>(ref bitPos);
            var value = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_flatValues!), bitPos);
            _current = new KeyValuePair < K ?, V > (key, value);
            _remainingBits = bits & (bits - 1); //clear lowest set bit
            _wordIdx = wordIdx;
            _index = bitPos;
            return true;
        }

        //BCL Dictionary semantics: bare field read, no per-access checks.
        //Concurrent-modification detection lives in MoveNext.
        public KeyValuePair<K?, V> Current
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _current;
        }

        object? IEnumerator.Current => _current;

        public void Reset()
        {
            if (_version != _map._version)
                throw new InvalidOperationException("Collection was modified during enumeration.");
            _index = _hasNullKey ? -1 : -2;
            _wordIdx = -1;
            _remainingBits = 0;
            _current = default;
        }

        public void Dispose() {}
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static ushort toUshort(K key) => Unsafe.As<K, ushort>(ref key);
#region Flat Strategy Helpers
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    protected int next1(int bit) => next1(bit, _nulls!);

    protected static int next1(int bit, ulong[] nulls)
    {
        if (0xFFFF <= bit)
            return -1;
        var i = ++bit;
        var index = i >> 6;
        if (index >= nulls.Length)
            return -1;
        var value = nulls[index] & ~0UL << (i & 63);

        while (value == 0)
            if (++index == NULLS_SIZE)
                return -1;
            else
                value = nulls[index];

        return (index << 6) + BitOperations.TrailingZeroCount(value);
    }
#endregion
#region Dictionary Properties
    public bool IsReadOnly => false;
    public ICollection<K?> Keys => _keys ??= new KeyCollection(this);
    public ICollection<V> Values => _values ??= new ValueCollection(this);
    IEnumerable<K?> IReadOnlyDictionary<K?, V>.Keys => Keys;
    IEnumerable<V> IReadOnlyDictionary<K?, V>.Values => Values;

    bool ICollection<KeyValuePair<K?, V>>.Contains(KeyValuePair<K?, V> item) => TryGetValue(item.Key, out var value) && EqualityComparer<V>.Default.Equals(value, item.Value);
#endregion

    public int EnsureCapacity(int capacity)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(capacity);
        var currentCapacity = _entries?.Length ?? (IsFlatStrategy ? VALUES_SIZE : 0);
        if (currentCapacity >= capacity)
            return currentCapacity;
        _version++;
        if (_buckets == null && !IsFlatStrategy)
            return Initialize(capacity);
        var newSize = GetPowerOfTwo(capacity);
        Resize(newSize);
        return newSize;
    }

    public void TrimExcess()
    {
        var count = Count;
        if (count == 0)
        {
            Initialize(0);
            return;
        }

        if (IsFlatStrategy)
        {
            if (count <= flatStrategyThreshold)
                Resize(GetPowerOfTwo(count));
        }
        else if (_entries != null)
        {
            var newSize = GetPowerOfTwo(count);
            if (newSize < _entries.Length)
                Resize(newSize);
        }
    }
#region Collection Wrappers
    [DebuggerDisplay("Count = {Count}")]
    public sealed class KeyCollection : ICollection<K?>, IReadOnlyCollection<K?>
    {
        private readonly NullableTwoBytesKeyMap<K, V> map;
        public KeyCollection(NullableTwoBytesKeyMap<K, V> dictionary) => map = dictionary ?? throw new ArgumentNullException(nameof(dictionary));
        public int Count => map.Count;
        public bool IsReadOnly => true;

        public void CopyTo(K?[] dst, int dstIndex)
        {
            ArgumentNullException.ThrowIfNull(dst);
            ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual((uint)dstIndex, (uint)dst.Length);
            if (dst.Length - dstIndex < map.Count)
                throw new ArgumentException("Destination array is not long enough.");
            foreach (var item in map)
                dst[dstIndex++] = item.Key;
        }

        public bool Contains(K? item) => map.ContainsKey(item);
        public Enumerator GetEnumerator() => new(map);
        IEnumerator<K?> IEnumerable<K?>.GetEnumerator() => GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
        void ICollection<K?>.Add(K? item) => throw new NotSupportedException();
        bool ICollection<K?>.Remove(K? item) => throw new NotSupportedException();
        void ICollection<K?>.Clear() => throw new NotSupportedException();

        public struct Enumerator : IEnumerator<K?>
        {
            private NullableTwoBytesKeyMap<K, V>.Enumerator _dictEnumerator;
            internal Enumerator(NullableTwoBytesKeyMap<K, V> dictionary) => _dictEnumerator = dictionary.GetEnumerator();
            public bool MoveNext() => _dictEnumerator.MoveNext();
            public K? Current => _dictEnumerator.Current.Key;
            object? IEnumerator.Current => Current;
            public void Dispose() => _dictEnumerator.Dispose();
            public void Reset() => _dictEnumerator.Reset();
        }
    }

    [DebuggerDisplay("Count = {Count}")]
    public sealed class ValueCollection : ICollection<V>, IReadOnlyCollection<V>
    {
        private readonly NullableTwoBytesKeyMap<K, V> map;
        public ValueCollection(NullableTwoBytesKeyMap<K, V> dictionary) => map = dictionary ?? throw new ArgumentNullException(nameof(dictionary));
        public int Count => map.Count;
        public bool IsReadOnly => true;

        public void CopyTo(V[] dst, int dstIndex)
        {
            ArgumentNullException.ThrowIfNull(dst);
            ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual((uint)dstIndex, (uint)dst.Length);
            if (dst.Length - dstIndex < map.Count)
                throw new ArgumentException("Destination array is not long enough.");
            foreach (var item in map)
                dst[dstIndex++] = item.Value;
        }

        public bool Contains(V item) => map.ContainsValue(item);

        public Enumerator GetEnumerator() => new(map);
        IEnumerator<V> IEnumerable<V>.GetEnumerator() => GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
        void ICollection<V>.Add(V item) => throw new NotSupportedException();
        bool ICollection<V>.Remove(V item) => throw new NotSupportedException();
        void ICollection<V>.Clear() => throw new NotSupportedException();

        public struct Enumerator : IEnumerator<V>
        {
            private NullableTwoBytesKeyMap<K, V>.Enumerator _dictEnumerator;
            internal Enumerator(NullableTwoBytesKeyMap<K, V> dictionary) => _dictEnumerator = dictionary.GetEnumerator();
            public bool MoveNext() => _dictEnumerator.MoveNext();
            public V Current => _dictEnumerator.Current.Value;
            object? IEnumerator.Current => Current;
            public void Dispose() => _dictEnumerator.Dispose();
            public void Reset() => _dictEnumerator.Reset();
        }
    }
#endregion
}