//Copyright 2025 Chikirev Sirguy, Unirail Group. All rights reserved.
//
//This file is part of the AdHoc protocol runtime library.
//
//Licensed under the PolyForm Shield License 1.0.0. The full text is distributed with this
//file as LICENSE.md and is published at https://polyformproject.org/licenses/shield/1.0.0
//
//In short: you may use, modify and distribute this software for any purpose, except to
//provide a product that competes with the software, or with any product the licensor
//provides using the software. Competition is judged by function, not by form.
//
//The plain-text notice lines the license requires you to pass on - the Required Notice and
//the Licensor Line of Business - are in the NOTICE file distributed with this library.
//Keep LICENSE.md and NOTICE with any copy of this software that you distribute.
//
//Code generated by the AdHoc generator is NOT part of the Licensed Work and carries no
//restrictions whatsoever - see the header of any generated file.
//
//Provided as is, without any warranty or condition.
//
//Commercial licenses that remove the noncompete restriction are available.
//For licensing and inquiries: al8v5C6HU4UtqE9@gmail.com

using System;
using System.Collections;
using System.Collections.Generic;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace org.unirail.collections;

///<summary>
///A highly optimized set for nullable 2-byte unmanaged types (e.g., ushort, char).
///It uses a bitset ("flat") strategy for dense data and a custom hash table for sparse data.
///This class is not thread-safe.
///
///<para><b>Benchmark vs <c>HashSet&lt;ushort?&gt;</c></b> (N = 50 000 unique ushort keys → flat mode,
///.NET 9, Release):</para>
///<code>
///Insert         Search hit    Search miss
///NullableTwoBytesSet&lt;ushort?&gt;   113 477 937    1 011 268 420   ~922 023 182   ops/sec
///HashSet                              0.23            0.04           ~0.04   x
///</code>
///<para><b>Memory profile (Insert, 50 000 unique random ushort keys (transitions to flat strategy)):</b>
///<list type="bullet">
///<item><c>NullableTwoBytesSet</c> allocates <b>6.74 B/op</b> (Insert of 50 000 records)</item>
///<item><c>HashSet</c> allocates <b>46.55 B/op</b></item>
///<item><c>NullableTwoBytesSet</c> saves <b>~39 806 B per 1 000 records</b> vs HashSet</item>
///</list>
///</para>
///<para>
///Ratio &gt; 1 ⇒ <c>HashSet</c> faster, &lt; 1 ⇒ NullableTwoBytesSet faster. Flat mode delivers
///<b>~25× faster Contains</b> than <c>HashSet&lt;ushort?&gt;</c> (single bit-test vs hash + nullable
///wrap), 4.3× faster Insert.
///</para>
///<para>See <c>Tests/Benchmarks/NullableTwoBytesBenchmark.cs</c> for the full scenarios and an HTML report.</para>
///</summary>
public class NullableTwoBytesSet<K> : ISet<K?>, IReadOnlySet<K?>
    where K : unmanaged
{
    private ushort[]? _buckets;
    private K[]? _keys;
    private ushort[]? _links; //0-based indices into _keys for collision chains.

    //The _keys array is split into two regions to optimize for non-colliding entries:
    //1. Lo-Region (indices 0 to _loSize-1): Stores keys that have caused a hash collision.
    //2. Hi-Region (indices _keys.Length - _hiSize to _keys.Length-1): Stores keys that have not caused a collision.
    private int _hiSize; //Number of active entries in the high region.
    private int _loSize; //Number of active entries in the low region.

    private int _flatCount;
    private int _version;
    private uint _mask;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private ref ushort GetBucket(uint hashCode) => ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_buckets!), hashCode &_mask);

    private bool _hasNullKey;

    private const int DefaultCapacity = 4;
    protected const int VALUES_SIZE = 0x10000;         //65536
    protected const int NULLS_SIZE = VALUES_SIZE / 64; //1024
    public const int flatStrategyThreshold = 0x7FFF;   //Max capacity for hash phase

    private ulong[]? _nulls; //Bitset for flat mode. A set bit at index `i` means the value `i` is present.
    public bool IsFlatStrategy => _nulls != null;

    public NullableTwoBytesSet() : this(0) {}

    public NullableTwoBytesSet(int capacity)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(capacity);
        if (Unsafe.SizeOf<K>() != 2)
            throw new InvalidOperationException($"The Key type {typeof(K).Name} is {Unsafe.SizeOf<K>()} bytes, but must be 2 bytes.");

        if (capacity > 0)
            Initialize(capacity);
    }

    public NullableTwoBytesSet(IEnumerable<K?> collection) : this(collection is ICollection<K?> coll ? coll.Count : 0)
    {
        ArgumentNullException.ThrowIfNull(collection);
        if (Unsafe.SizeOf<K>() != 2)
            throw new InvalidOperationException($"The Key type {typeof(K).Name} is {Unsafe.SizeOf<K>()} bytes, but must be 2 bytes.");
        AddRange(collection);
    }

    private void AddRange(IEnumerable<K?> enumerable)
    {
        foreach (var key in enumerable)
            Add(key);
    }

    public int Count => (IsFlatStrategy ? _flatCount : _loSize + _hiSize) + (_hasNullKey ? 1 : 0);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool Add(K? key)
    {
        if (!key.HasValue)
        {
            if (_hasNullKey)
                return false;
            _hasNullKey = true;
            _version++;
            return true;
        }

        while (true)
        {
            var kv = key.Value;

            if (IsFlatStrategy)
            {
                var i = toUshort(kv);
                ref var bitword = ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_nulls!), i >> 6);
                var t = bitword;
                if (t == (bitword |= 1UL << i))
                    return false;
                _flatCount++;
                _version++;
                return true;
            }

            if (_buckets == null)
                Initialize(DefaultCapacity);

            var keys = _keys!;
            if (keys.Length <= _loSize + _hiSize)
            {
                var newSize = keys.Length * 2;
                if (newSize > flatStrategyThreshold && keys.Length < flatStrategyThreshold)
                    newSize = flatStrategyThreshold;
                Resize(newSize);
                if (IsFlatStrategy)
                    continue; //Retry with the new flat strategy
                keys = _keys!;
            }

            var kUshort = toUshort(kv);
            ref var bucket = ref GetBucket(kUshort);
            var index = bucket - 1;

            ref var keysRef = ref MemoryMarshal.GetArrayDataReference(keys);
            int dstIndex;

            if (index == -1) //Bucket is empty: place new entry in hi-region
                dstIndex = keys.Length - 1 - _hiSize++;
            else
            {
                ref var linksRef = ref MemoryMarshal.GetArrayDataReference(_links!);
                var loSize = _loSize;
                for (int i = index, collisions = 0;;)
                {
                    if (toUshort(Unsafe.Add(ref keysRef, i)) == kUshort)
                        return false;

                    if (loSize <= i)
                        break;
                    i = Unsafe.Add(ref linksRef, i);

                    if (loSize + 1 < collisions++)
                        throw new InvalidOperationException("Concurrent operations not supported.");
                }

                if (_links!.Length == (dstIndex = _loSize++))
                    Array.Resize(ref _links, Math.Max(16, Math.Min(_buckets!.Length, _links.Length * 2)));

                //Re-fetch links ref (Array.Resize may have allocated a new array).
                Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_links!), dstIndex) = (ushort)index;
            }

            Unsafe.Add(ref keysRef, dstIndex) = kv;
            bucket = (ushort)(dstIndex + 1);
            _version++;
            return true;
        }
    }

    void ICollection<K?>.Add(K? key) => Add(key);

    public void Clear()
    {
        if (Count == 0)
            return;

        _hasNullKey = false;
        _version++;

        if (IsFlatStrategy)
        {
            _flatCount = 0;
            Array.Clear(_nulls!, 0, _nulls!.Length);
        }
        else
        {
            if (_buckets != null)
                Array.Clear(_buckets, 0, _buckets.Length);
            _loSize = 0;
            _hiSize = 0;
        }
    }

    public bool Contains(K? key)
    {
        if (!key.HasValue)
            return _hasNullKey;
        var kv = key.Value;
        if (IsFlatStrategy)
            return exists(kv);

        if (_loSize + _hiSize == 0)
            return false;

        var kUshort = toUshort(kv);
        var i = GetBucket(kUshort) - 1;
        if (i == -1)
            return false;

        ref var keysRef = ref MemoryMarshal.GetArrayDataReference(_keys!);
        ref var linksRef = ref MemoryMarshal.GetArrayDataReference(_links!);
        var loSize = _loSize;

        for (var collisions = 0;;)
        {
            if (toUshort(Unsafe.Add(ref keysRef, i)) == kUshort)
                return true;

            if (loSize <= i)
                return false; //terminal entity
            i = Unsafe.Add(ref linksRef, i);

            if (loSize < ++collisions)
                throw new InvalidOperationException("Hash collision chain is unexpectedly long. Possible data corruption.");
        }
    }

    public void CopyTo(K?[] dst, int dstIndex)
    {
        ArgumentNullException.ThrowIfNull(dst);
        ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual((uint)dstIndex, (uint)dst.Length);
        if (dst.Length - dstIndex < Count)
            throw new ArgumentException("Destination array is not long enough.");

        if (_hasNullKey)
            dst[dstIndex++] = null;

        if (IsFlatStrategy)
            for (var i = -1; (i = next1(i)) != -1;)
                dst[dstIndex++] = Unsafe.As<int, K>(ref i);
        else
        {
            //Copy lo-region
            for (var i = 0; i < _loSize; i++)
                dst[dstIndex++] = _keys[i];
            //Copy hi-region
            for (var i = _keys.Length - _hiSize; i < _keys.Length; i++)
                dst[dstIndex++] = _keys[i];
        }
    }

    private int Initialize(int capacity, int linksHint = 16)
    {
        _version++;
        _flatCount = 0;

        if (flatStrategyThreshold < capacity)
        {
            _nulls = new ulong[NULLS_SIZE];
            _buckets = null;
            _keys = null;
            _links = null;
            _loSize = _hiSize = 0;
            return VALUES_SIZE;
        }

        _nulls = null;

        var size = GetPowerOfTwo(capacity);
        _buckets = new ushort[size];
        _keys = new K[size];
        _links = new ushort[Math.Min(size, linksHint)];
        _loSize = _hiSize = 0;
        _mask = (uint)(size - 1);

        return size;
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static int GetPowerOfTwo(int capacity) => capacity <= DefaultCapacity ? DefaultCapacity : (int)BitOperations.RoundUpToPowerOf2((uint)capacity);

    private int Resize(int newSize)
    {
        _version++;

        if (IsFlatStrategy)
        {
            if (flatStrategyThreshold < newSize)
                return newSize;
            var oldNulls = _nulls!;
            var totalEntries = _flatCount;
            Initialize(newSize, totalEntries);

            ref var keys0 = ref MemoryMarshal.GetArrayDataReference(_keys!);
            ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
            ref var buckets0 = ref MemoryMarshal.GetArrayDataReference(_buckets!);
            var mask = _mask;
            var newEnd = _keys!.Length;
            var loSize = 0;
            var hiSize = 0;

            for (var token = -1; (token = next1(token, oldNulls)) != -1;)
            {
                var key = Unsafe.As<int, K>(ref token);
                ref var bucket = ref Unsafe.Add(ref buckets0, (nint)(toUshort(key) & mask));
                var prev = (int)bucket - 1;
                int dstIndex;

                if (prev == -1)
                    dstIndex = newEnd - 1 - hiSize++;
                else
                {
                    dstIndex = loSize++;
                    Unsafe.Add(ref links0, dstIndex) = (ushort)prev;
                }

                Unsafe.Add(ref keys0, dstIndex) = key;
                bucket = (ushort)(dstIndex + 1);
            }

            _loSize = loSize;
            _hiSize = hiSize;
            return newSize;
        }

        if (flatStrategyThreshold < newSize)
        {
            _nulls = new ulong[NULLS_SIZE];
            //Copy lo-region
            for (var i = 0; i < _loSize; i++)
                exists1(_keys![i], _nulls);
            //Copy hi-region
            for (var i = _keys!.Length - _hiSize; i < _keys.Length; i++)
                exists1(_keys[i], _nulls);

            _flatCount = _loSize + _hiSize;
            _buckets = null;
            _keys = null;
            _links = null;
            _loSize = 0;
            _hiSize = 0;
            return VALUES_SIZE;
        }

        //Hash-to-hash resize
        var oldKeys = _keys;
        var oldLoSize = _loSize;
        var oldHiSize = _hiSize;
        var oldEnd = oldKeys!.Length;
        var oldHiStart = oldEnd - oldHiSize;

        var totalEntries2 = oldLoSize + oldHiSize;
        Initialize(newSize, totalEntries2);

        ref var oldKeys0 = ref MemoryMarshal.GetArrayDataReference(oldKeys);
        ref var keys0_ = ref MemoryMarshal.GetArrayDataReference(_keys!);
        ref var links0_ = ref MemoryMarshal.GetArrayDataReference(_links!);
        ref var buckets0_ = ref MemoryMarshal.GetArrayDataReference(_buckets!);
        var mask_ = _mask;
        var newEnd_ = _keys!.Length;
        var loSize_ = 0;
        var hiSize_ = 0;

        for (var i = 0; i < oldLoSize; i++)
        {
            var key = Unsafe.Add(ref oldKeys0, i);
            ref var bucket = ref Unsafe.Add(ref buckets0_, (nint)(toUshort(key) & mask_));
            var prev = (int)bucket - 1;
            int dstIndex;

            if (prev == -1)
                dstIndex = newEnd_ - 1 - hiSize_++;
            else
            {
                dstIndex = loSize_++;
                Unsafe.Add(ref links0_, dstIndex) = (ushort)prev;
            }

            Unsafe.Add(ref keys0_, dstIndex) = key;
            bucket = (ushort)(dstIndex + 1);
        }

        for (var i = oldHiStart; i < oldEnd; i++)
        {
            var key = Unsafe.Add(ref oldKeys0, i);
            ref var bucket = ref Unsafe.Add(ref buckets0_, (nint)(toUshort(key) & mask_));
            var prev = (int)bucket - 1;
            int dstIndex;

            if (prev == -1)
                dstIndex = newEnd_ - 1 - hiSize_++;
            else
            {
                dstIndex = loSize_++;
                Unsafe.Add(ref links0_, dstIndex) = (ushort)prev;
            }

            Unsafe.Add(ref keys0_, dstIndex) = key;
            bucket = (ushort)(dstIndex + 1);
        }

        _loSize = loSize_;
        _hiSize = hiSize_;
        return newSize;
    }

    //Moves data from src index to dst index and updates all links pointing to src.
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void Move(int src, int dst, ref K dstKey)
    {
        //Move is private and called only from Remove (three sites). Centralizing the
        //version bump here removes the duplicated `_version++` from each Remove branch
        //and still bumps once per Remove (including the src == dst early-return case).
        _version++;
        if (src == dst)
            return;

        //Skip the array-bounds checks: src < _keys.Length and the chain-walked
        //indices are bounded by the same. Same trick the BCL uses internally.
        ref var keys0 = ref MemoryMarshal.GetArrayDataReference(_keys!);
        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        ref var srcKey = ref Unsafe.Add(ref keys0, src);
        ref var srcBucket = ref GetBucket(toUshort(srcKey));
        var index = srcBucket - 1;

        if (index == src)
            srcBucket = (ushort)(dst + 1);
        else
        {
            ref var link = ref Unsafe.Add(ref links0, index);
            while (link != src)
            {
                index = link;
                link = ref Unsafe.Add(ref links0, index);
            }
            link = (ushort)dst;
        }

        if (src < _loSize)
            Unsafe.Add(ref links0, dst) = Unsafe.Add(ref links0, src);

        dstKey = srcKey;
    }

    public bool Remove(K? key)
    {
        if (!key.HasValue)
        {
            if (!_hasNullKey)
                return false;
            _hasNullKey = false;
            _version++;
            return true;
        }

        var kv = key.Value;

        if (IsFlatStrategy)
        {
            var i = toUshort(kv);
            ref var bitword = ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_nulls!), i >> 6);
            var t = bitword;
            if (t == (bitword &= ~(1UL << i)))
                return false;
            _flatCount--;
            _version++;
            return true;
        }

        if (_loSize + _hiSize == 0)
            return false;

        var kUshort = toUshort(kv);
        ref var bucket = ref GetBucket(kUshort);
        var idx = bucket - 1;
        if (idx < 0)
            return false;

        var loSize = _loSize;
        ref var keys0 = ref MemoryMarshal.GetArrayDataReference(_keys!);

        ref var k = ref Unsafe.Add(ref keys0, idx);
        if (loSize <= idx)
        {
            if (toUshort(k) != kUshort)
                return false;
            Move(_keys!.Length - _hiSize, idx, ref k);
            _hiSize--;
            bucket = 0;
            return true;
        }

        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        var prev = -1;
        var prevPrev = -1;

        for (var collisions = 0;
             toUshort(k) != kUshort;
             prevPrev = prev,
                 k = ref Unsafe.Add(ref keys0, idx = Unsafe.Add(ref links0, prev = idx)))
        {
            if (idx >= loSize)
                return false;
            if (++collisions > loSize)
                throw new InvalidOperationException("Hash collision chain is unexpectedly long. Possible data corruption.");
        }

        var lastLo = loSize - 1;
        if (idx < loSize)
        {
            //Standard removal: rewire (prev or bucket) → next; compact lo by swap-with-last.
            //Single read of the matched entry's link; both branches consume `next`.
            var next = Unsafe.Add(ref links0, idx);
            if (prev < 0)
                bucket = (ushort)(next + 1);
            else
                Unsafe.Add(ref links0, prev) = next;
            Move(lastLo, idx, ref k);
        }
        else
        {
            //Found at hi-terminator with chain length ≥ 2. Migrate prev (lo) into the hi slot
            //so the chain still terminates in hi; prev's lo slot becomes the hole.
            ref var prevKey = ref Unsafe.Add(ref keys0, prev);
            k = prevKey;
            if (prevPrev < 0)
                bucket = (ushort)(idx + 1);
            else
                Unsafe.Add(ref links0, prevPrev) = (ushort)idx;
            Move(lastLo, prev, ref prevKey);
        }

        _loSize = lastLo;
        return true;
    }

    public Enumerator GetEnumerator() => new(this);
    IEnumerator<K?> IEnumerable<K?>.GetEnumerator() => GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

    ///<summary>
    ///High-throughput iterator over the set.
    ///<para><b>Flat-mode design (cached bitset word).</b> The previous implementation called
    ///<c>next1(_bitIndex)</c> on every <see cref="MoveNext"/>, which re-computed the word index
    ///<c>(bit+1) &gt;&gt; 6</c>, re-loaded <c>_nulls[index]</c> from the heap, and re-built the mask
    ///<c>~0UL &lt;&lt; (i &amp; 63)</c>. None of that survives across <see cref="MoveNext"/> calls.
    ///The new design keeps the current word and "bits not yet consumed" in the enumerator
    ///struct: each call is just <c>TrailingZeroCount</c> on a register, then <c>bits &amp;= bits - 1</c>
    ///to clear the lowest set bit. The heap is touched once per word (every ~64 items, on
    ///average) instead of once per item.</para>
    ///<para><b>Hash-mode design.</b> Lo-region and hi-region snapshotted at construction so the
    ///instance fields are never re-read during the walk. <c>Unsafe.Add</c> +
    ///<c>MemoryMarshal.GetArrayDataReference</c> skips the JIT-emitted array-bounds check on
    ///<c>_keys</c>; the lo/hi boundary fold collapses the "have I finished" branch to a single
    ///<c>i &gt;= _hiEnd</c> compare.</para>
    ///<para><b>Null-key handling.</b> If <c>_hasNullKey</c> was set at construction, the very first
    ///<see cref="MoveNext"/> yields <c>null</c> before any flat/hash element. State machine:
    ///<c>_index = -1</c> not started, <c>_index = -2</c> finished.</para>
    ///<para><b>Concurrent-modification semantics.</b> Matches BCL Dictionary: the version check
    ///lives in <see cref="MoveNext"/>; <see cref="Current"/> is a bare field read.</para>
    ///</summary>
    public struct Enumerator : IEnumerator<K?>
    {
        private readonly NullableTwoBytesSet<K> _set;
        private readonly int _version;

        //Hash-mode snapshot (null in flat mode).
        private readonly K[]? _keys;
        private readonly int _loEnd;
        private readonly int _hiStart;
        private readonly int _hiEnd;

        //Flat-mode snapshot (null in hash mode).
        private readonly ulong[]? _nulls;

        //Null-key snapshot: yield null first if true.
        private readonly bool _hasNullKey;

        //Iteration state.
        private int _wordIdx;         //flat mode: current word index in _nulls
        private ulong _remainingBits; //flat mode: bits not yet consumed in the current word
        private int _index;           //-1 = not started, -2 = finished, else current bit/index
        private bool _nullEmitted;    //true once the null key has been yielded
        private K? _current;

        internal Enumerator(NullableTwoBytesSet<K> set)
        {
            _set = set;
            _version = set._version;
            _current = default;
            _index = -1;
            _wordIdx = -1;
            _remainingBits = 0;
            _hasNullKey = set._hasNullKey;
            _nullEmitted = false;

            if (set.IsFlatStrategy)
            {
                _keys = null;
                _nulls = set._nulls;
                _loEnd = 0;
                _hiStart = 0;
                _hiEnd = 0;
            }
            else
            {
                _keys = set._keys;
                _nulls = null;
                _loEnd = set._loSize;
                _hiEnd = _keys?.Length ?? 0;
                _hiStart = _hiEnd - set._hiSize;
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool MoveNext()
        {
            if (_version != _set._version)
                throw new InvalidOperationException("Collection was modified during enumeration.");
            if (_index == -2)
                return false;

            //1. Yield the null key first, if present and not yet emitted.
            if (_hasNullKey && !_nullEmitted)
            {
                _nullEmitted = true;
                _current = null;
                return true;
            }

            //2. Flat mode: cached bitset-word walk.
            if (_nulls != null)
                return MoveNextFlat();

            //3. Hash mode: walk lo-region [0..loEnd), then hi-region [hiStart..hiEnd).
            if (_keys == null)
            {
                _index = -2;
                return false;
            }
            var i = _index + 1;
            if (i == _loEnd)
                i = _hiStart;
            if (i >= _hiEnd)
            {
                _index = -2;
                return false;
            }

            _current = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_keys), i);
            _index = i;
            return true;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private bool MoveNextFlat()
        {
            var bits = _remainingBits;
            var wordIdx = _wordIdx;

            //Drain remaining set bits in the current word; advance to the next non-zero word
            //only when the current one is exhausted. The heap is touched once per word.
            if (bits == 0)
            {
                ref var nulls0 = ref MemoryMarshal.GetArrayDataReference(_nulls!);
                do
                {
                    if (++wordIdx >= NULLS_SIZE)
                    {
                        _index = -2;
                        return false;
                    }
                    bits = Unsafe.Add(ref nulls0, wordIdx);
                } while (bits == 0);
            }

            var trailing = BitOperations.TrailingZeroCount(bits);
            var bitPos = (wordIdx << 6) + trailing;
            _current = Unsafe.As<int, K>(ref bitPos);
            _remainingBits = bits & (bits - 1); //clear lowest set bit
            _wordIdx = wordIdx;
            _index = bitPos;
            return true;
        }

        public K? Current
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _current;
        }

        object? IEnumerator.Current => _current;

        public void Reset()
        {
            if (_version != _set._version)
                throw new InvalidOperationException("Collection was modified during enumeration.");
            _index = -1;
            _wordIdx = -1;
            _remainingBits = 0;
            _nullEmitted = false;
            _current = default;
        }

        public void Dispose() {}
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static ushort toUshort(K key) => Unsafe.As<K, ushort>(ref key);
#region Flat Strategy Helpers
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private bool exists(K key) => (_nulls![toUshort(key) >> 6] & 1UL << toUshort(key)) != 0;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void exists1(K key, ulong[] nulls) => nulls[toUshort(key) >> 6] |= 1UL << toUshort(key);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    protected int next1(int bit) => next1(bit, _nulls!);

    protected static int next1(int bit, ulong[] nulls)
    {
        if (0xFFFF <= bit)
            return -1;
        var i = ++bit;
        var index = i >> 6;
        var value = nulls![index] & ~0UL << (i & 63);

        while (value == 0)
            if (++index == NULLS_SIZE)
                return -1;
            else
                value = nulls[index];

        return (index << 6) + BitOperations.TrailingZeroCount(value);
    }

    //Helper to count set bits in _nulls for flat strategy
    private int CalculateFlatCount()
    {
        var count = 0;
        ref var nullsRef = ref MemoryMarshal.GetArrayDataReference(_nulls!);
        for (var i = 0; i < NULLS_SIZE; i++)
            count += BitOperations.PopCount(Unsafe.Add(ref nullsRef, i));
        return count;
    }
#endregion
#region ISet Explicit / Remaining Implementation
    public bool IsReadOnly => false;

    public void ExceptWith(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        if (Count == 0)
            return;
        if (other is NullableTwoBytesSet<K> otherSet && otherSet.Count == 0)
            return;

        if (IsFlatStrategy && other is NullableTwoBytesSet<K> { IsFlatStrategy : true } otherTbs)
        {
            ref var nullsRef = ref MemoryMarshal.GetArrayDataReference(_nulls!);
            ref var otherNullsRef = ref MemoryMarshal.GetArrayDataReference(otherTbs._nulls!);
            for (var i = 0; i < NULLS_SIZE; i++)
                Unsafe.Add(ref nullsRef, i) &= ~Unsafe.Add(ref otherNullsRef, i);
            _hasNullKey &= !otherTbs._hasNullKey;
            _flatCount = CalculateFlatCount();
            _version++;
            return;
        }

        foreach (var key in other)
            Remove(key);
    }

    public void IntersectWith(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);

        if (IsFlatStrategy && other is NullableTwoBytesSet<K> { IsFlatStrategy : true } otherTbs)
        {
            ref var nullsRef = ref MemoryMarshal.GetArrayDataReference(_nulls!);
            ref var otherNullsRef = ref MemoryMarshal.GetArrayDataReference(otherTbs._nulls!);
            for (var i = 0; i < NULLS_SIZE; i++)
                Unsafe.Add(ref nullsRef, i) &= Unsafe.Add(ref otherNullsRef, i);
            _hasNullKey &= otherTbs._hasNullKey;
            _flatCount = CalculateFlatCount();
            _version++;
            return;
        }

        var t = new NullableTwoBytesSet<K>();
        foreach (var key in other)
            if (Contains(key))
                t.Add(key);

        _buckets = t._buckets;
        _keys = t._keys;
        _links = t._links;
        _hiSize = t._hiSize;
        _loSize = t._loSize;
        _flatCount = t._flatCount;
        _version++;
        _mask = t._mask;
        _hasNullKey = t._hasNullKey;
        _nulls = t._nulls;
    }

    public void SymmetricExceptWith(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        if (other == this)
        {
            Clear();
            return;
        }

        if (IsFlatStrategy && other is NullableTwoBytesSet<K> { IsFlatStrategy : true } otherTbs)
        {
            ref var nullsRef = ref MemoryMarshal.GetArrayDataReference(_nulls!);
            ref var otherNullsRef = ref MemoryMarshal.GetArrayDataReference(otherTbs._nulls!);
            for (var i = 0; i < NULLS_SIZE; i++)
                Unsafe.Add(ref nullsRef, i) ^= Unsafe.Add(ref otherNullsRef, i);
            _hasNullKey ^= otherTbs._hasNullKey;
            _flatCount = CalculateFlatCount();
            _version++;
            return;
        }

        foreach (var key in other)
            if (!Remove(key))
                Add(key);
    }

    public void UnionWith(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);

        if (IsFlatStrategy && other is NullableTwoBytesSet<K> { IsFlatStrategy : true } otherTbs)
        {
            ref var nullsRef = ref MemoryMarshal.GetArrayDataReference(_nulls!);
            ref var otherNullsRef = ref MemoryMarshal.GetArrayDataReference(otherTbs._nulls!);
            for (var i = 0; i < NULLS_SIZE; i++)
                Unsafe.Add(ref nullsRef, i) |= Unsafe.Add(ref otherNullsRef, i);
            _hasNullKey |= otherTbs._hasNullKey;
            _flatCount = CalculateFlatCount();
            _version++;
            return;
        }

        foreach (var key in other)
            Add(key);
    }

    public bool IsProperSubsetOf(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        var otherCollection = other as ICollection<K?> ?? new HashSet<K?>(other);
        return Count < otherCollection.Count && IsSubsetOf(otherCollection);
    }

    public bool IsProperSupersetOf(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        var otherCollection = other as ICollection<K?> ?? new HashSet<K?>(other);
        return Count > otherCollection.Count && IsSupersetOf(otherCollection);
    }

    public bool IsSubsetOf(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        if (Count == 0)
            return true;
        var otherAsSet = other as ISet<K?> ?? new HashSet<K?>(other);
        if (Count > otherAsSet.Count)
            return false;

        //Fast path
        if (IsFlatStrategy && other is NullableTwoBytesSet<K> { IsFlatStrategy : true } otherTbs)
        {
            if (_hasNullKey && !otherTbs._hasNullKey)
                return false;
            ref var nullsRef = ref MemoryMarshal.GetArrayDataReference(_nulls!);
            ref var otherNullsRef = ref MemoryMarshal.GetArrayDataReference(otherTbs._nulls!);
            for (var i = 0; i < NULLS_SIZE; i++)
                if ((Unsafe.Add(ref nullsRef, i) & ~Unsafe.Add(ref otherNullsRef, i)) != 0)
                    return false;

            return true;
        }

        foreach (var key in this)
            if (!otherAsSet.Contains(key))
                return false;
        return true;
    }

    public bool IsSupersetOf(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        if (other is ICollection<K?> { Count : 0 })
            return true;

        //Fast path
        if (IsFlatStrategy && other is NullableTwoBytesSet<K> { IsFlatStrategy : true } otherTbs)
        {
            if (otherTbs._hasNullKey && !_hasNullKey)
                return false;
            ref var nullsRef = ref MemoryMarshal.GetArrayDataReference(_nulls!);
            ref var otherNullsRef = ref MemoryMarshal.GetArrayDataReference(otherTbs._nulls!);
            for (var i = 0; i < NULLS_SIZE; i++)
                if ((Unsafe.Add(ref otherNullsRef, i) & ~Unsafe.Add(ref nullsRef, i)) != 0)
                    return false;

            return true;
        }

        foreach (var key in other)
            if (!Contains(key))
                return false;
        return true;
    }

    public bool Overlaps(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        if (Count == 0)
            return false;

        //Fast path
        if (IsFlatStrategy && other is NullableTwoBytesSet<K> { IsFlatStrategy : true } otherTbs)
        {
            if (_hasNullKey && otherTbs._hasNullKey)
                return true;
            ref var nullsRef = ref MemoryMarshal.GetArrayDataReference(_nulls!);
            ref var otherNullsRef = ref MemoryMarshal.GetArrayDataReference(otherTbs._nulls!);
            for (var i = 0; i < NULLS_SIZE; i++)
                if ((Unsafe.Add(ref nullsRef, i) & Unsafe.Add(ref otherNullsRef, i)) != 0)
                    return true;

            return false;
        }

        foreach (var key in other)
            if (Contains(key))
                return true;
        return false;
    }

    public bool SetEquals(IEnumerable<K?> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        var otherAsSet = other as ISet<K?> ?? new HashSet<K?>(other);
        return Count == otherAsSet.Count && IsSupersetOf(otherAsSet);
    }
#endregion

    public int EnsureCapacity(int capacity)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(capacity);
        var currentCapacity = _keys?.Length ?? (IsFlatStrategy ? VALUES_SIZE : 0);
        if (currentCapacity >= capacity)
            return currentCapacity;
        _version++;
        if (_buckets == null && !IsFlatStrategy)
            return Initialize(capacity);
        var newSize = GetPowerOfTwo(capacity);
        Resize(newSize);
        return newSize;
    }

    public void TrimExcess()
    {
        var count = Count;
        if (count == 0)
        {
            Initialize(0);
            return;
        }

        if (IsFlatStrategy)
        {
            if (count <= flatStrategyThreshold)
            {
                Resize(GetPowerOfTwo(count));
            }
        }
        else if (_keys != null)
        {
            var newSize = GetPowerOfTwo(count);
            if (newSize < _keys.Length)
            {
                Resize(newSize);
            }
        }
    }
}