//Copyright 2025 Chikirev Sirguy, Unirail Group. All rights reserved.
//
//This file is part of the AdHoc protocol runtime library.
//
//Licensed under the PolyForm Shield License 1.0.0. The full text is distributed with this
//file as LICENSE.md and is published at https://polyformproject.org/licenses/shield/1.0.0
//
//In short: you may use, modify and distribute this software for any purpose, except to
//provide a product that competes with the software, or with any product the licensor
//provides using the software. Competition is judged by function, not by form.
//
//The plain-text notice lines the license requires you to pass on - the Required Notice and
//the Licensor Line of Business - are in the NOTICE file distributed with this library.
//Keep LICENSE.md and NOTICE with any copy of this software that you distribute.
//
//Code generated by the AdHoc generator is NOT part of the Licensed Work and carries no
//restrictions whatsoever - see the header of any generated file.
//
//Provided as is, without any warranty or condition.
//
//Commercial licenses that remove the noncompete restriction are available.
//For licensing and inquiries: al8v5C6HU4UtqE9@gmail.com

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;

namespace org.unirail.collections;

///<summary>
///A lock-free, bounded object pool designed to prevent false sharing and handle high concurrency.
///<para>
///</para>
///
///<para><b>Benchmark, single-threaded Acquire+Release</b> (N = 1 000 000, .NET 9, Release):</para>
///<code>
///Acquire+Release
///Pool&lt;object&gt;             51 977 329   ops/sec    (alloc 0 B/op)
///Queue&lt;object&gt; (manual)         4.50   x          (alloc 0 B/op, but NOT thread-safe)
///ConcurrentQueue                 1.43   x          (alloc 0 B/op)
///new object() (no pool)          9.61   x          (alloc 24 B/op — pure GC pressure)
///</code>
///<para>
///Ratio &gt; 1 ⇒ alternative faster. Pool trades raw single-threaded throughput for lock-free
///concurrent safety + zero per-op allocation. Direct allocation wins on speed but pays 24 B/op
///GC pressure (Pool: 0). For single-thread reuse a plain <c>Queue&lt;T&gt;</c> is ~4.5× faster.
///Pool's value is multi-thread Acquire/Release without locking — see <c>PaddedInt</c>'s
///cache-line padding to avoid false sharing on the read/write indices.
///</para>
///<para>See <c>Tests/Benchmarks/PoolBenchmark.cs</c> for the full scenarios and an HTML report.</para>
///</summary>
///<typeparam name="T">The type of the objects in the pool. Must be a reference type.</typeparam>
public sealed class Pool<T>
    where T : class
{
    //The buffer storing items.
    readonly T?[] _items;

    //Mask used to wrap indices (capacity - 1).
    readonly int _mask;

    //Factory delegate to create new items when the pool is empty or under contention.
    readonly Func<T> _factory;

    PaddedInt _readIndex;
    PaddedInt _writeIndex;

    ///<summary>
    ///Initializes a new instance of the Pool.
    ///</summary>
    ///<param name="powerOf2">The capacity as a power of 2 (e.g., 10 means capacity 1024). Range 1-30.</param>
    ///<param name="factory">Delegate to create new instances of T.</param>
    public Pool(int powerOf2, Func<T> factory)
    {
        if (powerOf2 is < 1 or > 30)
            throw new ArgumentOutOfRangeException(nameof(powerOf2), "powerOf2 must be between 1 and 30");

        ArgumentNullException.ThrowIfNull(factory);

        var capacity = 1 << powerOf2;
        _items = new T[capacity];
        _mask = capacity - 1;
        _factory = factory;
    }

    ///<summary>
    ///Retrieves an item from the pool.
    ///If the pool is empty or under heavy contention, a new item is created via the factory.
    ///</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public T Acquire()
    {
        //Optimistic check: If indices match, pool looks empty.
        //Direct access to .Value is safe here for a "dirty" read.
        if (_readIndex.Value == _writeIndex.Value)
            return _factory();

        while (true)
        {
            //Volatile reads to ensure we get fresh values from main memory/cache
            var read = Volatile.Read(ref _readIndex.Value);
            var write = Volatile.Read(ref _writeIndex.Value);

            if (read == write)
                return _factory();

            if (Interlocked.CompareExchange(ref _readIndex.Value, read + 1, read) != read)
                continue; //Another thread stole the cursor; spin and retry.

            var item = Interlocked.Exchange(ref _items[read & _mask], null);

            //If item is null, it means a Writer claimed the write-slot but hasn't
            //finished writing the object yet (race condition).
            //In that case, we fall back to creating a new object.
            return item ?? _factory();
        }
    }

    ///<summary>
    ///Returns an item to the pool.
    ///If the pool is full, the item is dropped (left for GC).
    ///</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Release(T item)
    {
        if (item == null)
            return;

        while (true)
        {
            var write = Volatile.Read(ref _writeIndex.Value);
            var read = Volatile.Read(ref _readIndex.Value);

            if ((uint)_items.Length <= (uint)(write - read))
                return; //Buffer full. Drop item.

            if (Interlocked.CompareExchange(ref _writeIndex.Value, write + 1, write) != write)
                continue; //Another thread advanced the cursor; spin and retry.

            Volatile.Write(ref _items[write & _mask], item);
            return;
        }
    }

    ///<summary>
    ///The total capacity of the pool.
    ///</summary>
    public int Capacity => _items.Length;

    ///<summary>
    ///The approximate number of items currently available.
    ///</summary>
    public int Count =>
        //Calculate count using modular arithmetic logic (via uint cast) to handle wrapping.
        Math.Max(0, (int)((uint)_writeIndex.Value - (uint)_readIndex.Value));
}

//--- False Sharing Prevention ---
//We use a custom struct with Explicit Layout to force the Read and Write indices
//to reside on separate cache lines.
//Most modern cache lines are 64 bytes (x64). Apple Silicon/ARM can be 128 bytes.
//Size = 128 ensures no overlap regardless of architecture.

[StructLayout(LayoutKind.Explicit, Size = 128)]
struct PaddedInt
{
    [FieldOffset(0)]
    public int Value;
}
