//Copyright 2025 Chikirev Sirguy, Unirail Group. All rights reserved.
//
//This file is part of the AdHoc protocol runtime library.
//
//Licensed under the PolyForm Shield License 1.0.0. The full text is distributed with this
//file as LICENSE.md and is published at https://polyformproject.org/licenses/shield/1.0.0
//
//In short: you may use, modify and distribute this software for any purpose, except to
//provide a product that competes with the software, or with any product the licensor
//provides using the software. Competition is judged by function, not by form.
//
//The plain-text notice lines the license requires you to pass on - the Required Notice and
//the Licensor Line of Business - are in the NOTICE file distributed with this library.
//Keep LICENSE.md and NOTICE with any copy of this software that you distribute.
//
//Code generated by the AdHoc generator is NOT part of the Licensed Work and carries no
//restrictions whatsoever - see the header of any generated file.
//
//Provided as is, without any warranty or condition.
//
//Commercial licenses that remove the noncompete restriction are available.
//For licensing and inquiries: al8v5C6HU4UtqE9@gmail.com

using System;
using System.Collections;
using System.Collections.Generic;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace org.unirail.collections;

///<summary>
///Represents a set of unique primitive values of type <typeparamref name="K"/>.
///This set implementation uses a hash table and is optimized for primitive types.
///<para><b>Storage layout:</b> dual-region <c>_keys</c> array (lo-region for collision-chain entries,
///hi-region for chain terminators), plus a side <c>_links</c> array sized only to the lo-region —
///memory paid only for actual collisions. See <see cref="PrimitiveKeyMap{K,V}"/> for the full
///discussion of why this layout was selected over inlined-next variants.</para>
///
///<para><b>Benchmark vs <c>HashSet&lt;int&gt;</c></b> (N = 100 000, random int keys, .NET 9, Release):</para>
///<code>
///Insert       Search          Get          Iterate        Delete         Churn
///PrimitiveSet&lt;int&gt;  49 011 714  144 035 886  133 485 889      809 903 969    18 997 476    18 163 325   ops/sec
///HashSet                 0.87         0.70         0.64             1.30          2.09          2.30   x
///</code>
///<para><b>Memory profile (grow-from-empty Insert, 100 000 random int keys):</b>
///<list type="bullet">
///<item><c>PrimitiveSet</c> allocates <b>26.23 B/op</b> (grow-from-empty Insert, 100 000 random int keys of 100 000 records)</item>
///<item><c>HashSet</c> allocates <b>48.30 B/op</b></item>
///<item><c>PrimitiveSet</c> saves <b>~22 077 B per 1 000 records</b> vs HashSet</item>
///</list>
///</para>
///<para>
///Ratio &gt; 1 ⇒ <c>HashSet</c> faster, &lt; 1 ⇒ <c>PrimitiveSet</c> faster. PrimitiveSet wins on
///Insert (1.15× on grow / 1.51× pre-sized) and on every read path (1.4–1.55×); HashSet wins on
///Iterate (its single contiguous entry array enjoys better cache flow than our dual-region split)
///and on Remove (~2× — the structural cost of dual-region compaction).
///</para>
///<para>See <c>Tests/Benchmarks/PrimitiveSetBenchmark.cs</c> for the full scenarios and an HTML report.</para>
///</summary>
///<typeparam name="K">The type of the primitive values in the set. Must be an unmanaged type.</typeparam>
public class PrimitiveSet<K> : ISet<K>, IReadOnlyCollection<K>
    where K : unmanaged
{
    private uint[]? _buckets;
    private K[]? _keys;
    private uint[]? _links; //0-based indices into _keys for collision chains.

    //The _keys array is split into two regions to optimize for non-colliding entries:
    //1. Lo-Region (indices 0 to _loSize-1): Stores keys that have caused a hash collision.
    //2. Hi-Region (indices _keys.Length - _hiSize to _keys.Length-1): Stores keys that have not caused a collision.
    private int _hiSize; //Number of active entries in the high region.
    private int _loSize; //Number of active entries in the low region.

    private int _version;
    private uint _mask;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private ref uint GetBucket(uint hashCode) => ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_buckets!), hashCode &_mask);

    private const int DefaultCapacity = 4;

    public PrimitiveSet() : this(0) {}

    public PrimitiveSet(int capacity)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(capacity);
        if (capacity > 0)
            Initialize(capacity);
    }

    public PrimitiveSet(IEnumerable<K> collection) : this(collection is ICollection<K> coll ? coll.Count : 0)
    {
        ArgumentNullException.ThrowIfNull(collection);
        AddRange(collection);
    }

    private void AddRange(IEnumerable<K> enumerable)
    {
        foreach (var key in enumerable)
            Add(key);
    }

    public int Count
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => _loSize + _hiSize;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool Add(K key)
    {
        if (_buckets == null)
            Initialize(DefaultCapacity);

        var keys = _keys!;
        if (keys.Length <= _loSize + _hiSize)
        {
            Resize(keys.Length * 2);
            keys = _keys!;
        }

        ref var bucket = ref GetBucket((uint)key.GetHashCode());
        var index = (int)bucket - 1;

        ref var keysRef = ref MemoryMarshal.GetArrayDataReference(keys);
        int dstIndex;

        if (index == -1) //Bucket is empty: place new entry in hi-region
            dstIndex = keys.Length - 1 - _hiSize++;
        else
        {
            ref var linksRef = ref MemoryMarshal.GetArrayDataReference(_links!);
            var loSize = _loSize;
            for (int i = index, collisions = 0;;)
            {
                if (EqualityComparer<K>.Default.Equals(Unsafe.Add(ref keysRef, i), key))
                    return false;

                if (loSize <= i)
                    break; //Reached a hi-region entry, end of this chain.
                i = (int)Unsafe.Add(ref linksRef, i);

                if (loSize + 1 < collisions++)
                    throw new InvalidOperationException("Concurrent operations not supported.");
            }

            if (_links!.Length == (dstIndex = _loSize++))
                Array.Resize(ref _links, Math.Max(16, Math.Min(_buckets!.Length, _links.Length * 2)));

            //Re-fetch links ref (Array.Resize may have allocated a new array).
            Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_links!), dstIndex) = (uint)index;
        }

        Unsafe.Add(ref keysRef, dstIndex) = key;
        bucket = (uint)(dstIndex + 1);
        _version++;
        return true;
    }

    void ICollection<K>.Add(K key) => Add(key);

    public void Clear()
    {
        if (Count == 0)
            return;

        _version++;

        if (_buckets != null)
            Array.Clear(_buckets, 0, _buckets.Length);
        _loSize = 0;
        _hiSize = 0;
    }

    public bool Contains(K key)
    {
        if (_loSize + _hiSize == 0)
            return false;

        var i = (int)GetBucket((uint)key.GetHashCode()) - 1;
        if (i == -1)
            return false;

        ref var keysRef = ref MemoryMarshal.GetArrayDataReference(_keys!);
        ref var linksRef = ref MemoryMarshal.GetArrayDataReference(_links!);
        var loSize = _loSize;

        for (var collisions = 0;;)
        {
            if (EqualityComparer<K>.Default.Equals(Unsafe.Add(ref keysRef, i), key))
                return true;

            if (loSize <= i)
                return false; //Reached end of chain (a hi-region entry)
            i = (int)Unsafe.Add(ref linksRef, i);

            if (loSize < ++collisions)
                throw new InvalidOperationException("Hash collision chain is unexpectedly long. Possible data corruption.");
        }
    }

    public void CopyTo(K[] dst, int dstIndex)
    {
        ArgumentNullException.ThrowIfNull(dst);
        ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual((uint)dstIndex, (uint)dst.Length);
        if (dst.Length - dstIndex < Count)
            throw new ArgumentException("Destination array is not long enough.");

        //Copy lo-region
        Array.Copy(_keys!, 0, dst, dstIndex, _loSize);
        //Copy hi-region
        Array.Copy(_keys!, _keys!.Length - _hiSize, dst, dstIndex + _loSize, _hiSize);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private int Initialize(int capacity, int linksHint = 16)
    {
        _version++;

        var size = GetPowerOfTwo(capacity);
        _buckets = new uint[size];
        _keys = new K[size];
        _links = new uint[Math.Min(size, linksHint)];
        _loSize = _hiSize = 0;
        _mask = (uint)(size - 1);

        return size;
    }

    private static int GetPowerOfTwo(int capacity) => capacity <= DefaultCapacity ? DefaultCapacity : (int)BitOperations.RoundUpToPowerOf2((uint)capacity);

    ///<summary>
    ///Rebuilds the table at <paramref name="newSize"/>, re-inserting every old key.
    ///<para>
    ///<b>Memory win — pre-size <c>_links</c> once.</b> The previous implementation called a per-entry
    ///<c>Copy</c> helper that doubled <c>_links</c> from 16 → 32 → 64 → … → roundUpPowerOf2(N) as
    ///entries streamed in. By passing the precise <c>linksHint</c> to <c>Initialize</c>, we make
    ///<b>zero</b> intermediate allocations and the kept array is right-sized.
    ///</para>
    ///<para><b>Speed win — hoist hot fields.</b> The per-entry rebuild loop reads <c>_buckets</c>,
    ///<c>_mask</c>, <c>_hiSize</c>, <c>_loSize</c> on every iteration. The JIT cannot hoist them across
    ///the <c>_hiSize++</c>/<c>_loSize++</c> writes, so they compile to repeated memory loads. We hoist
    ///them into locals (<c>buckets0</c>, <c>mask</c>, <c>hiSize</c>, <c>loSize</c>) and write back at
    ///the end. Combined with cached <c>Unsafe.Add</c> refs and no JIT bounds checks, the loop body
    ///reduces to register-only work plus the unavoidable hash + memory writes.</para>
    ///</summary>
    private int Resize(int newSize)
    {
        _version++;
        var oldKeys = _keys;
        var oldLoSize = _loSize;
        var oldHiSize = _hiSize;
        var oldEnd = oldKeys!.Length;
        var oldHiStart = oldEnd - oldHiSize;

        //Pass the precise linksHint so Initialize sizes _links to fit all surviving entries
        //worst-case (every old entry could re-collide into lo). No throwaway 16-element alloc.
        var totalEntries = oldLoSize + oldHiSize;
        Initialize(newSize, totalEntries);

        ref var oldKeys0 = ref MemoryMarshal.GetArrayDataReference(oldKeys);
        ref var keys0 = ref MemoryMarshal.GetArrayDataReference(_keys!);
        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        ref var buckets0 = ref MemoryMarshal.GetArrayDataReference(_buckets!);
        var mask = _mask;
        var newEnd = _keys!.Length;
        var loSize = 0;
        var hiSize = 0;

        //Re-insert lo region [0..oldLoSize)
        for (var i = 0; i < oldLoSize; i++)
        {
            var key = Unsafe.Add(ref oldKeys0, i);
            ref var bucket = ref Unsafe.Add(ref buckets0, (nint)((uint)key.GetHashCode() & mask));
            var prev = (int)bucket - 1;
            int dstIndex;

            if (prev == -1)
                dstIndex = newEnd - 1 - hiSize++;
            else
            {
                dstIndex = loSize++; //pre-sized: never resizes here
                Unsafe.Add(ref links0, dstIndex) = (uint)prev;
            }

            Unsafe.Add(ref keys0, dstIndex) = key;
            bucket = (uint)(dstIndex + 1);
        }

        //Re-insert hi region [oldHiStart..oldEnd)
        for (var i = oldHiStart; i < oldEnd; i++)
        {
            var key = Unsafe.Add(ref oldKeys0, i);
            ref var bucket = ref Unsafe.Add(ref buckets0, (nint)((uint)key.GetHashCode() & mask));
            var prev = (int)bucket - 1;
            int dstIndex;

            if (prev == -1)
                dstIndex = newEnd - 1 - hiSize++;
            else
            {
                dstIndex = loSize++;
                Unsafe.Add(ref links0, dstIndex) = (uint)prev;
            }

            Unsafe.Add(ref keys0, dstIndex) = key;
            bucket = (uint)(dstIndex + 1);
        }

        _loSize = loSize;
        _hiSize = hiSize;
        return newSize;
    }

    //Moves data from src index to dst index and updates all links pointing to src.
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void Move(int src, int dst, ref K dstKey)
    {
        //Move is private and called only from Remove (three sites). Centralizing the
        //version bump here removes the duplicated `_version++` from each Remove branch
        //and still bumps once per Remove (including the src == dst early-return case).
        _version++;
        if (src == dst)
            return;

        //Skip the array-bounds checks: src < _keys.Length and the chain-walked
        //indices are bounded by the same. Same trick the BCL uses internally.
        ref var keys0 = ref MemoryMarshal.GetArrayDataReference(_keys!);
        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        ref var srcKey = ref Unsafe.Add(ref keys0, src);
        ref var srcBucket = ref GetBucket((uint)srcKey.GetHashCode());
        var index = (int)srcBucket - 1;

        if (index == src)
            srcBucket = (uint)(dst + 1);
        else
        {
            ref var link = ref Unsafe.Add(ref links0, index);
            while (link != src)
            {
                index = (int)link;
                link = ref Unsafe.Add(ref links0, index);
            }
            link = (uint)dst;
        }

        if (src < _loSize)
            Unsafe.Add(ref links0, dst) = Unsafe.Add(ref links0, src);

        dstKey = srcKey;
    }

    ///<summary>
    ///Removes <paramref name="key"/> if present.
    ///<para>Index-based chain walk (no <c>ref</c> aliasing across iterations) so the JIT can keep
    ///the loop in registers. Tracks <c>prev</c>/<c>prevPrev</c> indices so the hi-terminator
    ///migration case rewires the back-pointer in O(1).</para>
    ///</summary>
    public bool Remove(K key)
    {
        if (_loSize + _hiSize == 0)
            return false;

        ref var bucket = ref GetBucket((uint)key.GetHashCode());
        var idx = (int)bucket - 1;
        if (idx < 0)
            return false;

        var loSize = _loSize;
        ref var keys0 = ref MemoryMarshal.GetArrayDataReference(_keys!);

        ref var k = ref Unsafe.Add(ref keys0, idx);
        if (loSize <= idx)
        {
            if (!EqualityComparer<K>.Default.Equals(k, key))
                return false;
            Move(_keys!.Length - _hiSize, idx, ref k);
            _hiSize--;
            bucket = 0;
            return true;
        }

        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        var prev = -1;
        var prevPrev = -1;

        for (var collisions = 0;
             !EqualityComparer<K>.Default.Equals(k, key);
             prevPrev = prev,
                 k = ref Unsafe.Add(ref keys0, idx = (int)Unsafe.Add(ref links0, prev = idx)))
        {
            if (idx >= loSize)
                return false;
            if (++collisions > loSize)
                throw new InvalidOperationException("Hash collision chain is unexpectedly long. Possible data corruption.");
        }

        var lastLo = loSize - 1;
        if (idx < loSize)
        {
            //Standard removal: rewire (prev or bucket) → next; compact lo by swap-with-last.
            //Single read of the matched entry's link; both branches consume `next`.
            var next = Unsafe.Add(ref links0, idx);
            if (prev < 0)
                bucket = next + 1;
            else
                Unsafe.Add(ref links0, prev) = next;
            Move(lastLo, idx, ref k);
        }
        else
        {
            //Found at hi-terminator with chain length ≥ 2. Migrate prev (lo) into the hi slot
            //so the chain still terminates in hi; prev's lo slot becomes the hole.
            ref var prevKey = ref Unsafe.Add(ref keys0, prev);
            k = prevKey;
            if (prevPrev < 0)
                bucket = (uint)(idx + 1);
            else
                Unsafe.Add(ref links0, prevPrev) = (uint)idx;
            Move(lastLo, prev, ref prevKey);
        }

        _loSize = lastLo;
        return true;
    }

    public Enumerator GetEnumerator() => new(this);
    IEnumerator<K> IEnumerable<K>.GetEnumerator() => GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

    public struct Enumerator : IEnumerator<K>
    {
        private readonly PrimitiveSet<K> _set;
        private readonly K[]? _keys;
        private readonly int _loEnd;
        private readonly int _hiStart;
        private readonly int _hiEnd;
        private readonly int _version;
        private int _index; //-1 = not started, -2 = finished, else current index
        private K _current;

        internal Enumerator(PrimitiveSet<K> set)
        {
            _set = set;
            _version = set._version;
            _keys = set._keys;
            _loEnd = set._loSize;
            _hiEnd = _keys?.Length ?? 0;
            _hiStart = _hiEnd - set._hiSize;
            _index = -1;
            _current = default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool MoveNext()
        {
            if (_version != _set._version)
                throw new InvalidOperationException("Collection was modified during enumeration.");
            if (_index == -2)
                return false;

            var i = _index + 1;
            if (i == _loEnd)
                i = _hiStart;
            if (i >= _hiEnd)
            {
                _index = -2;
                return false;
            }

            _current = _keys![i];
            _index = i;
            return true;
        }

        public K Current
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {
                if (_version != _set._version)
                    throw new InvalidOperationException("Collection was modified during enumeration.");
                if (_index < 0)
                    throw new InvalidOperationException("Enumeration has either not started or has finished.");
                return _current;
            }
        }

        object IEnumerator.Current => Current!;

        public void Reset()
        {
            if (_version != _set._version)
                throw new InvalidOperationException("Collection was modified during enumeration.");
            _index = -1;
            _current = default;
        }

        public void Dispose() {}
    }
#region ISet Explicit / Remaining Implementation
    public bool IsReadOnly => false;

    public void ExceptWith(IEnumerable<K> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        if (Count == 0)
            return;
        if (other is PrimitiveSet<K> otherSet && otherSet.Count == 0)
            return;

        foreach (var key in other)
            Remove(key);
    }

    public void IntersectWith(IEnumerable<K> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        if (Count == 0 || other == this)
            return;

        var t = new PrimitiveSet<K>();
        foreach (var key in other)
            if (Contains(key))
                t.Add(key);

        _buckets = t._buckets;
        _keys = t._keys;
        _links = t._links;
        _hiSize = t._hiSize;
        _loSize = t._loSize;
        _version++;
        _mask = t._mask;
    }

    public void SymmetricExceptWith(IEnumerable<K> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        if (other == this)
        {
            Clear();
            return;
        }

        foreach (var key in other)
            if (!Remove(key))
                Add(key);
    }

    public void UnionWith(IEnumerable<K> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        foreach (var key in other)
            Add(key);
    }

    public bool IsProperSubsetOf(IEnumerable<K> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        var otherCollection = other as ICollection<K> ?? new HashSet<K>(other);
        return Count < otherCollection.Count && IsSubsetOf(otherCollection);
    }

    public bool IsProperSupersetOf(IEnumerable<K> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        var otherCollection = other as ICollection<K> ?? new HashSet<K>(other);
        return Count > otherCollection.Count && IsSupersetOf(otherCollection);
    }

    public bool IsSubsetOf(IEnumerable<K> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        if (Count == 0)
            return true;
        var otherAsSet = other as ISet<K> ?? new HashSet<K>(other);
        if (Count > otherAsSet.Count)
            return false;

        foreach (var key in this)
            if (!otherAsSet.Contains(key))
                return false;
        return true;
    }

    public bool IsSupersetOf(IEnumerable<K> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        if (other is ICollection<K> { Count : 0 })
            return true;

        foreach (var key in other)
            if (!Contains(key))
                return false;
        return true;
    }

    public bool Overlaps(IEnumerable<K> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        if (Count == 0)
            return false;

        foreach (var key in other)
            if (Contains(key))
                return true;
        return false;
    }

    public bool SetEquals(IEnumerable<K> other)
    {
        ArgumentNullException.ThrowIfNull(other);
        var otherAsSet = other as ISet<K> ?? new HashSet<K>(other);
        return Count == otherAsSet.Count && IsSupersetOf(otherAsSet);
    }
#endregion

    public int EnsureCapacity(int capacity)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(capacity);
        var currentCapacity = _keys?.Length ?? 0;
        if (currentCapacity >= capacity)
            return currentCapacity;
        _version++;
        if (_buckets == null)
            return Initialize(capacity);
        var newSize = GetPowerOfTwo(capacity);
        Resize(newSize);
        return newSize;
    }

    public void TrimExcess()
    {
        var count = Count;
        if (count == 0)
        {
            Initialize(0);
            return;
        }

        if (_keys != null)
        {
            var newSize = GetPowerOfTwo(count);
            if (newSize < _keys.Length)
            {
                Resize(newSize);
            }
        }
    }
}