//Copyright 2025 Chikirev Sirguy, Unirail Group. All rights reserved.
//
//This file is part of the AdHoc protocol runtime library.
//
//Licensed under the PolyForm Shield License 1.0.0. The full text is distributed with this
//file as LICENSE.md and is published at https://polyformproject.org/licenses/shield/1.0.0
//
//In short: you may use, modify and distribute this software for any purpose, except to
//provide a product that competes with the software, or with any product the licensor
//provides using the software. Competition is judged by function, not by form.
//
//The plain-text notice lines the license requires you to pass on - the Required Notice and
//the Licensor Line of Business - are in the NOTICE file distributed with this library.
//Keep LICENSE.md and NOTICE with any copy of this software that you distribute.
//
//Code generated by the AdHoc generator is NOT part of the Licensed Work and carries no
//restrictions whatsoever - see the header of any generated file.
//
//Provided as is, without any warranty or condition.
//
//Commercial licenses that remove the noncompete restriction are available.
//For licensing and inquiries: al8v5C6HU4UtqE9@gmail.com

using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace org.unirail.collections;

///<summary>
///Hash map with primitive (unmanaged) keys, optimized for top throughput and minimal GC pressure.
///<para><b>Storage layout (current — selected design):</b></para>
///<para>
///A single <see cref="Entry"/> array <c>_entries</c> is split into two regions to optimize for the
///common case where most entries do not collide:
///</para>
///<list type="bullet">
///<item><b>Hi-region</b> [<c>_entries.Length - _hiSize .. _entries.Length</c>) — chain terminators
///(entries placed when their bucket was empty). They have no successor; the chain ends there.</item>
///<item><b>Lo-region</b> [<c>0 .. _loSize</c>) — collision-chain elements. Their successor index is
///stored in a separate side array <c>_links</c> sized only to <c>_loSize</c> (not capacity), so the
///memory cost is paid only when collisions actually occur.</item>
///</list>
///<para>
///Chain termination is detected implicitly by the bound <c>_loSize &lt;= i</c> while walking — no
///sentinel and no per-hop region flag are needed. The chain walk reads <c>_entries[i]</c> and, on a
///miss, follows <c>_links[i]</c>; both arrays are touched but <c>_entries</c> is the dominant working
///set and the JIT keeps its reference hot across the loop.
///</para>
///
///<para><b>Alternative considered: Option D — split <c>LoEntry</c>/<c>HiEntry</c> types</b></para>
///<para>
///An obvious "fix" to the second-array fetch on collision walks is to inline the next-pointer into
///each entry, Dictionary-style. To keep the hi-region tight (the merit of the dual-region design),
///the natural answer is two distinct entry types in two arrays:
///</para>
///<code>
///struct LoEntry { uint next; K key; V value; }   // collision-chain elements
///struct HiEntry { K key; V value; }              // chain terminators
///LoEntry[] _loEntries; HiEntry[] _hiEntries;     // bucket value encodes region in its high bit
///</code>
///<para>
///This was prototyped and benchmarked. Result against the current design (random <c>int</c> keys at
///~78% load factor):
///</para>
///<list type="bullet">
///<item><c>Add</c>: +38% (good — chain walk during duplicate detection benefits from one less load).</item>
///<item><c>TryGet</c>: <b>-35%</b> (bad — every lookup pays a region-flag branch, mask/decode of the
///bucket value, and dispatches between two arrays even on the hot length-0/1 path).</item>
///<item><c>foreach</c>: -10% (walks two arrays instead of one).</item>
///</list>
///<para>
///<b>Why Option D was not selected:</b> with a well-distributed hash and a load factor &lt;= 0.75,
///roughly 82% of buckets are length 0 or 1, where the inlined-next saving buys nothing because there
///is no chain hop. Option D's overhead, however, is paid on every lookup. Real workloads are
///lookup-dominated and have rare collisions; the current design's tight hi-region entries plus a
///single shared <c>_entries</c> array win in that regime. Option D would only pay off on adversarial
///hash distributions or sustained load factor &gt; 0.85, neither of which is the target use case.
///</para>
///<para>
///For posterity: a forced-collision benchmark (keys whose hashes all map to one bucket) would expose
///Option D's chain-walk advantage and is the right diagnostic if the workload assumption ever changes.
///</para>
///
///<para><b>Benchmark vs <c>Dictionary&lt;int,int&gt;</c></b> (N = 100 000, random int keys, .NET 9, Release;
///median of 7–10 runs):</para>
///<code>
///Insert       Search          Get          Iterate       Delete       Churn   Insert(N)
///PrimitiveKeyMap&lt;int,int&gt;  46 210 721  189 035 917  157 625 707    1 529 051 988   55 000 000   61 195 230  111 204 664   ops/sec
///Dictionary                      1.10         0.65         0.74             0.85         0.85         0.76         0.73   x
///</code>
///<para><b>Memory profile (grow-from-empty Insert, 100 000 random int keys):</b>
///<list type="bullet">
///<item><c>PrimitiveKeyMap</c> allocates <b>36.71 B/op</b> (grow-from-empty Insert of 100 000 records)</item>
///<item><c>Dictionary</c> allocates <b>60.38 B/op</b></item>
///<item><c>PrimitiveKeyMap</c> saves <b>~23 664 B per 1 000 records</b> vs Dictionary</item>
///</list>
///</para>
///<para>
///Ratio &gt; 1 ⇒ <c>Dictionary</c> faster, &lt; 1 ⇒ <c>PrimitiveKeyMap</c> faster. PrimitiveKeyMap
///is 26–41% faster than Dictionary on every read path (Search/Get/Indexer), <b>~38% faster on
///pre-sized Insert</b> (Insert(N) column), and now beats Dictionary on Iterate, Delete, and Churn.
///The remaining ~10% gap on grow-from-empty Insert is structural: each Resize allocates three
///parallel arrays (<c>_buckets</c>, <c>_entries</c>, <c>_links</c>) where Dictionary allocates two,
///and Resize re-insertions write to two cache lines per entry (entry + link) where Dictionary's
///inline-<c>next</c> Entry hits one. The dual-region layout pays for that on Resize and recovers it
///many times over on every read. The chain-walk speed-up came from skipping JIT-emitted array-bounds
///checks (<c>Unsafe.Add</c> + <c>MemoryMarshal.GetArrayDataReference</c> on
///<c>_entries</c>/<c>_links</c>); the Resize speed-up came from hoisting <c>_buckets</c>,
///<c>_mask</c>, <c>_hiSize</c>, <c>_loSize</c> into locals so the per-entry rebuild loop runs
///entirely from registers, plus passing the precise <c>linksHint</c> to <c>Initialize</c> to size
///<c>_links</c> exactly once per Resize.
///</para>
///<para>See <c>Tests/Benchmarks/PrimitiveKeyMapBenchmark.cs</c> for the full scenarios and an HTML report.</para>
///</summary>
///<typeparam name="K">The unmanaged primitive key type.</typeparam>
///<typeparam name="V">The value type.</typeparam>
[DebuggerDisplay("Count = {Count}")]
public class PrimitiveKeyMap<K, V> : IDictionary<K, V>, IReadOnlyDictionary<K, V>
    where K : unmanaged
{
    private struct Entry
    {
        public K key;
        public V value;
    }

    private uint[]? _buckets;
    private Entry[]? _entries;
    private uint[]? _links; //0-based indices into _entries for collision chains.

    //The _entries array is split into two regions to optimize for non-colliding entries:
    //1. Lo-Region (indices 0 to _loSize-1): Stores entries that have caused a hash collision.
    //2. Hi-Region (indices _entries.Length - _hiSize to _entries.Length-1): Stores entries that have not caused a collision.
    private int _hiSize; //Number of active entries in the high region.
    private int _loSize; //Number of active entries in the low region.

    private int _version;
    private uint _mask;

    private KeysCollection? _keys;
    private ValuesCollection? _values;

    private const int DefaultCapacity = 4;

    public PrimitiveKeyMap() : this(0) {}

    public PrimitiveKeyMap(int capacity)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(capacity);
        if (capacity > 0)
            Initialize(capacity);
    }

    public PrimitiveKeyMap(IEnumerable<KeyValuePair<K, V>> collection) : this(collection is ICollection<KeyValuePair<K, V>> coll ? coll.Count : 0)
    {
        ArgumentNullException.ThrowIfNull(collection);
        AddRange(collection);
    }

    public PrimitiveKeyMap(IDictionary<K, V> dictionary) : this(dictionary?.Count ?? 0)
    {
        ArgumentNullException.ThrowIfNull(dictionary);
        AddRange(dictionary);
    }

    private void AddRange(IEnumerable<KeyValuePair<K, V>> enumerable)
    {
        foreach (var pair in enumerable)
            Add(pair.Key, pair.Value);
    }

    public int Count
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => _loSize + _hiSize;
    }

    public bool IsReadOnly => false;

    public V this[K key]
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            ref var entry = ref FindEntry(key);
            if (Unsafe.IsNullRef(ref entry))
                throw new KeyNotFoundException("The given key was not present in the map.");
            return entry.value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => TryInsert(key, value, true);
    }

    public void Add(K key, V value)
    {
        if (!TryInsert(key, value, false))
            throw new ArgumentException("An item with the same key has already been added.");
    }

    void ICollection<KeyValuePair<K, V>>.Add(KeyValuePair<K, V> item) => TryInsert(item.Key, item.Value, true);

    ///<summary>Attempts to add the specified key and value. Returns false if the key already exists.</summary>
    ///<remarks>Native implementation. Avoids the BCL <c>IDictionary&lt;K,V&gt;</c> extension method's
    ///double dispatch (ContainsKey + Add).</remarks>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool TryAdd(K key, V value) => TryInsert(key, value, false);

    ///<summary>
    ///Internal entry-finder. Returns a ref to the entry on hit, or a null ref on miss.
    ///AggressiveInlining so callers (TryGetValue, ContainsKey, indexer) inline the body — the
    ///indexer was 4× slower than direct TryGetValue without this fix.
    ///</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private ref Entry FindEntry(K key)
    {
        if (_loSize + _hiSize == 0)
            return ref Unsafe.NullRef<Entry>();

        var i = (int)GetBucket((uint)key.GetHashCode()) - 1;
        if (i == -1)
            return ref Unsafe.NullRef<Entry>();

        ref var entry = ref _entries![i];
        for (var collisions = 0; !EqualityComparer<K>.Default.Equals(entry.key, key); entry = ref _entries![i = (int)_links![i]])
        {
            if (_loSize <= i)
                return ref Unsafe.NullRef<Entry>();
            if (_loSize < ++collisions)
                throw new InvalidOperationException("Hash collision chain is unexpectedly long. Possible data corruption.");
        }

        return ref entry;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private bool TryInsert(K key, V value, bool overwrite)
    {
        if (_buckets == null)
            Initialize(DefaultCapacity);

        var entries = _entries!;
        if (entries.Length <= _loSize + _hiSize)
        {
            Resize(entries.Length * 2);
            entries = _entries!;
        }

        ref var bucket = ref GetBucket((uint)key.GetHashCode());
        ref var entries0 = ref MemoryMarshal.GetArrayDataReference(entries);

        int dstIndex;
        if (bucket == 0)
            dstIndex = entries.Length - 1 - _hiSize++; //Empty bucket → place in hi-region.
        else
        {
            //Cache links0 only for the read-only chain walk. The post-walk lo-insert may
            //call Array.Resize(ref _links, ...) which would invalidate this ref, so the
            //write below uses the _links! field directly.
            ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
            var loSize = _loSize;
            for (uint i = bucket - 1, collisions = 0;;)
            {
                ref var entry = ref Unsafe.Add(ref entries0, i);
                if (EqualityComparer<K>.Default.Equals(entry.key, key))
                {
                    if (!overwrite)
                        return false;
                    entry.value = value;
                    _version++;
                    return false;
                }

                if (loSize <= i)
                    break; //Reached hi-region terminator without match.
                i = Unsafe.Add(ref links0, i);
                if (loSize + 1 < collisions++)
                    throw new InvalidOperationException("Concurrent operations not supported.");
            }

            //Push new entry on chain head in lo-region.
            if (_links!.Length == (dstIndex = _loSize++))
                Array.Resize(ref _links, Math.Max(16, Math.Min(_buckets!.Length, _links.Length * 2)));
            _links[dstIndex] = bucket - 1;
        }

        ref var newEntry = ref Unsafe.Add(ref entries0, dstIndex);
        newEntry.key = key;
        newEntry.value = value;
        bucket = (uint)(dstIndex + 1);
        _version++;
        return true;
    }

    public ICollection<K> Keys => _keys ??= new KeysCollection(this);
    public ICollection<V> Values => _values ??= new ValuesCollection(this);

    IEnumerable<K> IReadOnlyDictionary<K, V>.Keys => Keys;
    IEnumerable<V> IReadOnlyDictionary<K, V>.Values => Values;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private ref uint GetBucket(uint hashCode) => ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_buckets!), hashCode &_mask);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private int Initialize(int capacity, int linksHint = 16)
    {
        _version++;
        var size = GetPowerOfTwo(capacity);
        _buckets = new uint[size];
        _entries = new Entry[size];
        _links = new uint[Math.Min(size, linksHint)];
        _loSize = _hiSize = 0;
        _mask = (uint)(size - 1);
        return size;
    }

    public void Clear()
    {
        if (Count == 0)
            return;
        _version++;
        if (_buckets != null)
            Array.Clear(_buckets, 0, _buckets.Length);
        _loSize = 0;
        _hiSize = 0;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool ContainsKey(K key) => !Unsafe.IsNullRef(ref FindEntry(key));

    public bool ContainsValue(V value)
    {
        //Iterate lo-region
        for (var i = 0; i < _loSize; i++)
            if (EqualityComparer<V>.Default.Equals(_entries![i].value, value))
                return true;
        if (_hiSize == 0)
            return false;

        //Iterate hi-region
        for (var i = _entries!.Length - _hiSize; i < _entries.Length; i++)
            if (EqualityComparer<V>.Default.Equals(_entries![i].value, value))
                return true;

        return false;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool TryGetValue(K key, [MaybeNullWhen(false)] out V value)
    {
        ref var entry = ref FindEntry(key);
        if (Unsafe.IsNullRef(ref entry))
        {
            value = default;
            return false;
        }

        value = entry.value;
        return true;
    }

    ///<summary>
    ///Gets a reference to the value associated with the specified key, adding a provided default value if the key does not exist.
    ///</summary>
    ///<param name="key">The key to search for.</param>
    ///<param name="defaultValue">The value to add if the key does not exist.</param>
    ///<param name="exists">When this method returns, contains <c>true</c> if the key already existed; otherwise, <c>false</c>.</param>
    ///<returns>A reference to the value associated with the specified key.</returns>
    ///<remarks>
    ///Note: Do not add or remove items from the map while holding this reference, as triggering a resize of the internal arrays will invalidate it.
    ///</remarks>
    public ref V GetValueRefOrAddDefault(K key, V defaultValue, out bool exists)
    {
        if (_buckets == null)
            Initialize(DefaultCapacity);

        var entries = _entries!;
        if (entries.Length <= _loSize + _hiSize)
        {
            Resize(entries.Length * 2);
            entries = _entries!;
        }

        ref var bucket = ref GetBucket((uint)key.GetHashCode());
        ref var entries0 = ref MemoryMarshal.GetArrayDataReference(entries);

        int dstIndex;
        if (bucket == 0)
            dstIndex = entries.Length - 1 - _hiSize++;
        else
        {
            //Cache links0 only for the read-only chain walk. Post-walk insert may
            //Array.Resize(_links) and invalidate this ref, so the write uses _links! directly.
            ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
            var loSize = _loSize;
            for (uint i = bucket - 1, collisions = 0;;)
            {
                ref var entry = ref Unsafe.Add(ref entries0, i);
                if (EqualityComparer<K>.Default.Equals(entry.key, key))
                {
                    exists = true;
                    return ref entry.value;
                }

                if (loSize <= i)
                    break;
                i = Unsafe.Add(ref links0, i);
                if (loSize + 1 < collisions++)
                    throw new InvalidOperationException("Concurrent operations not supported.");
            }

            if (_links!.Length == (dstIndex = _loSize++))
                Array.Resize(ref _links, Math.Max(16, Math.Min(_buckets!.Length, _links.Length * 2)));
            _links[dstIndex] = bucket - 1;
        }

        ref var newEntry = ref Unsafe.Add(ref entries0, dstIndex);
        newEntry.key = key;
        newEntry.value = defaultValue;
        bucket = (uint)(dstIndex + 1);
        _version++;
        exists = false;
        return ref newEntry.value;
    }

    ///<summary>
    ///Rebuilds the table at <paramref name="newSize"/>, re-inserting every old entry.
    ///<para>
    ///<b>Memory win — pre-size <c>_links</c> once.</b> The previous implementation called a per-entry
    ///<c>Copy</c> helper that doubled <c>_links</c> from 16 → 32 → 64 → … → roundUpPowerOf2(N) as
    ///entries streamed in. For a Resize that re-inserts ~75 000 lo-entries (typical at 100k load),
    ///that's ~13 <c>Array.Resize</c> calls allocating cumulatively <b>~1 MB</b> of arrays that all
    ///become garbage, plus the final ~512 KB kept array. By passing the precise <c>linksHint</c> to
    ///<c>Initialize</c>, we make <b>zero</b> intermediate allocations and the kept array is right-sized.
    ///</para>
    ///<para><b>Speed win — hoist hot fields.</b> The per-entry rebuild loop reads <c>_buckets</c>,
    ///<c>_mask</c>, <c>_hiSize</c>, <c>_loSize</c> on every iteration. The JIT cannot hoist them across
    ///the <c>_hiSize++</c>/<c>_loSize++</c> writes (it cannot prove the writes don't alias other field
    ///loads), so they compile to repeated memory loads. We hoist them into locals (<c>buckets0</c>,
    ///<c>mask</c>, <c>hiSize</c>, <c>loSize</c>) and write back at the end. Combined with cached
    ///<c>Unsafe.Add</c> refs and no JIT bounds checks, the loop body reduces to register-only work plus
    ///the unavoidable hash + memory writes.</para>
    ///</summary>
    private int Resize(int newSize)
    {
        _version++;
        var oldEntries = _entries;
        var oldLoSize = _loSize;
        var oldHiSize = _hiSize;
        var oldEnd = oldEntries!.Length;
        var oldHiStart = oldEnd - oldHiSize;

        //Pass the precise linksHint so Initialize sizes _links to fit all surviving entries
        //worst-case (every old entry could re-collide into lo). No throwaway 16-element alloc.
        var totalEntries = oldLoSize + oldHiSize;
        Initialize(newSize, totalEntries);

        ref var oldEntries0 = ref MemoryMarshal.GetArrayDataReference(oldEntries);
        ref var entries0 = ref MemoryMarshal.GetArrayDataReference(_entries!);
        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        ref var buckets0 = ref MemoryMarshal.GetArrayDataReference(_buckets!);
        var mask = _mask;
        var newEnd = _entries!.Length;
        var loSize = 0;
        var hiSize = 0;

        //Re-insert lo region [0..oldLoSize)
        for (var i = 0; i < oldLoSize; i++)
        {
            ref var entry = ref Unsafe.Add(ref oldEntries0, i);
            ref var bucket = ref Unsafe.Add(ref buckets0, (nint)((uint)entry.key.GetHashCode() & mask));
            var prev = (int)bucket - 1;
            int dstIndex;

            if (prev == -1)
                dstIndex = newEnd - 1 - hiSize++;
            else
            {
                dstIndex = loSize++; //pre-sized: never resizes here
                Unsafe.Add(ref links0, dstIndex) = (uint)prev;
            }

            Unsafe.Add(ref entries0, dstIndex) = entry;
            bucket = (uint)(dstIndex + 1);
        }

        //Re-insert hi region [oldHiStart..oldEnd)
        for (var i = oldHiStart; i < oldEnd; i++)
        {
            ref var entry = ref Unsafe.Add(ref oldEntries0, i);
            ref var bucket = ref Unsafe.Add(ref buckets0, (nint)((uint)entry.key.GetHashCode() & mask));
            var prev = (int)bucket - 1;
            int dstIndex;

            if (prev == -1)
                dstIndex = newEnd - 1 - hiSize++;
            else
            {
                dstIndex = loSize++;
                Unsafe.Add(ref links0, dstIndex) = (uint)prev;
            }

            Unsafe.Add(ref entries0, dstIndex) = entry;
            bucket = (uint)(dstIndex + 1);
        }

        _loSize = loSize;
        _hiSize = hiSize;
        return newSize;
    }

    //Moves data from src index to dst index and updates all links pointing to src.
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void Move(int src, int dst, ref Entry dstEntry)
    {
        //Move is private and called only from Remove (three sites). Centralizing the
        //version bump here removes the duplicated `_version++` from each Remove branch
        //and still bumps once per Remove (including the src == dst early-return case).
        _version++;
        if (src == dst)
            return;

        //Skip the array-bounds checks: src < _entries.Length and the chain-walked
        //indices are bounded by the same. Same trick the BCL uses internally.
        ref var entries0 = ref MemoryMarshal.GetArrayDataReference(_entries!);
        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        ref var srcEntry = ref Unsafe.Add(ref entries0, src);
        ref var srcBucket = ref GetBucket((uint)srcEntry.key.GetHashCode());
        var index = (int)srcBucket - 1;

        if (index == src)
            srcBucket = (uint)(dst + 1);
        else
        {
            ref var link = ref Unsafe.Add(ref links0, index);
            while (link != src)
            {
                index = (int)link;
                link = ref Unsafe.Add(ref links0, index);
            }

            link = (uint)dst;
        }

        if (src < _loSize)
            Unsafe.Add(ref links0, dst) = Unsafe.Add(ref links0, src);

        dstEntry = srcEntry;
    }

    ///<summary>
    ///Removes <paramref name="key"/> if present.
    ///<para>Index-based chain walk (no <c>ref</c> aliasing across iterations) so the JIT can keep
    ///the loop in registers. Tracks the immediate predecessor (<c>prev</c>) and pre-predecessor
    ///(<c>prevPrev</c>) so the hi-terminator migration case rewires the back-pointer in O(1).
    ///Hot fields (<c>_entries</c>, <c>_links</c>, <c>_loSize</c>) are hoisted into locals.</para>
    ///</summary>
    public bool Remove(K key)
    {
        if (_loSize + _hiSize == 0)
            return false;

        ref var bucket = ref GetBucket((uint)key.GetHashCode());
        var idx = (int)bucket - 1;
        if (idx < 0)
            return false;

        var loSize = _loSize;
        ref var entries0 = ref MemoryMarshal.GetArrayDataReference(_entries!);

        //Chain length 1 (entry sits in hi as the original empty-bucket placement).
        ref var e = ref Unsafe.Add(ref entries0, idx);
        if (loSize <= idx)
        {
            if (!EqualityComparer<K>.Default.Equals(e.key, key))
                return false;
            Move(_entries!.Length - _hiSize, idx, ref e);
            _hiSize--;
            bucket = 0;
            return true;
        }

        ref var links0 = ref MemoryMarshal.GetArrayDataReference(_links!);
        var prev = -1;
        var prevPrev = -1;

        for (var collisions = 0;
             !EqualityComparer<K>.Default.Equals(e.key, key);
             prevPrev = prev,
                 e = ref Unsafe.Add(ref entries0, idx = (int)Unsafe.Add(ref links0, prev = idx)))
        {
            if (idx >= loSize)
                return false;
            if (++collisions > loSize)
                throw new InvalidOperationException("Hash collision chain is unexpectedly long. Possible data corruption.");
        }

        var lastLo = loSize - 1;
        if (idx < loSize)
        {
            //Standard removal: rewire (prev or bucket) → next; compact lo by swap-with-last.
            //Single read of the matched entry's link; both branches consume `next`.
            var next = Unsafe.Add(ref links0, idx);
            if (prev < 0)
                bucket = next + 1;
            else
                Unsafe.Add(ref links0, prev) = next;
            Move(lastLo, idx, ref e);
        }
        else
        {
            //Found at hi-terminator with chain length ≥ 2. Migrate prev (lo) into the hi slot
            //so the chain still terminates in hi; prev's lo slot becomes the hole.
            ref var prevEntry = ref Unsafe.Add(ref entries0, prev);
            e = prevEntry;
            if (prevPrev < 0)
                bucket = (uint)(idx + 1);
            else
                Unsafe.Add(ref links0, prevPrev) = (uint)idx;
            Move(lastLo, prev, ref prevEntry);
        }

        _loSize = lastLo;
        return true;
    }

    bool ICollection<KeyValuePair<K, V>>.Remove(KeyValuePair<K, V> item) => TryGetValue(item.Key, out var value) && EqualityComparer<V>.Default.Equals(value, item.Value) && Remove(item.Key);

    bool ICollection<KeyValuePair<K, V>>.Contains(KeyValuePair<K, V> item) { return TryGetValue(item.Key, out var value) && EqualityComparer<V>.Default.Equals(value, item.Value); }

    void ICollection<KeyValuePair<K, V>>.CopyTo(KeyValuePair<K, V>[] dst, int dstIndex)
    {
        ArgumentNullException.ThrowIfNull(dst);
        ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual((uint)dstIndex, (uint)dst.Length);
        if (dst.Length - dstIndex < Count)
            throw new ArgumentException("Destination array is not long enough.");

        //Copy lo-region
        for (var i = 0; i < _loSize; i++)
        {
            ref var entry = ref _entries![i];
            dst[dstIndex++] = new KeyValuePair<K, V>(entry.key, entry.value);
        }

        if (_hiSize == 0)
            return;

        //Copy hi-region
        for (var i = _entries!.Length - _hiSize; i < _entries.Length; i++)
        {
            ref var entry = ref _entries[i];
            dst[dstIndex++] = new KeyValuePair<K, V>(entry.key, entry.value);
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static int GetPowerOfTwo(int capacity) => capacity <= DefaultCapacity ? DefaultCapacity : (int)BitOperations.RoundUpToPowerOf2((uint)capacity);

    public Enumerator GetEnumerator() => new(this);
    IEnumerator<KeyValuePair<K, V>> IEnumerable<KeyValuePair<K, V>>.GetEnumerator() => GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

    public struct Enumerator : IEnumerator<KeyValuePair<K, V>>
    {
        //Snapshot the layout at construction so MoveNext only reads instance fields when
        //version-checking. Field reads on a heap object cost a load + a possible cache miss
        //per call; locals stay in registers across the iteration.
        private readonly PrimitiveKeyMap<K, V> _map;
        private readonly Entry[]? _entries;
        private readonly int _loEnd;
        private readonly int _hiStart;
        private readonly int _hiEnd;
        private readonly int _version;
        private int _index; //-1 = not started, -2 = finished, else current index
        private KeyValuePair<K, V> _current;

        internal Enumerator(PrimitiveKeyMap<K, V> map)
        {
            _map = map;
            _version = map._version;
            _entries = map._entries;
            _loEnd = map._loSize;
            _hiEnd = _entries?.Length ?? 0;
            _hiStart = _hiEnd - map._hiSize;
            _index = -1;
            _current = default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool MoveNext()
        {
            if (_version != _map._version)
                throw new InvalidOperationException("Collection was modified during enumeration.");
            if (_index == -2)
                return false; //already finished — calling MoveNext again is allowed and must keep returning false

            var i = _index + 1;
            if (i == _loEnd)
                i = _hiStart;
            if (i >= _hiEnd)
            {
                _index = -2;
                return false;
            }

            //Skip the array-bounds check: we just verified i < _hiEnd ≤ _entries.Length,
            //so the JIT-generated bounds check on _entries![i] is provably redundant.
            ref var entry = ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_entries!), i);
            _current = new KeyValuePair<K, V>(entry.key, entry.value);
            _index = i;
            return true;
        }

        //BCL Dictionary semantics: bare field read, no per-access checks.
        //Concurrent-modification detection lives in MoveNext.
        public KeyValuePair<K, V> Current
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _current;
        }

        object? IEnumerator.Current => Current;

        public void Reset()
        {
            if (_version != _map._version)
                throw new InvalidOperationException("Collection was modified during enumeration.");
            _index = -1;
            _current = default;
        }

        public void Dispose() {}
    }

    public int EnsureCapacity(int capacity)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(capacity);
        var currentCapacity = _entries?.Length ?? 0;
        if (currentCapacity >= capacity)
            return currentCapacity;
        _version++;
        if (_buckets == null)
            return Initialize(capacity);
        var newSize = GetPowerOfTwo(capacity);
        Resize(newSize);
        return newSize;
    }

    public void TrimExcess()
    {
        var count = Count;
        if (count == 0)
        {
            Initialize(0);
            return;
        }

        if (_entries == null)
            return;
        var newSize = GetPowerOfTwo(count);
        if (newSize < _entries.Length)
            Resize(newSize);
    }
#region Helper Collections
    [DebuggerDisplay("Count = {Count}")]
    public sealed class KeysCollection : ICollection<K>, IReadOnlyCollection<K>
    {
        private readonly PrimitiveKeyMap<K, V> map;
        public KeysCollection(PrimitiveKeyMap<K, V> map) => this.map = map;
        public int Count => map.Count;
        public bool IsReadOnly => true;

        public void CopyTo(K[] dst, int dstIndex)
        {
            ArgumentNullException.ThrowIfNull(dst);
            ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual((uint)dstIndex, (uint)dst.Length);
            if (dst.Length - dstIndex < Count)
                throw new ArgumentException("Destination array is not long enough.");

            foreach (var item in map)
                dst[dstIndex++] = item.Key;
        }

        public bool Contains(K item) => map.ContainsKey(item);
        public Enumerator GetEnumerator() => new(map);
        IEnumerator<K> IEnumerable<K>.GetEnumerator() => GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
        void ICollection<K>.Add(K item) => throw new NotSupportedException();
        bool ICollection<K>.Remove(K item) => throw new NotSupportedException();
        void ICollection<K>.Clear() => throw new NotSupportedException();

        public struct Enumerator : IEnumerator<K>
        {
            private PrimitiveKeyMap<K, V>.Enumerator _dictEnumerator;
            internal Enumerator(PrimitiveKeyMap<K, V> map) => _dictEnumerator = map.GetEnumerator();
            public bool MoveNext() => _dictEnumerator.MoveNext();
            public K Current => _dictEnumerator.Current.Key;
            object? IEnumerator.Current => Current;
            public void Dispose() => _dictEnumerator.Dispose();
            public void Reset() => _dictEnumerator.Reset();
        }
    }

    [DebuggerDisplay("Count = {Count}")]
    public sealed class ValuesCollection : ICollection<V>, IReadOnlyCollection<V>
    {
        private readonly PrimitiveKeyMap<K, V> map;
        public ValuesCollection(PrimitiveKeyMap<K, V> map) => this.map = map;
        public int Count => map.Count;
        public bool IsReadOnly => true;

        public void CopyTo(V[] dst, int dstIndex)
        {
            ArgumentNullException.ThrowIfNull(dst);
            ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual((uint)dstIndex, (uint)dst.Length);
            if (dst.Length - dstIndex < Count)
                throw new ArgumentException("Destination array is not long enough.");

            foreach (var item in map)
                dst[dstIndex++] = item.Value;
        }

        public bool Contains(V item) => map.ContainsValue(item);

        public Enumerator GetEnumerator() => new(map);
        IEnumerator<V> IEnumerable<V>.GetEnumerator() => GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
        void ICollection<V>.Add(V item) => throw new NotSupportedException();
        bool ICollection<V>.Remove(V item) => throw new NotSupportedException();
        void ICollection<V>.Clear() => throw new NotSupportedException();

        public struct Enumerator : IEnumerator<V>
        {
            private PrimitiveKeyMap<K, V>.Enumerator _dictEnumerator;
            internal Enumerator(PrimitiveKeyMap<K, V> map) => _dictEnumerator = map.GetEnumerator();
            public bool MoveNext() => _dictEnumerator.MoveNext();
            public V Current => _dictEnumerator.Current.Value;
            object? IEnumerator.Current => Current;
            public void Dispose() => _dictEnumerator.Dispose();
            public void Reset() => _dictEnumerator.Reset();
        }
    }
#endregion
}