//Copyright 2025 Chikirev Sirguy, Unirail Group. All rights reserved.
//
//This file is part of the AdHoc protocol runtime library.
//
//Licensed under the PolyForm Shield License 1.0.0. The full text is distributed with this
//file as LICENSE.md and is published at https://polyformproject.org/licenses/shield/1.0.0
//
//In short: you may use, modify and distribute this software for any purpose, except to
//provide a product that competes with the software, or with any product the licensor
//provides using the software. Competition is judged by function, not by form.
//
//The plain-text notice lines the license requires you to pass on - the Required Notice and
//the Licensor Line of Business - are in the NOTICE file distributed with this library.
//Keep LICENSE.md and NOTICE with any copy of this software that you distribute.
//
//Code generated by the AdHoc generator is NOT part of the Licensed Work and carries no
//restrictions whatsoever - see the header of any generated file.
//
//Provided as is, without any warranty or condition.
//
//Commercial licenses that remove the noncompete restriction are available.
//For licensing and inquiries: al8v5C6HU4UtqE9@gmail.com

using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;

namespace org.unirail.collections;

///<summary>The head and the tail of a <see cref="RingBuffer{T}"/>, each alone on a cache line - padded on both sides,
///whatever the runtime lays out around the struct - as <c>PaddedHeadAndTail</c> of .NET's <c>ConcurrentQueue</c>: 128
///bytes, the line of Apple silicon and the pair of lines Intel's spatial prefetcher fetches together. Not nested in the
///generic class: a type nested in a generic one is generic, and the runtime refuses an explicit layout to generics.</summary>
[StructLayout(LayoutKind.Explicit, Size = 3 * 128)]
internal struct PaddedHeadAndTail
{
    [FieldOffset(128)]
    public ulong Head;
    [FieldOffset(256)]
    public ulong Tail;
}

///<summary>
///A fixed-size queue for any number of producers and consumers (MPMC), without a lock: Dmitry Vyukov's bounded MPMC queue
///(https://www.1024cores.net/home/lock-free-algorithms/queues/bounded-mpmc-queue), as the segments of .NET's
///<c>ConcurrentQueue</c> have it. Every member is thread-safe; nothing is allocated.
///</summary>
///<remarks>
///<para>Each slot carries a sequence number that says whose turn it is - the producer of lap <c>n</c> or its consumer - so
///a put is one CAS on the tail, a take one CAS on the head, and a value is taken only once it is written.</para>
///<para><see cref="TryGet"/>, <see cref="TryPut"/> and <see cref="PutPosition"/> never wait: a slot its producer has
///claimed and not yet written reads as empty, a slot its consumer has claimed and not yet released reads as full. A
///producer that finds the head on the position its put took (<see cref="PutPosition"/> <c>==</c> <see cref="Head"/>)
///knows the consumer found the queue empty or passed its value by, and wakes it - the transmit queue of a connection
///works so. <see cref="Clear()"/> waits for a value its producer is writing: nothing is left behind when a queue is
///emptied for good.</para>
///<para>The same queue as <c>org.unirail.collections.RingBuffer</c> of the Java runtime, in the idiom of .NET: <c>Try</c>
///methods with an <c>out</c> value, so that an empty queue of a value type is not mistaken for a default value.</para>
///<para>Against <c>ConcurrentQueue&lt;object&gt;</c> (.NET 10, i9-13900HX P-cores, M operations a second, the best of 3):</para>
///<code>
///RingBuffer (1024)    ConcurrentQueue
///1 thread, put + get                95                  85
///4 producers, 1 consumer            8.0 - 8.6           8.5 - 9.1   and 0.5 - 1 MB allocated
///4 producers, 4 consumers           8.0 - 8.8           8.6 - 9.0   and 0.5 - 8 MB allocated
///1 producer, 1 consumer            14                  33 - 55      and 150 MB allocated
///</code>
///<para>Many producers - a transmit queue - run as fast, with nothing allocated. One producer outruns one consumer in
///<c>ConcurrentQueue</c> by growing it without end - 10 million values ahead, 150 MB - which a bounded queue must not do:
///a full one refuses, and its producer waits.</para>
///</remarks>
///<typeparam name="T">The type of the values.</typeparam>
public class RingBuffer<T>
{
    ///<summary>What <see cref="PutPosition"/> returns when the queue is full.</summary>
    public const ulong FULL = ulong.MaxValue;

    //the slots: a value and its turn side by side, in one cache line - as the Slot of ConcurrentQueue's segments. In two
    //arrays each operation touched two lines, both moving between the cores (1 producer to 1 consumer: 13.6 against 15.7 M/s).
    readonly Slot[] _slots;

    struct Slot
    {
        public T Item; //cleared when taken if T holds references: the queue keeps nothing it gave away alive

        //the turn: slot i of lap n is free for the put of position i + n * Length when it equals that position, and holds
        //its value for the take of that position when it equals the position + 1
        public ulong Sequence;
    }

    readonly ulong _mask;

    //the position of the next take and of the next put, each on a cache line of its own
    PaddedHeadAndTail _positions;

    ///<summary>A queue of 2<sup><paramref name="capacityPowerOfTwo"/></sup> values.</summary>
    ///<exception cref="ArgumentOutOfRangeException"><paramref name="capacityPowerOfTwo"/> is negative or above 30.</exception>
    public RingBuffer(int capacityPowerOfTwo)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(capacityPowerOfTwo);
        ArgumentOutOfRangeException.ThrowIfGreaterThan(capacityPowerOfTwo, 30);
        var capacity = 1 << capacityPowerOfTwo;
        _mask = (ulong)(capacity - 1);
        _slots = new Slot[capacity];
        for (var i = 0; i < capacity; i++)
            _slots[i].Sequence = (ulong)i;
    }

    ///<summary>The capacity: how many values the queue holds at most.</summary>
    public int Length => _slots.Length;

    ///<summary>How many values are in the queue: a snapshot, stale once other threads move on.</summary>
    public int Size
    {
        get {
            var head = Volatile.Read(ref _positions.Head); //before the tail: puts in between make it larger, never negative
            var tail = Volatile.Read(ref _positions.Tail);
            return head < tail ? (int)Math.Min(tail - head, (ulong)_slots.Length) : 0;
        }
    }

    ///<summary>No value in the queue: a snapshot.</summary>
    public bool IsEmpty => Volatile.Read(ref _positions.Tail) <= Volatile.Read(ref _positions.Head);

    ///<summary>No room in the queue: a snapshot.</summary>
    public bool IsFull => Size == _slots.Length;

    ///<summary>The position of the next take: compared with what <see cref="PutPosition"/> returned, it tells a producer
    ///that the consumer is to be woken.</summary>
    public ulong Head => Volatile.Read(ref _positions.Head);

    ///<summary>Takes the value at the head. Never waits.</summary>
    ///<param name="value">The value taken; <c>default</c> when there is none.</param>
    ///<returns><c>false</c>: the queue is empty - or the value at its head is claimed by a producer and not yet written,
    ///and that producer wakes the consumer once it is (see <see cref="PutPosition"/>).</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool TryGet([MaybeNullWhen(false)] out T value)
    {
        var pos = Claim(false);
        if (pos == FULL)
        {
            value = default;
            return false;
        }
        value = Take(pos);
        return true;
    }

    ///<summary>Takes the value at the head, as <see cref="TryGet"/>: for a queue of references, where <c>null</c> means
    ///"nothing". Never waits.</summary>
    ///<returns>The value taken, or <paramref name="empty"/>.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public T? Get(T? empty = default) => TryGet(out var value) ? value : empty;

    ///<summary>Puts <paramref name="value"/> at the tail. Never waits.</summary>
    ///<returns><c>false</c>: the queue is full.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool TryPut(T value) => PutPosition(value) != FULL;

    ///<summary>Puts <paramref name="value"/> at the tail, as <see cref="TryPut"/>, and tells the position it took.
    ///Never waits.</summary>
    ///<returns>The position of the value - when <see cref="Head"/> equals it after the put, the consumer found the queue
    ///empty or passed the value by while it was being written, and is to be woken - or <see cref="FULL"/>.</returns>
    public ulong PutPosition(T value)
    {
        ref var slots = ref MemoryMarshal.GetArrayDataReference(_slots);
        for (;;)
        {
            var pos = Volatile.Read(ref _positions.Tail);
            ref var slot = ref Unsafe.Add(ref slots, (nint)(pos & _mask));
            var dif = (long)(Volatile.Read(ref slot.Sequence) - pos);
            if (dif == 0)
            {
                if (Interlocked.CompareExchange(ref _positions.Tail, pos + 1, pos) != pos)
                    continue; //another producer took this position: try the next
                slot.Item = value;
                Volatile.Write(ref slot.Sequence, pos + 1); //a release: the value is seen with the sequence
                return pos;
            }
            if (dif < 0)
                return FULL; //the slot holds the value of the lap before, or its consumer has not released it yet
            //else another producer took this position: try the next
        }
    }

    ///<summary>Takes and drops every value there is.</summary>
    ///<returns>This queue.</returns>
    public RingBuffer<T> Clear()
    {
        for (ulong pos; (pos = Claim(true)) != FULL;)
            Take(pos);
        return this;
    }

    ///<summary>Takes every value there is and hands each to <paramref name="onClear"/>, oldest first.</summary>
    ///<remarks>A slot is emptied and freed before its value is handed on: <paramref name="onClear"/> may throw or take its
    ///time without holding the producers up. A value it puts into this queue is taken again: it must not.</remarks>
    ///<returns>This queue.</returns>
    public RingBuffer<T> Clear(Action<T> onClear)
    {
        for (ulong pos; (pos = Claim(true)) != FULL;)
            onClear(Take(pos));
        return this;
    }

    ///<summary>As <see cref="Clear(Action{T})"/>, with a state of the caller's. With a <c>static</c> lambda nothing is
    ///allocated: no closure, and the delegate is cached by the compiler.</summary>
    ///<returns>This queue.</returns>
    public RingBuffer<T> Clear<S>(S state, Action<S, T> onClear)
    {
        for (ulong pos; (pos = Claim(true)) != FULL;)
            onClear(state, Take(pos));
        return this;
    }

    public override string ToString() => $"RingBuffer{{Length={Length}, Size={Size}, Head={Volatile.Read(ref _positions.Head)}, Tail={Volatile.Read(ref _positions.Tail)}}}";

    ///<summary>Moves the head on by one.</summary>
    ///<param name="wait">Wait for a producer that has claimed the slot at the head and not yet written it.</param>
    ///<returns>The position taken, or <see cref="FULL"/>: nothing to take - empty (or, without <paramref name="wait"/>, not
    ///yet written).</returns>
    ulong Claim(bool wait)
    {
        ref var slots = ref MemoryMarshal.GetArrayDataReference(_slots);
        var spinner = new SpinWait();
        for (;;)
        {
            var pos = Volatile.Read(ref _positions.Head);
            var dif = (long)(Volatile.Read(ref Unsafe.Add(ref slots, (nint)(pos & _mask)).Sequence) - (pos + 1));
            if (dif == 0)
            {
                if (Interlocked.CompareExchange(ref _positions.Head, pos + 1, pos) == pos)
                    return pos;
                continue; //another consumer took this position: try the next
            }
            if (dif < 0)
            {
                if (!wait || Volatile.Read(ref _positions.Tail) <= pos)
                    return FULL;      //empty
                spinner.SpinOnce(-1); //claimed by a producer that is writing it: a few instructions away
            }
            //else another consumer took this position: try the next
        }
    }

    ///<summary>Reads the value at a claimed position and frees its slot for the next lap.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    T Take(ulong pos)
    {
        ref var slot = ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_slots), (nint)(pos & _mask));
        var value = slot.Item;
        if (RuntimeHelpers.IsReferenceOrContainsReferences<T>())
            slot.Item = default!;                                      //a JIT-time constant: nothing written for values without references
        Volatile.Write(ref slot.Sequence, pos + (ulong)_slots.Length); //a release: the read above comes first
        return value;
    }
}
