//Copyright 2025 Chikirev Sirguy, Unirail Group. All rights reserved.
//
//This file is part of the AdHoc protocol runtime library.
//
//Licensed under the PolyForm Shield License 1.0.0. The full text is distributed with this
//file as LICENSE.md and is published at https://polyformproject.org/licenses/shield/1.0.0
//
//In short: you may use, modify and distribute this software for any purpose, except to
//provide a product that competes with the software, or with any product the licensor
//provides using the software. Competition is judged by function, not by form.
//
//The plain-text notice lines the license requires you to pass on - the Required Notice and
//the Licensor Line of Business - are in the NOTICE file distributed with this library.
//Keep LICENSE.md and NOTICE with any copy of this software that you distribute.
//
//Code generated by the AdHoc generator is NOT part of the Licensed Work and carries no
//restrictions whatsoever - see the header of any generated file.
//
//Provided as is, without any warranty or condition.
//
//Commercial licenses that remove the noncompete restriction are available.
//For licensing and inquiries: al8v5C6HU4UtqE9@gmail.com

//ChaCha20 stream-cipher stages for org.unirail.AdHoc streams (RFC 8439). A pluggable inner stage between the
//outer framer (Receiver/Transmitter.Chunked) and what it wraps: the transmit side XOR-encrypts freshly-written
//plaintext in place, the receive side XOR-decrypts each de-framed chunk into a scratch buffer. Compose it like
//any other stage; for compress-then-encrypt place it OUTSIDE (toward the wire) of the Zstd stage.
//
//─ Properties ───────────────────────────────────────────────────────────────
//  • Length-preserving — encrypt and decrypt are the same keystream XOR, so the stage neither adds nor removes
//    bytes and is valid under the `File` framer (which declares its size at Init) as well as `Chunked`.
//  • Pure managed, no native/unsafe code. The bulk keystream is a hardware-SIMD core (AVX-512 16-block → AVX2
//    8-block → scalar) using safe System.Runtime.Intrinsics types; the IsSupported / endianness guards fold at
//    JIT time, so a CPU or platform without a tier drops to the next one, down to the portable scalar path.
//  • Key material is folded into the state on Init and not retained.
//
//─ SECURITY (read this) ──────────────────────────────────────────────────────
//  • Pairing is mandatory and symmetric: both ends MUST use the SAME 32-byte key
//    and 12-byte nonce (and the default counter 0). The sender's keystream is the
//    receiver's keystream.
//  • NEVER reuse a (key, nonce) pair for two different streams. Re-using a nonce
//    under the same key is catastrophic (XOR of two plaintexts leaks). Use a fresh
//    random/counter nonce per stream and convey it out-of-band, or derive a unique
//    nonce per stream from a session value.
//  • ChaCha20 provides CONFIDENTIALITY ONLY — no integrity/authentication. A
//    tampered ciphertext decrypts to garbage without detection. If you need
//    authenticated encryption, add a MAC stage (e.g. Poly1305) or terminate the
//    stream into an authenticated container.
//
using System;
using System.Buffers.Binary;
using System.Diagnostics.CodeAnalysis;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using org.unirail.collections;

namespace org.unirail;

public interface ChaCha20
{
    ///<summary>
    ///ChaCha20 keystream engine (RFC 8439): 256-bit key, 96-bit nonce, 32-bit block counter, 20 rounds.
    ///Encryption and decryption are the same operation — XOR of the data with the keystream. The keystream
    ///position (block counter + offset into the current 64-byte block) is retained across <see cref="Process(Span{byte})"/>
    ///calls, so a single keyed stream spans any number of chunks and socket fills.
    ///<para>The bulk path is vectorized: on AVX-512 hardware it generates 16 blocks (1 KiB) at a time, on AVX2
    ///8 blocks (512 B) at a time, and otherwise falls through to the scalar block — all producing a byte-identical
    ///keystream to the reference implementation. The hand-off between tiers and the head/tail of every call are
    ///scalar, so chunk boundaries never disturb the keystream.</para>
    ///</summary>
    sealed class Core
    {
        const uint C0 = 0x61707865, C1 = 0x3320646e, C2 = 0x79622d32, C3 = 0x6b206574; //"expand 32-byte k"

        readonly uint[] _s = new uint[16];  //state: const(4) | key(8) | counter(1) | nonce(3)
        readonly byte[] _ks = new byte[64]; //current keystream block, for sub-block (tail/head) XOR
        int _ksPos = 64;                    //read cursor into _ks; 64 == exhausted (next byte forces a fresh block)

        ///<summary>(Re)key for a fresh stream. <paramref name="key"/> = 32 bytes, <paramref name="nonce"/> = 12 bytes.
        ///Both ends must pass identical values (and the same <paramref name="counter"/>, normally 0).</summary>
        public void Init(ReadOnlySpan<byte> key, ReadOnlySpan<byte> nonce, uint counter = 0)
        {
            if (key.Length != 32)
                throw new ArgumentException("ChaCha20 key must be 32 bytes, got " + key.Length, nameof(key));
            if (nonce.Length != 12)
                throw new ArgumentException("ChaCha20 nonce must be 12 bytes, got " + nonce.Length, nameof(nonce));

            _s[0] = C0;
            _s[1] = C1;
            _s[2] = C2;
            _s[3] = C3;
            for (var i = 0; i < 8; i++)
                _s[4 + i] = BinaryPrimitives.ReadUInt32LittleEndian(key.Slice(i * 4, 4));
            _s[12] = counter;
            _s[13] = BinaryPrimitives.ReadUInt32LittleEndian(nonce.Slice(0, 4));
            _s[14] = BinaryPrimitives.ReadUInt32LittleEndian(nonce.Slice(4, 4));
            _s[15] = BinaryPrimitives.ReadUInt32LittleEndian(nonce.Slice(8, 4));
            _ksPos = 64;
        }

        ///<summary>Right after <see cref="Init"/>: the stream's nonce becomes <c>nonce XOR (0⁴ ‖ seq)</c>, little-endian - the
        ///per-record nonce of TLS 1.3 and QUIC.</summary>
        public void Nonce(ulong seq)
        {
            _s[14] ^= (uint)seq;
            _s[15] ^= (uint)(seq >> 32);
        }

        ///<summary>
        ///The sequence of the next stream that carries its own nonce. Every process starts at a random point of the 64-bit
        ///space and counts up: two streams under one key never share a nonce within a process, and across processes and
        ///restarts only if two ranges drawn at random in 2⁶⁴ overlap.
        ///</summary>
        public static ulong NextSeq() => (ulong)System.Threading.Interlocked.Increment(ref _seq);

        static long _seq = BitConverter.ToInt64(System.Security.Cryptography.RandomNumberGenerator.GetBytes(8));

        ///<summary>In-place XOR (encrypt == decrypt).</summary>
        public void Process(Span<byte> data) => Process(data, data);

        ///<summary>XOR <paramref name="src"/> with the keystream into <paramref name="dst"/>
        ///(<paramref name="dst"/> may alias <paramref name="src"/>). Advances the keystream by the data length.</summary>
        public void Process(ReadOnlySpan<byte> src, Span<byte> dst)
        {
            Span<uint> b = stackalloc uint[16]; //one block scratch, reused for every block in this call
            int i = 0, n = src.Length;

            //1. finish the current partial keystream block left over from a previous call
            while (_ksPos < 64 && i < n)
            {
                dst[i] = (byte)(src[i] ^ _ks[_ksPos]);
                i++;
                _ksPos++;
            }

            //2a. bulk: 16 blocks (1 KiB) at a time on AVX-512. The IsSupported guard is a JIT-time
            //    constant, so on hardware without AVX-512 this whole loop is elided.
            if (Avx512F.IsSupported && Avx512BW.IsSupported)
                while (n - i >= 1024)
                {
                    Block16(_s, src.Slice(i, 1024), dst.Slice(i, 1024));
                    i += 1024;
                }

            //2b. bulk: 8 blocks (512 B) at a time on AVX2 — also covers the 512..1023 B remainder after the AVX-512 loop.
            if (Avx2.IsSupported)
                while (n - i >= 512)
                {
                    Block8(_s, src.Slice(i, 512), dst.Slice(i, 512));
                    i += 512;
                }

            //2c. whole 64-byte blocks — XOR straight from the freshly generated keystream, no _ks copy.
            //    This is the only bulk path on a non-x86 target (and the 64..511 B remainder elsewhere),
            //    so it XORs a whole block in two vector ops where the hardware has them. The vector
            //    forms consume the raw bytes of the keystream words, which equals the little-endian
            //    serialization RFC 8439 mandates only on a little-endian host — hence the guard, which
            //    like the IsHardwareAccelerated ones is a JIT-time constant.
            if (n - i >= 64)
            {
                ref byte sr = ref MemoryMarshal.GetReference(src);
                ref byte dr = ref MemoryMarshal.GetReference(dst);
                ref byte kr = ref Unsafe.As<uint, byte>(ref MemoryMarshal.GetReference(b)); //byte view of the block scratch
                do
                {
                    Block(b);
                    var at = (nuint)i;
                    if (BitConverter.IsLittleEndian && Vector256.IsHardwareAccelerated)
                    {
                        Vector256.StoreUnsafe(Vector256.LoadUnsafe(ref kr) ^ Vector256.LoadUnsafe(ref sr, at), ref dr, at);
                        Vector256.StoreUnsafe(Vector256.LoadUnsafe(ref kr, 32) ^ Vector256.LoadUnsafe(ref sr, at + 32), ref dr, at + 32);
                    }
                    else if (BitConverter.IsLittleEndian && Vector128.IsHardwareAccelerated)
                        for (nuint o = 0; o < 64; o += 16)
                            Vector128.StoreUnsafe(Vector128.LoadUnsafe(ref kr, o) ^ Vector128.LoadUnsafe(ref sr, at + o), ref dr, at + o);
                    else
                        for (var j = 0; j < 16; j++)
                        {
                            var w = b[j] ^ BinaryPrimitives.ReadUInt32LittleEndian(src.Slice(i + j * 4, 4));
                            BinaryPrimitives.WriteUInt32LittleEndian(dst.Slice(i + j * 4, 4), w);
                        }

                    i += 64;
                } while (n - i >= 64);
            }

            //3. tail < 64 — cache the block in _ks, consume what we need, keep the rest for the next call
            if (i < n)
            {
                Block(b);
                for (var j = 0; j < 16; j++)
                    BinaryPrimitives.WriteUInt32LittleEndian(_ks.AsSpan(j * 4, 4), b[j]);
                _ksPos = 0;
                while (i < n)
                {
                    dst[i] = (byte)(src[i] ^ _ks[_ksPos]);
                    i++;
                    _ksPos++;
                }
            }
        }

        //One 20-round ChaCha20 block (added to the input state) into o, then advance the 32-bit block counter.
        void Block(Span<uint> o)
        {
            uint x0 = _s[0], x1 = _s[1], x2 = _s[2], x3 = _s[3],
                 x4 = _s[4], x5 = _s[5], x6 = _s[6], x7 = _s[7],
                 x8 = _s[8], x9 = _s[9], x10 = _s[10], x11 = _s[11],
                 x12 = _s[12], x13 = _s[13], x14 = _s[14], x15 = _s[15];

            for (var r = 0; r < 10; r++) //10 double-rounds = 20 rounds
            {
                QR(ref x0, ref x4, ref x8, ref x12); //column rounds
                QR(ref x1, ref x5, ref x9, ref x13);
                QR(ref x2, ref x6, ref x10, ref x14);
                QR(ref x3, ref x7, ref x11, ref x15);
                QR(ref x0, ref x5, ref x10, ref x15); //diagonal rounds
                QR(ref x1, ref x6, ref x11, ref x12);
                QR(ref x2, ref x7, ref x8, ref x13);
                QR(ref x3, ref x4, ref x9, ref x14);
            }

            o[0] = x0 + _s[0];
            o[1] = x1 + _s[1];
            o[2] = x2 + _s[2];
            o[3] = x3 + _s[3];
            o[4] = x4 + _s[4];
            o[5] = x5 + _s[5];
            o[6] = x6 + _s[6];
            o[7] = x7 + _s[7];
            o[8] = x8 + _s[8];
            o[9] = x9 + _s[9];
            o[10] = x10 + _s[10];
            o[11] = x11 + _s[11];
            o[12] = x12 + _s[12];
            o[13] = x13 + _s[13];
            o[14] = x14 + _s[14];
            o[15] = x15 + _s[15];

            _s[12]++; //32-bit block counter; wraps after 2^32 blocks (256 GB), no carry into the nonce (RFC 8439)
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void QR(ref uint a, ref uint b, ref uint c, ref uint d)
        {
            a += b;
            d ^= a;
            d = BitOperations.RotateLeft(d, 16);
            c += d;
            b ^= c;
            b = BitOperations.RotateLeft(b, 12);
            a += b;
            d ^= a;
            d = BitOperations.RotateLeft(d, 8);
            c += d;
            b ^= c;
            b = BitOperations.RotateLeft(b, 7);
        }

        //SIMD bulk keystream. Both routines consume whole blocks from `src` into `dst` and advance s[12] by the
        //blocks produced, so the streaming counter stays owned here and the scalar head/tail above is unchanged.
        //Layout is word-parallel: each vector lane is a different block (16 state words → 16 vectors, round
        //function is pure lane-wise ARX), and a final 8×8 transpose (XorStore8, one group at a time, kept in
        //vector registers) turns the word-major lanes back into contiguous 64-byte blocks for the XOR.

        //Transpose one word-major 8×8 dword group into block-major rows and XOR-store each
        //32-byte row over its block: row t belongs to block t, and blocks are 64 B apart.
        //`off` is the byte offset of row 0 — it selects both the block group (64 B per block)
        //and the half of the block (0 == words 0..7, 32 == words 8..15).
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void XorStore8(Vector256<uint> r0, Vector256<uint> r1, Vector256<uint> r2, Vector256<uint> r3,
                              Vector256<uint> r4, Vector256<uint> r5, Vector256<uint> r6, Vector256<uint> r7,
                              ref byte src, ref byte dst, nuint off)
        {
            Transpose8x8(ref r0, ref r1, ref r2, ref r3, ref r4, ref r5, ref r6, ref r7);
            Vector256.StoreUnsafe(r0.AsByte() ^ Vector256.LoadUnsafe(ref src, off), ref dst, off);
            Vector256.StoreUnsafe(r1.AsByte() ^ Vector256.LoadUnsafe(ref src, off + 64), ref dst, off + 64);
            Vector256.StoreUnsafe(r2.AsByte() ^ Vector256.LoadUnsafe(ref src, off + 128), ref dst, off + 128);
            Vector256.StoreUnsafe(r3.AsByte() ^ Vector256.LoadUnsafe(ref src, off + 192), ref dst, off + 192);
            Vector256.StoreUnsafe(r4.AsByte() ^ Vector256.LoadUnsafe(ref src, off + 256), ref dst, off + 256);
            Vector256.StoreUnsafe(r5.AsByte() ^ Vector256.LoadUnsafe(ref src, off + 320), ref dst, off + 320);
            Vector256.StoreUnsafe(r6.AsByte() ^ Vector256.LoadUnsafe(ref src, off + 384), ref dst, off + 384);
            Vector256.StoreUnsafe(r7.AsByte() ^ Vector256.LoadUnsafe(ref src, off + 448), ref dst, off + 448);
        }

        //---- AVX2: 8 blocks (512 B) per call ----

        //Rotating left by 16 and by 8 moves whole BYTES inside each dword, so one `vpshufb` does what
        //shift/shift/or needs three instructions and a live extra temporary for — and it is that
        //temporary, not the instruction count, that dominates: 16 word vectors already fill all 16 YMM
        //registers, so every extra live value spills. Replacing the two byte-aligned rotations cuts the
        //stack traffic of an 8-block group from ~200 to ~140 32-byte moves and nearly doubles the
        //throughput of this path. The masks index within each 128-bit lane, hence the repeat.
        static readonly Vector256<byte> Rot16 = Vector256.Create((byte)2, 3, 0, 1, 6, 7, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13,
                                                                 2, 3, 0, 1, 6, 7, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13);
        static readonly Vector256<byte> Rot8 = Vector256.Create((byte)3, 0, 1, 2, 7, 4, 5, 6, 11, 8, 9, 10, 15, 12, 13, 14,
                                                                3, 0, 1, 2, 7, 4, 5, 6, 11, 8, 9, 10, 15, 12, 13, 14);

        //Rotations by 12 and 7 are not byte multiples, so they stay shift/shift/or — but BOTH counts
        //have to reach the JIT as literals. It folds a [ConstantExpected] argument forwarded verbatim
        //into the `imm8` encoding and does NOT fold an expression over it: written as `32 - n` the right
        //shift silently becomes the VARIABLE form, `vpsrld ymm, ymm, ymmword ptr [mem]`, paying a memory
        //load for its shift count every time. Hence two explicit literals per call site instead of one.
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static Vector256<uint> Rol2(Vector256<uint> x, [ConstantExpected] byte l, [ConstantExpected] byte r) => Avx2.Or(Avx2.ShiftLeftLogical(x, l), Avx2.ShiftRightLogical(x, r));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void QR2(ref Vector256<uint> a, ref Vector256<uint> b, ref Vector256<uint> c, ref Vector256<uint> d)
        {
            a = Avx2.Add(a, b);
            d = Avx2.Shuffle(Avx2.Xor(d, a).AsByte(), Rot16).AsUInt32();
            c = Avx2.Add(c, d);
            b = Rol2(Avx2.Xor(b, c), 12, 20);
            a = Avx2.Add(a, b);
            d = Avx2.Shuffle(Avx2.Xor(d, a).AsByte(), Rot8).AsUInt32();
            c = Avx2.Add(c, d);
            b = Rol2(Avx2.Xor(b, c), 7, 25);
        }

        static void Block8(uint[] s, ReadOnlySpan<byte> src, Span<byte> dst)
        {
            var inc = Vector256.Create(0u, 1, 2, 3, 4, 5, 6, 7); //per-lane counter offset
            Vector256<uint> o0 = Vector256.Create(s[0]), o1 = Vector256.Create(s[1]), o2 = Vector256.Create(s[2]), o3 = Vector256.Create(s[3]),
                            o4 = Vector256.Create(s[4]), o5 = Vector256.Create(s[5]), o6 = Vector256.Create(s[6]), o7 = Vector256.Create(s[7]),
                            o8 = Vector256.Create(s[8]), o9 = Vector256.Create(s[9]), o10 = Vector256.Create(s[10]), o11 = Vector256.Create(s[11]),
                            o12 = Avx2.Add(Vector256.Create(s[12]), inc), o13 = Vector256.Create(s[13]), o14 = Vector256.Create(s[14]), o15 = Vector256.Create(s[15]);
            Vector256<uint> x0 = o0, x1 = o1, x2 = o2, x3 = o3, x4 = o4, x5 = o5, x6 = o6, x7 = o7,
                            x8 = o8, x9 = o9, x10 = o10, x11 = o11, x12 = o12, x13 = o13, x14 = o14, x15 = o15;

            for (var r = 0; r < 10; r++)
            {
                QR2(ref x0, ref x4, ref x8, ref x12);
                QR2(ref x1, ref x5, ref x9, ref x13);
                QR2(ref x2, ref x6, ref x10, ref x14);
                QR2(ref x3, ref x7, ref x11, ref x15);
                QR2(ref x0, ref x5, ref x10, ref x15);
                QR2(ref x1, ref x6, ref x11, ref x12);
                QR2(ref x2, ref x7, ref x8, ref x13);
                QR2(ref x3, ref x4, ref x9, ref x14);
            }

            x0 = Avx2.Add(x0, o0);
            x1 = Avx2.Add(x1, o1);
            x2 = Avx2.Add(x2, o2);
            x3 = Avx2.Add(x3, o3);
            x4 = Avx2.Add(x4, o4);
            x5 = Avx2.Add(x5, o5);
            x6 = Avx2.Add(x6, o6);
            x7 = Avx2.Add(x7, o7);
            x8 = Avx2.Add(x8, o8);
            x9 = Avx2.Add(x9, o9);
            x10 = Avx2.Add(x10, o10);
            x11 = Avx2.Add(x11, o11);
            x12 = Avx2.Add(x12, o12);
            x13 = Avx2.Add(x13, o13);
            x14 = Avx2.Add(x14, o14);
            x15 = Avx2.Add(x15, o15);

            //word-major → block-major: two independent 8×8 dword transposes, each XOR-stored as it
            //is produced (words 0..7 fill the first half of every block, words 8..15 the second)
            ref byte sr = ref MemoryMarshal.GetReference(src);
            ref byte dr = ref MemoryMarshal.GetReference(dst);
            XorStore8(x0, x1, x2, x3, x4, x5, x6, x7, ref sr, ref dr, 0);
            XorStore8(x8, x9, x10, x11, x12, x13, x14, x15, ref sr, ref dr, 32);
            s[12] += 8;
        }

        //Standard AVX2 8×8 dword transpose (UnpackLow/High dword → qword → Permute2x128).
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void Transpose8x8(ref Vector256<uint> r0, ref Vector256<uint> r1, ref Vector256<uint> r2, ref Vector256<uint> r3,
                                 ref Vector256<uint> r4, ref Vector256<uint> r5, ref Vector256<uint> r6, ref Vector256<uint> r7)
        {
            var t0 = Avx2.UnpackLow(r0, r1);
            var t1 = Avx2.UnpackHigh(r0, r1);
            var t2 = Avx2.UnpackLow(r2, r3);
            var t3 = Avx2.UnpackHigh(r2, r3);
            var t4 = Avx2.UnpackLow(r4, r5);
            var t5 = Avx2.UnpackHigh(r4, r5);
            var t6 = Avx2.UnpackLow(r6, r7);
            var t7 = Avx2.UnpackHigh(r6, r7);
            var u0 = Avx2.UnpackLow(t0.AsUInt64(), t2.AsUInt64()).AsUInt32();
            var u1 = Avx2.UnpackHigh(t0.AsUInt64(), t2.AsUInt64()).AsUInt32();
            var u2 = Avx2.UnpackLow(t1.AsUInt64(), t3.AsUInt64()).AsUInt32();
            var u3 = Avx2.UnpackHigh(t1.AsUInt64(), t3.AsUInt64()).AsUInt32();
            var u4 = Avx2.UnpackLow(t4.AsUInt64(), t6.AsUInt64()).AsUInt32();
            var u5 = Avx2.UnpackHigh(t4.AsUInt64(), t6.AsUInt64()).AsUInt32();
            var u6 = Avx2.UnpackLow(t5.AsUInt64(), t7.AsUInt64()).AsUInt32();
            var u7 = Avx2.UnpackHigh(t5.AsUInt64(), t7.AsUInt64()).AsUInt32();
            r0 = Avx2.Permute2x128(u0, u4, 0x20);
            r1 = Avx2.Permute2x128(u1, u5, 0x20);
            r2 = Avx2.Permute2x128(u2, u6, 0x20);
            r3 = Avx2.Permute2x128(u3, u7, 0x20);
            r4 = Avx2.Permute2x128(u0, u4, 0x31);
            r5 = Avx2.Permute2x128(u1, u5, 0x31);
            r6 = Avx2.Permute2x128(u2, u6, 0x31);
            r7 = Avx2.Permute2x128(u3, u7, 0x31);
        }

        //---- AVX-512: 16 blocks (1 KiB) per call. Rounds run 16-wide; the output transpose
        //     reuses the proven AVX2 8×8 on each 256-bit half (blocks 0..7 and 8..15). ----

        //`vprold` — one instruction, where the AVX2 path has to emulate the rotate with
        //shift/shift/or. There are 320 rotations per 1 KiB group, so this is 640 vector
        //instructions saved per call. (AVX-512 only; AVX2 has no dword rotate.)
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static Vector512<uint> Rol5(Vector512<uint> x, [ConstantExpected] byte n) => Avx512F.RotateLeft(x, n);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void QR5(ref Vector512<uint> a, ref Vector512<uint> b, ref Vector512<uint> c, ref Vector512<uint> d)
        {
            a = Avx512F.Add(a, b);
            d = Rol5(Avx512F.Xor(d, a), 16);
            c = Avx512F.Add(c, d);
            b = Rol5(Avx512F.Xor(b, c), 12);
            a = Avx512F.Add(a, b);
            d = Rol5(Avx512F.Xor(d, a), 8);
            c = Avx512F.Add(c, d);
            b = Rol5(Avx512F.Xor(b, c), 7);
        }

        static void Block16(uint[] s, ReadOnlySpan<byte> src, Span<byte> dst)
        {
            var inc = Vector512.Create(0u, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15); //per-lane counter offset
            Vector512<uint> o0 = Vector512.Create(s[0]), o1 = Vector512.Create(s[1]), o2 = Vector512.Create(s[2]), o3 = Vector512.Create(s[3]),
                            o4 = Vector512.Create(s[4]), o5 = Vector512.Create(s[5]), o6 = Vector512.Create(s[6]), o7 = Vector512.Create(s[7]),
                            o8 = Vector512.Create(s[8]), o9 = Vector512.Create(s[9]), o10 = Vector512.Create(s[10]), o11 = Vector512.Create(s[11]),
                            o12 = Avx512F.Add(Vector512.Create(s[12]), inc), o13 = Vector512.Create(s[13]), o14 = Vector512.Create(s[14]), o15 = Vector512.Create(s[15]);
            Vector512<uint> x0 = o0, x1 = o1, x2 = o2, x3 = o3, x4 = o4, x5 = o5, x6 = o6, x7 = o7,
                            x8 = o8, x9 = o9, x10 = o10, x11 = o11, x12 = o12, x13 = o13, x14 = o14, x15 = o15;

            for (var r = 0; r < 10; r++)
            {
                QR5(ref x0, ref x4, ref x8, ref x12);
                QR5(ref x1, ref x5, ref x9, ref x13);
                QR5(ref x2, ref x6, ref x10, ref x14);
                QR5(ref x3, ref x7, ref x11, ref x15);
                QR5(ref x0, ref x5, ref x10, ref x15);
                QR5(ref x1, ref x6, ref x11, ref x12);
                QR5(ref x2, ref x7, ref x8, ref x13);
                QR5(ref x3, ref x4, ref x9, ref x14);
            }

            x0 = Avx512F.Add(x0, o0);
            x1 = Avx512F.Add(x1, o1);
            x2 = Avx512F.Add(x2, o2);
            x3 = Avx512F.Add(x3, o3);
            x4 = Avx512F.Add(x4, o4);
            x5 = Avx512F.Add(x5, o5);
            x6 = Avx512F.Add(x6, o6);
            x7 = Avx512F.Add(x7, o7);
            x8 = Avx512F.Add(x8, o8);
            x9 = Avx512F.Add(x9, o9);
            x10 = Avx512F.Add(x10, o10);
            x11 = Avx512F.Add(x11, o11);
            x12 = Avx512F.Add(x12, o12);
            x13 = Avx512F.Add(x13, o13);
            x14 = Avx512F.Add(x14, o14);
            x15 = Avx512F.Add(x15, o15);

            //Each 16-lane word vector holds blocks 0..7 in its lower 256 bits and blocks 8..15 in
            //its upper 256 bits, so the output is four INDEPENDENT 8×8 dword transposes over
            //disjoint 32-byte destination rows — each one is split off, transposed and XOR-stored
            //on its own, so only 8 vectors of transpose state are ever live. Words 0..7 (x0..x7)
            //go first so those five 512-bit registers die before the second half is touched.
            ref byte sr = ref MemoryMarshal.GetReference(src);
            ref byte dr = ref MemoryMarshal.GetReference(dst);
            XorStore8(x0.GetLower(), x1.GetLower(), x2.GetLower(), x3.GetLower(), //blocks 0..7,  words 0..7
                      x4.GetLower(), x5.GetLower(), x6.GetLower(), x7.GetLower(), ref sr, ref dr, 0);
            XorStore8(x0.GetUpper(), x1.GetUpper(), x2.GetUpper(), x3.GetUpper(), //blocks 8..15, words 0..7
                      x4.GetUpper(), x5.GetUpper(), x6.GetUpper(), x7.GetUpper(), ref sr, ref dr, 512);
            XorStore8(x8.GetLower(), x9.GetLower(), x10.GetLower(), x11.GetLower(), //blocks 0..7,  words 8..15
                      x12.GetLower(), x13.GetLower(), x14.GetLower(), x15.GetLower(), ref sr, ref dr, 32);
            XorStore8(x8.GetUpper(), x9.GetUpper(), x10.GetUpper(), x11.GetUpper(), //blocks 8..15, words 8..15
                      x12.GetUpper(), x13.GetUpper(), x14.GetUpper(), x15.GetUpper(), ref sr, ref dr, 544);
            s[12] += 16;
        }
    }

    ///<summary>
    ///Poly1305 one-time authenticator (RFC 8439): a 16-byte tag of a message under a 32-byte key used once. Ported from
    ///Monocypher 4 (https://monocypher.org, CC0 / public domain; audited by Cure53 in 2020): 32-bit limbs, 64-bit products.
    ///</summary>
    sealed class Poly1305
    {
        readonly uint[] _r = new uint[4], _pad = new uint[4], _h = new uint[5];
        readonly byte[] _c = new byte[16]; //a block not yet complete
        int _cIdx;

        public void Init(ReadOnlySpan<byte> key)
        {
            Array.Clear(_h);
            _cIdx = 0;
            for (var i = 0; i < 4; i++)
            {
                _r[i] = BinaryPrimitives.ReadUInt32LittleEndian(key.Slice(i * 4));
                _pad[i] = BinaryPrimitives.ReadUInt32LittleEndian(key.Slice(16 + i * 4));
            }
            _r[0] &= 0x0fffffff; //r is clamped
            for (var i = 1; i < 4; i++)
                _r[i] &= 0x0ffffffc;
        }

        //h = (h + c) * r for each 16-byte block; end = 1 adds the 2^128 of a full block.
        void Blocks(ReadOnlySpan<byte> input, int nbBlocks, uint end)
        {
            uint r0 = _r[0], r1 = _r[1], r2 = _r[2], r3 = _r[3];
            uint rr0 = (r0 >> 2) * 5, rr1 = (r1 >> 2) + r1, rr2 = (r2 >> 2) + r2, rr3 = (r3 >> 2) + r3, rr4 = r0 & 3;
            uint h0 = _h[0], h1 = _h[1], h2 = _h[2], h3 = _h[3], h4 = _h[4];
            for (var i = 0; i < nbBlocks; i++)
            {
                var b = input.Slice(i * 16);
                ulong s0 = (ulong)h0 + BinaryPrimitives.ReadUInt32LittleEndian(b);
                ulong s1 = (ulong)h1 + BinaryPrimitives.ReadUInt32LittleEndian(b.Slice(4));
                ulong s2 = (ulong)h2 + BinaryPrimitives.ReadUInt32LittleEndian(b.Slice(8));
                ulong s3 = (ulong)h3 + BinaryPrimitives.ReadUInt32LittleEndian(b.Slice(12));
                uint s4 = h4 + end;

                ulong x0 = s0 * r0 + s1 * rr3 + s2 * rr2 + s3 * rr1 + (ulong)s4 * rr0;
                ulong x1 = s0 * r1 + s1 * r0 + s2 * rr3 + s3 * rr2 + (ulong)s4 * rr1;
                ulong x2 = s0 * r2 + s1 * r1 + s2 * r0 + s3 * rr3 + (ulong)s4 * rr2;
                ulong x3 = s0 * r3 + s1 * r2 + s2 * r1 + s3 * r0 + (ulong)s4 * rr3;
                uint x4 = s4 * rr4;

                //partial reduction modulo 2^130 - 5
                uint u5 = (uint)(x3 >> 32) + x4;
                ulong u0 = (ulong)(u5 >> 2) * 5 + (x0 & 0xffffffff);
                ulong u1 = (u0 >> 32) + (x1 & 0xffffffff) + (x0 >> 32);
                ulong u2 = (u1 >> 32) + (x2 & 0xffffffff) + (x1 >> 32);
                ulong u3 = (u2 >> 32) + (x3 & 0xffffffff) + (x2 >> 32);
                uint u4 = (uint)(u3 >> 32) + (u5 & 3);

                h0 = (uint)u0;
                h1 = (uint)u1;
                h2 = (uint)u2;
                h3 = (uint)u3;
                h4 = u4;
            }
            _h[0] = h0;
            _h[1] = h1;
            _h[2] = h2;
            _h[3] = h3;
            _h[4] = h4;
        }

        public void Update(ReadOnlySpan<byte> message)
        {
            if (0 < _cIdx)
            {
                var n = Math.Min(16 - _cIdx, message.Length);
                message.Slice(0, n).CopyTo(_c.AsSpan(_cIdx));
                _cIdx += n;
                message = message.Slice(n);
                if (_cIdx < 16)
                    return;
                Blocks(_c, 1, 1);
                _cIdx = 0;
            }
            var nb = message.Length >> 4;
            Blocks(message, nb, 1);
            message = message.Slice(nb << 4);
            message.CopyTo(_c);
            _cIdx = message.Length;
        }

        public void Final(Span<byte> mac)
        {
            if (_cIdx != 0)
            { //the last block, padded with a 1 then zeros: the 1 marks its length instead of the 2^128
                _c.AsSpan(_cIdx).Clear();
                _c[_cIdx] = 1;
                Blocks(_c, 1, 0);
            }
            ulong c = 5; //subtract 2^130 - 5 once when h is at or above it
            for (var i = 0; i < 4; i++)
            {
                c += _h[i];
                c >>= 32;
            }
            c += _h[4];
            c = (c >> 2) * 5;
            for (var i = 0; i < 4; i++)
            {
                c += (ulong)_h[i] + _pad[i];
                BinaryPrimitives.WriteUInt32LittleEndian(mac.Slice(i * 4), (uint)c);
                c >>= 32;
            }
            Array.Clear(_h);
            Array.Clear(_r);
            Array.Clear(_pad);
            Array.Clear(_c);
        }
    }

    ///<summary>
    ///ChaCha20-Poly1305 AEAD (RFC 8439) under one key, a message at a time: <see cref="Seal"/> and <see cref="Open"/> work in
    ///place and take the 64-bit message number the nonce is made of - 32 zero bits, then the number little-endian, as
    ///the Noise protocol forms it. A number must never be used twice under one key.
    ///</summary>
    sealed class Aead
    {
        public const int TAG = 16;

        readonly byte[] _key = new byte[32];
        readonly Core _c = new();
        readonly Poly1305 _mac = new();

        public Aead(ReadOnlySpan<byte> key) => Rekey(key);

        public void Rekey(ReadOnlySpan<byte> key) => key.Slice(0, 32).CopyTo(_key);

        public void Wipe() => System.Security.Cryptography.CryptographicOperations.ZeroMemory(_key);

        static void nonceOf(ulong n, Span<byte> nonce)
        {
            nonce.Slice(0, 4).Clear();
            BinaryPrimitives.WriteUInt64LittleEndian(nonce.Slice(4), n);
        }

        //Keystream block 0 gives the one-time Poly1305 key; the data takes the keystream from block 1 on.
        void start(ReadOnlySpan<byte> nonce)
        {
            _c.Init(_key, nonce);
            Span<byte> block = stackalloc byte[64];
            block.Clear();
            _c.Process(block); //block 0: the counter is 1 after it
            _mac.Init(block.Slice(0, 32));
            block.Clear();
        }

        void authenticate(ReadOnlySpan<byte> ad, ReadOnlySpan<byte> cipher, Span<byte> tag)
        {
            Span<byte> pad = stackalloc byte[16];
            pad.Clear();
            _mac.Update(ad);
            _mac.Update(pad.Slice(0, -ad.Length & 15));
            _mac.Update(cipher);
            _mac.Update(pad.Slice(0, -cipher.Length & 15));
            BinaryPrimitives.WriteUInt64LittleEndian(pad, (ulong)ad.Length);
            BinaryPrimitives.WriteUInt64LittleEndian(pad.Slice(8), (ulong)cipher.Length);
            _mac.Update(pad);
            _mac.Final(tag);
        }

        ///<summary>Encrypts <paramref name="data"/> in place and writes the tag of it and <paramref name="ad"/>.</summary>
        public void Seal(ulong n, ReadOnlySpan<byte> ad, Span<byte> data, Span<byte> tag)
        {
            Span<byte> nonce = stackalloc byte[12];
            nonceOf(n, nonce);
            Seal(nonce, ad, data, tag);
        }

        ///<summary>As <see cref="Seal(ulong, ReadOnlySpan{byte}, Span{byte}, Span{byte})"/>, with the whole 12-byte nonce given.</summary>
        public void Seal(ReadOnlySpan<byte> nonce, ReadOnlySpan<byte> ad, Span<byte> data, Span<byte> tag)
        {
            start(nonce);
            _c.Process(data);
            authenticate(ad, data, tag);
        }

        ///<summary>Checks the tag of <paramref name="data"/> and <paramref name="ad"/>, and only then decrypts in place.</summary>
        ///<returns><c>false</c> - forged or damaged: <paramref name="data"/> is left as it was.</returns>
        public bool Open(ulong n, ReadOnlySpan<byte> ad, Span<byte> data, ReadOnlySpan<byte> tag)
        {
            Span<byte> nonce = stackalloc byte[12];
            nonceOf(n, nonce);
            return Open(nonce, ad, data, tag);
        }

        ///<summary>As <see cref="Open(ulong, ReadOnlySpan{byte}, Span{byte}, ReadOnlySpan{byte})"/>, with the whole 12-byte nonce given.</summary>
        public bool Open(ReadOnlySpan<byte> nonce, ReadOnlySpan<byte> ad, Span<byte> data, ReadOnlySpan<byte> tag)
        {
            start(nonce);
            Span<byte> expected = stackalloc byte[TAG];
            authenticate(ad, data, expected);
            if (!System.Security.Cryptography.CryptographicOperations.FixedTimeEquals(expected, tag.Slice(0, TAG)))
                return false;
            _c.Process(data);
            return true;
        }
    }

    ///<summary>Decrypting receive-side stage.</summary>
    interface Receiver
    {
        ///<summary>
        ///ChaCha20-decrypting inner stage for <see cref="AdHoc.Connection.Receiver.Chunked"/>: XOR-decrypts each
        ///de-framed chunk out of the receive buffer into a scratch buffer, then drains the recovered plaintext into a
        ///downstream <see cref="AdHoc.Connection.Receiver.BytesDst"/> (a <c>Terminal</c> sink, or another stage).
        ///Pair with <see cref="Transmitter.Stage"/>.
        ///<para>The scratch buffer fully consumes the encrypted input each call (so the framer never re-presents
        ///already-decrypted bytes), and dribbles plaintext to the inner stage across backpressure. As a pure-byte inner
        ///stage it never touches the slot and never self-completes — the outer framer's <c>0x0000</c> terminator is the
        ///sole end-authority, so <see cref="__put_bytes"/> always returns <c>false</c>.</para>
        ///</summary>
        class Stage : AdHoc.Connection.Receiver.BytesDst, AdHoc.BytesDst
        {
            public static int buffer_size = 1 << 16; //staging buffer for decrypted plaintext

            readonly Core _c = new();
            readonly byte[] _out = new byte[buffer_size]; //staging buffer for decrypted plaintext
            int _outPos;                                  //read cursor into _out (plaintext already delivered downstream)
            int _outLen;                                  //valid plaintext length currently staged in _out
            bool _inFlight;                               //re-entrancy guard: a nested downstream consumer must not re-drive this stage mid-read (ports Java's inFlight)

            AdHoc.Connection.Receiver.BytesDst dst = null!; //inner stage — another IStream (Chunked/File) or a Terminal leaf

            ///<summary>Chain builder: swap the inner next-stage <see cref="dst"/> — set it (null to detach), return the previous.</summary>

            public int __id { get; set; } //unused for an inner stage (the outer framer carries the dispatch id)

            ///<summary>(Re)configure: inner dst + a fresh ChaCha20 keystream (<paramref name="key"/> 32 B, <paramref name="nonce"/> 12 B). Returns <c>this</c> for chaining.</summary>
            public Stage Init(AdHoc.Connection.Receiver.BytesDst dst, byte[] key, byte[] nonce)
            {
                this.dst = dst;
                dst_ = null; //INNER role — the two roles are mutually exclusive per instance
                _c.Init(key, nonce);
                _outPos = _outLen = 0;
                _hdrGot = HDR;
                _discard = false;
                return this;
            }

            ///<summary>
            ///(Re)configure for a pack, the pair of <see cref="Transmitter.Stage.InitExplicit"/>: its first 12 bytes, in clear,
            ///are the id of the key it was encrypted with (4) and the sequence its nonce is made of (8). The stage holds no key:
            ///it takes the one of that id from the keys of the Receiver that drives it (<see cref="AdHoc.Connection.Receiver.keys"/>).
            ///Each pack is decrypted alone: after a loss, as a duplicate, out of a replayed journal. A pack whose key the session
            ///does not have - of a session this side has lost - is dropped whole (<c>drop_received</c>).
            ///</summary>
            public Stage InitExplicit(AdHoc.Connection.Receiver.BytesDst dst)
            {
                this.dst = dst;
                dst_ = null;
                _outPos = _outLen = 0;
                _hdrGot = 0;
                _discard = false;
                return this;
            }

            const int HDR = 12;
            readonly byte[] _hdr = new byte[HDR];
            int _hdrGot = HDR; //bytes of the header read so far; HDR - all, or none to read
            bool _discard;     //the pack's key is unknown: its bytes are taken and thrown away

            //The header in front of the ciphertext: false while more of it is to come.
            bool readSeq(AdHoc.Connection.Receiver src, byte[] buf, ref int pos, int max)
            {
                for (; _hdrGot < HDR; _hdrGot++, pos++)
                {
                    if (pos == max)
                        return false;
                    _hdr[_hdrGot] = buf[pos];
                }
                var k = src.keys.Find(BinaryPrimitives.ReadUInt32LittleEndian(_hdr));
                if (k == null)
                {
                    _discard = true;
                    src.drop_received = true; //not dispatched when it ends
                    return true;
                }
                _c.Init(k.key, k.iv);
                _c.Nonce(BinaryPrimitives.ReadUInt64LittleEndian(_hdr.AsSpan(4)));
                return true;
            }
#region TRANSPORT role
            //Length-preserving, so nothing to flush and no frame. Decrypt into staging, NEVER in place: the transport
            //re-offers a refused tail, and a second XOR over it would corrupt it and desynchronize the keystream.

            AdHoc.BytesDst? dst_; //TRANSPORT role: the connection's own Receiver (null ⇒ inner role)
            int _skip;            //ciphertext byte already through the keystream that the transport will re-offer
            bool _closed;

            ///<summary>Ciphertext bytes consumed off the transport so far.</summary>
            public long wire_bytes;

            ///<summary>Plaintext bytes delivered to <see cref="dst_"/> so far.</summary>
            public long plain_bytes;

            ///<summary>Arm as the connection's transport-level decryptor: takes ciphertext off the socket and feeds the
            ///recovered protocol bytes to <paramref name="dst_"/> (normally <c>Connection.receiver</c>).
            ///Pair with <see cref="Transmitter.Stage.Init_"/>.</summary>
            public Stage Init_(AdHoc.BytesDst dst_, byte[] key, byte[] nonce)
            {
                this.dst_ = dst_;
                dst = null!; //TRANSPORT role
                _c.Init(key, nonce);
                _outPos = _outLen = 0;
                _hdrGot = HDR;
                _discard = false;
                _skip = 0;
                _closed = false;
                return this;
            }

            public bool isOpen() => !_closed && (dst_?.isOpen() ?? true);

            public void Close()
            {
                if (_closed)
                    return;
                _closed = true;
                _outPos = _outLen = 0;
                _skip = 0;
                dst_?.Close();
            }

            ///<summary>Transport entry: decrypt <paramref name="src"/> into the staging buffer and drain the recovered
            ///protocol bytes into <see cref="dst_"/>, reporting a SHORT count when the sink refuses.
            ///<para>ATTENTION! <paramref name="src"/> is borrowed and must not be referenced after this returns.</para></summary>
            ///<returns>The number of CIPHERTEXT bytes consumed from <paramref name="src"/>.</returns>
            public int Write(byte[] src, int src_byte, int src_bytes)
            {
                if (_closed || dst_ == null || src_bytes < 0)
                    return 0;
                var inPos = src_byte;
                var inMax = src_byte + src_bytes;

                if (0 < _skip) //this byte already went through the keystream — count it, do not re-decrypt it
                {
                    var s = Math.Min(_skip, src_bytes);
                    inPos += s;
                    _skip -= s;
                }

                while (true)
                {
                    if (_outPos < _outLen) //deliver staged plaintext BEFORE decrypting more
                    {
                        var n = dst_.Write(_out, _outPos, _outLen - _outPos);
                        if (n < 1)
                            break; //sink refuses → keep the staging, report what we consumed
                        _outPos += n;
                        plain_bytes += n;
                        if (_outPos < _outLen)
                            break; //partial take → same
                    }

                    _outPos = _outLen = 0;
                    if (inPos >= inMax)
                        break; //window exhausted — a stream cipher never holds bytes back, so this is the exit

                    var take = Math.Min(inMax - inPos, _out.Length);
                    _c.Process(src.AsSpan(inPos, take), _out.AsSpan(0, take)); //XOR-decrypt into staging (never in place: the transport may re-offer this buffer)
                    inPos += take;
                    wire_bytes += take;
                    _outLen = take;
                }

                var consumed = inPos - src_byte;
                if (_outPos < _outLen && consumed == src_bytes && 0 < consumed) //keep the transport's tail non-empty
                {
                    consumed--;
                    _skip = 1;
                }

                return consumed;
            }
#endregion

            ///<summary>
            ///Framework entry. Decrypts the available (chunk-clamped) ciphertext from the receive window into <c>_out</c>,
            ///draining the recovered plaintext into <see cref="dst"/> via a buffer swap. Always returns <c>false</c>:
            ///a codec stage never self-completes — the outer Chunked framer's <c>0x0000</c> terminator ends the stream.
            ///</summary>
            public bool __put_bytes(AdHoc.Connection.Receiver src)
            {
                //A deeply-nested downstream consumer (reached through _out) could, on its own park/resume, re-enter and
                //re-drive THIS stage mid-read — which would decrypt over the swapped _out window and corrupt state.
                //Refuse the re-entrant refill: park; the outer (non-re-entrant) drive refills after the framer's clamped
                //feed. (Ports Java's inFlight guard; in C#'s streaming model no such re-entry path is known, so this is a
                //safe no-op guard for parity — never fires unless a re-entry exists.)
                if (_inFlight)
                    return false;
                _inFlight = true;
                var inBuf = src.buffer!; //ciphertext input window (already clamped to the current chunk by the framer)
                var inPos = src.byte_;
                var inMax = src.byte_max;
                try
                {
                    if (_hdrGot < HDR && !readSeq(src, inBuf, ref inPos, inMax))
                        return false; //the rest of the header comes with the next chunk
                    if (_discard)
                    {
                        inPos = inMax; //a pack of a key this session does not have: taken, and thrown away
                        return false;
                    }
                    while (true)
                    {
                        //1. flush any plaintext still staged in _out to the inner stage before producing more
                        if (_outPos < _outLen)
                        {
                            src.buffer = _out;
                            src.byte_ = _outPos;
                            src.byte_max = _outLen;
                            dst.__put_bytes(src); //inner stage consumes pure bytes; its return is ignored (terminator is end-authority)
                            _outPos = src.byte_;  //the inner stage is the source of truth for what it consumed
                            if (_outPos < _outLen)
                                break; //inner parked (backpressure) → yield, leaving the unconsumed _out intact
                        }

                        //2. _out drained — decrypt the next batch of ciphertext from the receive window
                        if (inPos >= inMax)
                            break; //chunk exhausted → yield, wait for the next chunk
                        var n = Math.Min(inMax - inPos, _out.Length);
                        _c.Process(inBuf.AsSpan(inPos, n), _out.AsSpan(0, n)); //XOR-decrypt ciphertext → plaintext
                        inPos += n;
                        _outPos = 0;
                        _outLen = n;
                    }
                }
                finally
                {
                    //Restore the ciphertext wire window; src.byte_ reflects exactly how much ciphertext we consumed
                    //(the framer reads it back as the chunk's consumption count). Runs even if a nested call threw.
                    src.buffer = inBuf;
                    src.byte_ = inPos;
                    src.byte_max = inMax;
                    _inFlight = false;
                }

                return false; //a codec never self-completes; the framer's 0x0000 terminator is the end-authority
            }
        }
    }

    ///<summary>Encrypting transmit-side stage.</summary>
    interface Transmitter
    {
        ///<summary>
        ///ChaCha20-encrypting inner stage for <see cref="AdHoc.Connection.Transmitter.Chunked"/>: lets an upstream
        ///<see cref="AdHoc.Connection.Transmitter.BytesSrc"/> (a <c>Terminal</c> source, or another stage) write plaintext
        ///straight into the transmit window, XOR-encrypts it <b>in place</b> (the cipher is length-preserving, so no
        ///scratch buffer is needed), and hands the ciphertext back to the framer for chunk framing. Pair with
        ///<see cref="Receiver.Stage"/>.
        ///<para>Because it is length-preserving, a ChaCha20 stage over a known-size source is valid under the <c>File</c>
        ///framer (which declares its size at Init) as well as <c>Chunked</c>. <see cref="__get_bytes"/> relays the inner stage's completion verbatim.</para>
        ///</summary>
        class Stage : AdHoc.Connection.Transmitter.BytesSrc, AdHoc.BytesSrc
        {
            readonly Core _c = new();

            AdHoc.Connection.Transmitter.BytesSrc src = null!; //inner stage — another IStream (Chunked/File) or a Terminal leaf

            ///<summary>Chain builder: swap the inner next-stage <see cref="src"/> — set it (null to detach), return the previous.</summary>

            public int __id { get; set; } //unused for an inner stage (the outer framer carries the dispatch id)

            ///<summary>(Re)configure: inner src + a fresh ChaCha20 keystream (<paramref name="key"/> 32 B, <paramref name="nonce"/> 12 B). Returns <c>this</c> for chaining.</summary>
            public Stage Init(AdHoc.Connection.Transmitter.BytesSrc src, byte[] key, byte[] nonce)
            {
                this.src = src;
                src_ = null; //INNER role — the two roles are mutually exclusive per instance
                _c.Init(key, nonce);
                _hdrPut = HDR;
                return this;
            }

            ///<summary>
            ///(Re)configure for a pack. The stage holds no key: at the pack's first bytes it takes the newest key of the
            ///Transmitter that drives it (<see cref="AdHoc.Connection.Transmitter.keys"/>) and encrypts under that key's base
            ///nonce XOR-ed with the next <see cref="Core.NextSeq"/>. 12 bytes go in clear ahead of the ciphertext - the key's
            ///id (4) and the sequence (8): each pack is decrypted alone, with the key it names. The stream is no longer
            ///length-preserving: not for the <c>File</c> framer. Pair with <see cref="Receiver.Stage.InitExplicit"/>.
            ///</summary>
            public Stage InitExplicit(AdHoc.Connection.Transmitter.BytesSrc src)
            {
                this.src = src;
                src_ = null;
                _hdrPut = -1; //the key is taken at the first bytes
                return this;
            }

            //The key of the pack: the newest of the Transmitter's session.
            void keyed(AdHoc.Connection.Transmitter dst)
            {
                var k = dst.keys.Current ?? throw new InvalidOperationException("A pack chain with ChaCha20 on a connection without keys: encrypt the connection (a host key, a pinned server key), or add a key to its Transmitter's and Receiver's keys.");
                _c.Init(k.key, k.iv);
                var seq = Core.NextSeq();
                _c.Nonce(seq);
                BinaryPrimitives.WriteUInt32LittleEndian(_hdr, k.id);
                BinaryPrimitives.WriteUInt64LittleEndian(_hdr.AsSpan(4), seq);
                _hdrPut = 0;
            }

            const int HDR = 12;
            readonly byte[] _hdr = new byte[HDR];
            int _hdrPut = HDR; //bytes of the header written so far; HDR - all, or none to write
#region TRANSPORT role
            //Length-preserving: fill the transport buffer from the upper layer, XOR it in place, relay -1/0 verbatim.

            AdHoc.BytesSrc? src_; //TRANSPORT role: the connection's own Transmitter (null ⇒ inner role)
            bool _closed;

            ///<summary>Plaintext bytes pulled from <see cref="src_"/> so far (== ciphertext bytes: length-preserving).</summary>
            public long wire_bytes;

            ///<summary>Arm as the connection's transport-level encryptor: pulls protocol bytes from
            ///<paramref name="src_"/> (normally <c>Connection.transmitter</c>) and hands the socket ciphertext.
            ///Pair with <see cref="Receiver.Stage.Init_"/>.</summary>
            public Stage Init_(AdHoc.BytesSrc src_, byte[] key, byte[] nonce)
            {
                this.src_ = src_;
                src = null!; //TRANSPORT role
                _c.Init(key, nonce);
                _hdrPut = HDR;
                _closed = false;
                return this;
            }

            public bool isOpen() => !_closed && (src_?.isOpen() ?? true);

            public void Close()
            {
                if (_closed)
                    return;
                _closed = true;
                src_?.Close();
            }

            ///<summary>Transport entry: let the upper layer fill <paramref name="dst"/>, then XOR-encrypt exactly the
            ///freshly written bytes in place. Return value is relayed verbatim (<c>-1</c> dry, <c>0</c> nothing now).</summary>
            public int Read(byte[] dst, int dst_byte, int dst_bytes)
            {
                if (_closed || src_ == null)
                    return -1;
                var n = src_.Read(dst, dst_byte, dst_bytes);
                if (n < 1)
                    return n;
                _c.Process(dst.AsSpan(dst_byte, n)); //XOR in place; the keystream is continuous across calls
                wire_bytes += n;
                return n;
            }
#endregion

            //Transparent to length: a stream cipher neither adds nor removes bytes, so it forwards the inner stage's
            //declared payload size unchanged (-1 if the inner source's size is unknown). Valid under File and Chunked.

            ///<summary>
            ///Framework entry. Lets <see cref="src"/> write plaintext into the transmit window, then XOR-encrypts exactly
            ///those freshly-written bytes in place. The keystream advances continuously across fills. Relays the inner
            ///stage's completion verbatim: <c>true</c> at source EOF (the framer then writes the <c>0x0000</c> terminator),
            ///<c>false</c> to park when the buffer fills.
            ///</summary>
            public bool __get_bytes(AdHoc.Connection.Transmitter dst)
            {
                if (_hdrPut < 0)
                    keyed(dst);
                for (; _hdrPut < HDR; _hdrPut++) //the key id and the sequence, in clear, ahead of the ciphertext
                {
                    if (dst.byte_max <= dst.byte_)
                        return false;
                    dst.buffer![dst.byte_++] = _hdr[_hdrPut];
                }
                var from = dst.byte_;
                var done = src.__get_bytes(dst); //inner produces plaintext into dst.buffer[from .. dst.byte_]
                var n = dst.byte_ - from;
                if (0 < n)
                    _c.Process(dst.buffer.AsSpan(from, n)); //XOR-encrypt the new bytes in place; keystream is continuous
                return done;
            }
        }
    }
}
