//Copyright 2025 Chikirev Sirguy, Unirail Group. All rights reserved.
//
//This file is part of the AdHoc protocol runtime library.
//
//Licensed under the PolyForm Shield License 1.0.0. The full text is distributed with this
//file as LICENSE.md and is published at https://polyformproject.org/licenses/shield/1.0.0
//
//In short: you may use, modify and distribute this software for any purpose, except to
//provide a product that competes with the software, or with any product the licensor
//provides using the software. Competition is judged by function, not by form.
//
//The plain-text notice lines the license requires you to pass on - the Required Notice and
//the Licensor Line of Business - are in the NOTICE file distributed with this library.
//Keep LICENSE.md and NOTICE with any copy of this software that you distribute.
//
//Code generated by the AdHoc generator is NOT part of the Licensed Work and carries no
//restrictions whatsoever - see the header of any generated file.
//
//Provided as is, without any warranty or condition.
//
//Commercial licenses that remove the noncompete restriction are available.
//For licensing and inquiries: al8v5C6HU4UtqE9@gmail.com

//The handshake of an encrypted connection: Noise_NK_25519_ChaChaPoly_SHA256, as the Noise Protocol Framework (revision 34,
//https://noiseprotocol.org/noise.html) defines it. The client knows the server's static public key beforehand - pinned,
//as an SSH host key or a WireGuard peer key - and the server proves it holds the secret; both sides get keys of their own
//per connection, with forward secrecy. The client is authenticated later, by the application's own login inside.
//
//  <- s              the server's static key, known to the client
//  ...
//  -> e, es          message 1, client to server: 32 bytes of ephemeral key, the payload, a 16-byte tag
//  <- e, ee          message 2, server to client: the same
//
//Then Split gives one ChaCha20-Poly1305 key per direction. Transport-agnostic: the UDP transport carries the two
//messages in its INITIAL and ACCEPT, a stream transport as its first exchange; each numbers its messages itself.
using System;
using System.Security.Cryptography;
using System.Threading;

namespace org.unirail;

public sealed class NoiseNK
{
    public const int KEY = 32, TAG = ChaCha20.Aead.TAG;

    ///<summary>The overhead of a handshake message: the ephemeral key and the tag of the payload.</summary>
    public const int OVERHEAD = KEY + TAG;

    static readonly byte[] NAME = System.Text.Encoding.ASCII.GetBytes("Noise_NK_25519_ChaChaPoly_SHA256"); //exactly HASHLEN: h is the name itself

    readonly byte[] ck = new byte[32], h = new byte[32], k = new byte[32];
    readonly byte[] eSecret = new byte[KEY], ePublic = new byte[KEY], sSecret = new byte[KEY], rs = new byte[KEY], re = new byte[KEY];

    bool hasKey;
    ulong n;
    int step; //the next message: 0 - the first, 1 - the second, 2 - done

    readonly bool initiator;
    readonly ChaCha20.Aead cipher = new(new byte[KEY]);

    NoiseNK(bool initiator, ReadOnlySpan<byte> prologue)
    {
        this.initiator = initiator;
        NAME.CopyTo(h, 0);
        NAME.CopyTo(ck, 0);
        MixHash(prologue);
    }

    ///<summary>The client's side: it knows the server's static public key.</summary>
    ///<param name="ephemeral">For tests only: the ephemeral secret to use instead of a random one.</param>
    public static NoiseNK Initiator(ReadOnlySpan<byte> serverPublic, ReadOnlySpan<byte> prologue, ReadOnlySpan<byte> ephemeral = default)
    {
        var s = new NoiseNK(true, prologue);
        serverPublic.Slice(0, KEY).CopyTo(s.rs);
        s.MixHash(s.rs); //the pre-message: <- s
        s.ephemeral(ephemeral);
        return s;
    }

    ///<summary>The server's side: its static key pair.</summary>
    public static NoiseNK Responder(ReadOnlySpan<byte> staticSecret, ReadOnlySpan<byte> prologue, ReadOnlySpan<byte> ephemeral = default)
    {
        var s = new NoiseNK(false, prologue);
        staticSecret.Slice(0, KEY).CopyTo(s.sSecret);
        Span<byte> pub = stackalloc byte[KEY];
        X25519.PublicKey(pub, s.sSecret);
        s.MixHash(pub); //the pre-message: <- s
        s.ephemeral(ephemeral);
        return s;
    }

    void ephemeral(ReadOnlySpan<byte> given)
    {
        if (given.IsEmpty)
            X25519.KeyPair(eSecret, ePublic);
        else
        {
            given.Slice(0, KEY).CopyTo(eSecret);
            X25519.PublicKey(ePublic, eSecret);
        }
    }

    ///<summary>
    ///Writes this side's handshake message - the first for the client, the second for the server - with
    ///<paramref name="payload"/>, encrypted: <see cref="OVERHEAD"/> + payload bytes.
    ///</summary>
    ///<returns>The length written; -1 - not this side's turn, or the peer's key is of low order.</returns>
    public int WriteMessage(Span<byte> dst, ReadOnlySpan<byte> payload)
    {
        if (step != (initiator ? 0 : 1))
            return -1;
        ePublic.CopyTo(dst);
        MixHash(ePublic);
        Span<byte> dh = stackalloc byte[KEY];
        var ok = initiator ? X25519.Agree(dh, eSecret, rs)  //es
                           : X25519.Agree(dh, eSecret, re); //ee
        MixKey(dh);
        CryptographicOperations.ZeroMemory(dh);
        if (!ok)
            return -1;
        var c = dst.Slice(KEY, payload.Length + TAG);
        payload.CopyTo(c);
        EncryptAndHash(c);
        step++;
        return KEY + c.Length;
    }

    ///<summary>Reads the peer's handshake message; its payload is decrypted into <paramref name="payload"/>.</summary>
    ///<returns>The payload length; -1 - out of turn, too short, a low-order key, or forged.</returns>
    public int ReadMessage(ReadOnlySpan<byte> msg, Span<byte> payload)
    {
        if (step != (initiator ? 1 : 0) || msg.Length < OVERHEAD || payload.Length < msg.Length - OVERHEAD)
            return -1;
        //A message that fails leaves the state as it was: a forged one ahead of the real one does not spoil the handshake.
        Span<byte> saved = stackalloc byte[96];
        h.CopyTo(saved);
        ck.CopyTo(saved.Slice(32));
        k.CopyTo(saved.Slice(64));
        bool savedHasKey = hasKey;
        ulong savedN = n;

        msg.Slice(0, KEY).CopyTo(re);
        MixHash(re);
        Span<byte> dh = stackalloc byte[KEY];
        var ok = initiator ? X25519.Agree(dh, eSecret, re)  //ee
                           : X25519.Agree(dh, sSecret, re); //es
        MixKey(dh);
        CryptographicOperations.ZeroMemory(dh);
        var c = msg.Slice(KEY);
        var p = payload.Slice(0, c.Length - TAG);
        if (!ok || !DecryptAndHash(c, p))
        {
            saved.Slice(0, 32).CopyTo(h);
            saved.Slice(32, 32).CopyTo(ck);
            saved.Slice(64, 32).CopyTo(k);
            cipher.Rekey(k);
            hasKey = savedHasKey;
            n = savedN;
            CryptographicOperations.ZeroMemory(saved);
            return -1;
        }
        CryptographicOperations.ZeroMemory(saved);
        step++;
        return p.Length;
    }

    public bool Done => step == 2;

    ///<summary>The handshake hash: the same on both sides, unique to this handshake - a channel binding.</summary>
    public ReadOnlySpan<byte> HandshakeHash => h;

    ///<summary>
    ///The transport keys once the handshake is done: one ChaCha20-Poly1305 key per direction, each message numbered by
    ///its sender from 0 (the nonce). Wipes the handshake secrets.
    ///</summary>
    public void Split(out ChaCha20.Aead send, out ChaCha20.Aead receive)
    {
        if (!Done)
            throw new InvalidOperationException("The handshake is not done.");
        Span<byte> k1 = stackalloc byte[32], k2 = stackalloc byte[32];
        Hkdf(ck, ReadOnlySpan<byte>.Empty, k1, k2);
        send = new ChaCha20.Aead(initiator ? k1 : k2);
        receive = new ChaCha20.Aead(initiator ? k2 : k1);
        CryptographicOperations.ZeroMemory(k1);
        CryptographicOperations.ZeroMemory(k2);
    }

    ///<summary>
    ///A further secret of this handshake, apart from the transport keys, for <paramref name="label"/>: 32 bytes into
    ///<paramref name="a"/> and 32 into <paramref name="b"/>. Call before <see cref="Wipe"/>.
    ///</summary>
    public void Export(ReadOnlySpan<byte> label, Span<byte> a, Span<byte> b)
    {
        if (!Done)
            throw new InvalidOperationException("The handshake is not done.");
        Hkdf(ck, label, a, b);
    }

    static readonly byte[] PACKS = System.Text.Encoding.ASCII.GetBytes("AdHoc packs");

    ///<summary>
    ///The key this handshake gives the pack stages of the session (<see cref="AdHoc.Connection.Keyring"/>): 32 bytes of key and 12 of
    ///base nonce from <see cref="Export"/>, the id from the handshake hash - the same on both sides, never 0. Call before <see cref="Wipe"/>.
    ///</summary>
    public AdHoc.Connection.Keyring.Key PackKey()
    {
        byte[] key = new byte[32], more = new byte[32];
        Export(PACKS, key, more);
        var iv = more.AsSpan(0, 12).ToArray();
        CryptographicOperations.ZeroMemory(more);
        var id = System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian(h);
        return new AdHoc.Connection.Keyring.Key(id == 0 ? 1 : id, key, iv);
    }

    public void Wipe()
    {
        foreach (var x in new[] { ck, k, eSecret, sSecret })
            CryptographicOperations.ZeroMemory(x);
        cipher.Wipe();
    }
#region the symmetric state
    void MixHash(ReadOnlySpan<byte> data)
    {
        using var sha = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
        sha.AppendData(h);
        sha.AppendData(data);
        sha.GetHashAndReset(h);
    }

    void MixKey(ReadOnlySpan<byte> ikm)
    {
        Hkdf(ck, ikm, ck, k);
        cipher.Rekey(k);
        hasKey = true;
        n = 0;
    }

    //In place: the plaintext, then room for the tag.
    void EncryptAndHash(Span<byte> c)
    {
        var p = c.Slice(0, c.Length - TAG);
        if (hasKey)
            cipher.Seal(n++, h, p, c.Slice(p.Length, TAG));
        MixHash(c);
    }

    bool DecryptAndHash(ReadOnlySpan<byte> c, Span<byte> p)
    {
        c.Slice(0, p.Length).CopyTo(p);
        if (hasKey && !cipher.Open(n++, h, p, c.Slice(p.Length, TAG)))
            return false;
        MixHash(c);
        return true;
    }

    ///<summary>Noise's HKDF with HMAC-SHA256: two outputs of 32 bytes from the chaining key and the input key material.</summary>
    static void Hkdf(ReadOnlySpan<byte> chaining, ReadOnlySpan<byte> ikm, Span<byte> out1, Span<byte> out2)
    {
        Span<byte> temp = stackalloc byte[32], buf = stackalloc byte[33], o1 = stackalloc byte[32];
        HMACSHA256.HashData(chaining, ikm, temp);
        buf[0] = 1;
        HMACSHA256.HashData(temp, buf.Slice(0, 1), o1);
        o1.CopyTo(buf);
        buf[32] = 2;
        HMACSHA256.HashData(temp, buf, out2); //out2 before out1: out1 may be the chaining key itself
        o1.CopyTo(out1);
        CryptographicOperations.ZeroMemory(temp);
        CryptographicOperations.ZeroMemory(buf);
        CryptographicOperations.ZeroMemory(o1);
    }
#endregion
}

///<summary>
///An encrypted byte stream between a connection's Internal and its transport - TCP, a WebSocket (inside its frames), any
///ordered, reliable byte stream. The transport reads the outgoing bytes from it and writes the incoming ones to it, in
///place of the Internal's <c>BytesSrc</c> and <c>BytesDst</c>; it talks to the Internal through the two getters it is given,
///so an Internal that changes under the connection is followed.
///<para>
///First the <see cref="NoiseNK"/> handshake, each message as <c>[length 1][message]</c>: the client writes message 1 at once,
///the server answers with message 2. Then records, as TLS and Noise frame a stream: <c>[length 2, little-endian]
///[ciphertext][tag 16]</c>, at most 16 KB of plaintext each, ChaCha20-Poly1305 with the length as the associated data and
///the record count of the direction as the nonce - nothing of it on the wire, the stream keeps the order. A record that does
///not open - forged, damaged, replayed, dropped, reordered - ends the stream: a byte stream has no record to skip.
///</para>
///<para>
///The records are sealed in place in the transport's own send buffer; a received record is opened in a buffer of its own
///and handed on from there, so a destination that refuses bytes gets them again later and the transport's receive buffer
///is never written.
///</para>
///</summary>
public sealed class NoiseStream : AdHoc.BytesSrc, AdHoc.BytesDst
{
    public const int RECORD = 16 * 1024, HEADER = 2, TAG = NoiseNK.TAG;

    ///<summary>What the handshake of a stream is bound to: the protocol and its version.</summary>
    static readonly byte[] PROLOGUE = System.Text.Encoding.ASCII.GetBytes("AdHoc stream 1");

    readonly Func<AdHoc.BytesSrc?> src;
    readonly Func<AdHoc.BytesDst?> dst;
    readonly Action wake;
    readonly Action<AdHoc.Connection.Keyring.Key>? keys;

    ///<summary>The key this connection's handshake gives the pack stages of its session (<see cref="AdHoc.Connection.Keyring"/>); null before the handshake is done.</summary>
    public AdHoc.Connection.Keyring.Key? PackKey { get; private set; }

    NoiseNK? hs;
    ChaCha20.Aead? tx, rx;
    ulong txN, rxN;

    //The handshake message going out: [length][message].
    readonly byte[] hsOut = new byte[1 + NoiseNK.OVERHEAD];
    int hsOutLen, hsOutPos;

    //The record, or handshake message, coming in: what of it arrived, how long it is, and its opened plaintext still to hand on.
    readonly byte[] rec = new byte[HEADER + RECORD + TAG];
    int got, need = 1, plainPos, plainEnd;

    volatile bool failed;

    ///<summary>Records that did not open: the stream ended at the first.</summary>
    public long forged;

    NoiseStream(Func<AdHoc.BytesSrc?> src, Func<AdHoc.BytesDst?> dst, Action wake, Action<AdHoc.Connection.Keyring.Key>? keys)
    {
        this.src = src;
        this.dst = dst;
        this.wake = wake;
        this.keys = keys;
    }

    ///<summary>The client's end: it pinned the server's static public key, and sends the first message at once.</summary>
    ///<param name="wake">Asks the transport to read from this again: the handshake got on, and there is something to send.</param>
    ///<param name="keys">Takes the pack key of the handshake, for the session the connection carries - before anything is sent under the new keys.</param>
    public static NoiseStream Client(ReadOnlySpan<byte> serverPublic, Func<AdHoc.BytesSrc?> src, Func<AdHoc.BytesDst?> dst, Action wake, Action<AdHoc.Connection.Keyring.Key>? keys = null)
    {
        var s = new NoiseStream(src, dst, wake, keys) { hs = NoiseNK.Initiator(serverPublic, PROLOGUE) };
        s.hsOutLen = 1 + s.hs.WriteMessage(s.hsOut.AsSpan(1), ReadOnlySpan<byte>.Empty);
        s.hsOut[0] = (byte)(s.hsOutLen - 1);
        return s;
    }

    ///<summary>The server's end, with its static secret key: it waits for the client's first message.</summary>
    public static NoiseStream Server(ReadOnlySpan<byte> staticSecret, Func<AdHoc.BytesSrc?> src, Func<AdHoc.BytesDst?> dst, Action wake, Action<AdHoc.Connection.Keyring.Key>? keys = null) =>
        new(src, dst, wake, keys) { hs = NoiseNK.Responder(staticSecret, PROLOGUE) };

    ///<summary>Both directions have their keys.</summary>
    public bool Ready => Volatile.Read(ref tx) != null;
#region out
    ///<summary>The bytes to send: the handshake message, then records of what the Internal's source gives.</summary>
    public int Read(byte[] dst_, int at, int room)
    {
        if (failed)
            return -1;
        var tx = Volatile.Read(ref this.tx); //first: the handshake answer is written before the keys are published
        if (hsOutPos < hsOutLen)
        {
            var n = Math.Min(room, hsOutLen - hsOutPos);
            Array.Copy(hsOut, hsOutPos, dst_, at, n);
            hsOutPos += n;
            return n;
        }
        if (tx == null)
            return 0; //the keys come with the server's answer
        var inner = src();
        if (inner == null)
            return 0;
        var pos = at;
        var end = at + room;
        while (HEADER + 1 + TAG <= end - pos)
        {
            var n = inner.Read(dst_, pos + HEADER, Math.Min(RECORD, end - pos - HEADER - TAG));
            if (n < 1)
            {
                if (pos == at)
                    return n; //nothing now, or the source is dry
                break;
            }
            dst_[pos] = (byte)n;
            dst_[pos + 1] = (byte)(n >> 8);
            tx.Seal(txN++, dst_.AsSpan(pos, HEADER), dst_.AsSpan(pos + HEADER, n), dst_.AsSpan(pos + HEADER + n, TAG));
            pos += HEADER + n + TAG;
        }
        return pos - at;
    }

    public bool isOpen() => !failed && (src()?.isOpen() ?? false);

    void AdHoc.BytesSrc.Close() => src()?.Close();
#endregion
#region in
    ///<summary>The bytes received: the handshake message, then records, opened and handed on to the Internal's destination.</summary>
    ///<returns>How many were taken; 0 - the destination refuses now, offer them again later; -1 - the stream is broken.</returns>
    public int Write(byte[] src_, int at, int length)
    {
        if (failed)
            return -1;
        var taken = 0;
        for (;;)
        {
            if (plainPos < plainEnd)
            { //an opened record the destination has not taken all of
                var d = dst();
                if (d == null)
                    return taken;
                var n = d.Write(rec, plainPos, plainEnd - plainPos);
                if (n < 0)
                    return n;
                if (n == 0)
                    return taken;
                plainPos += n;
                continue;
            }
            if (taken == length)
                return taken;

            var k = Math.Min(need - got, length - taken);
            Array.Copy(src_, at + taken, rec, got, k);
            got += k;
            taken += k;
            if (got < need)
                continue;

            if (rx == null)
            { //the handshake: [length][message]
                if (need == 1)
                {
                    need = 1 + rec[0];
                    if (rec[0] < NoiseNK.OVERHEAD || rec.Length < need)
                        return fail();
                    continue;
                }
                if (!handshake())
                    return fail();
                got = 0;
                need = HEADER;
                continue;
            }
            if (need == HEADER)
            {
                var len = rec[0] | rec[1] << 8;
                if (len == 0 || RECORD < len)
                    return fail();
                need = HEADER + len + TAG;
                continue;
            }
            var plain = need - HEADER - TAG;
            if (!rx.Open(rxN++, rec.AsSpan(0, HEADER), rec.AsSpan(HEADER, plain), rec.AsSpan(HEADER + plain, TAG)))
                return fail();
            plainPos = HEADER;
            plainEnd = HEADER + plain;
            got = 0;
            need = HEADER;
        }
    }

    //A handshake message in rec[1..need): the server reads the first and answers, the client reads the answer.
    bool handshake()
    {
        var h = hs!;
        if (h.ReadMessage(rec.AsSpan(1, need - 1), Span<byte>.Empty) < 0)
            return false;
        if (!h.Done)
        {
            hsOutLen = 1 + h.WriteMessage(hsOut.AsSpan(1), ReadOnlySpan<byte>.Empty);
            hsOut[0] = (byte)(hsOutLen - 1);
            hsOutPos = 0;
        }
        PackKey = h.PackKey();
        keys?.Invoke(PackKey); //before the keys are published: no pack goes out ahead of its key
        h.Split(out var send, out var receive);
        h.Wipe();
        hs = null;
        rx = receive;
        Volatile.Write(ref tx, send); //last: a transmit on another thread that sees the keys sees the answer too
        wake();                       //the server's answer, or what the client queued meanwhile
        return true;
    }

    int fail()
    {
        forged++;
        failed = true;
        return -1;
    }

    void AdHoc.BytesDst.Close() => dst()?.Close();
#endregion
}
