#This file contains common information about the AdHoc agent.

# =============================== Attempting to establish connections to the server in sequential order. ==============================

server = ["wss://unirail.org:8691", "223.255.167.58:8691"]


#===============================Path to the 7-Zip console executable.  https://7-zip.org/download.html set latest version!
#for Windows https://7-zip.org/a/7zr.exe
#for MacOS https://7-zip.org/a/7z2300-mac.tar.xz
# for Linux https://7-zip.org/a/7z2300-linux-x86.tar.xz
7zip_exe = "C:/Program Files/7-Zip/7z.exe"

# =============================== EXTERNAL C# EDITOR ==============================

#JetBrains Rider
#https://www.jetbrains.com/help/rider/Opening_Files_from_Command_Line.html
#rider64.exe [--line <number>] [--column <number>] <path ...>
#show_code_exe="/Rider/bin/rider64.exe"
#show_code_args="--line <line number> <path to file>"

#VS Code
# https://code.visualstudio.com/docs/editor/command-line#_launching-from-command-line
#-g or --goto	When used with file:line{:character}, opens a file at a specific line and optional character position.
#This argument is provided since some operating systems permit : in a file name.
show_code_exe = "/VSCode/Code.exe"
show_code_args = "--goto <path to file>:<line number>:<char number>"

#AdhocAgent github Client ID https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#:~:text=client_id,ID%20you%20received%20from%20GitHub%20when%20you
adhoc_id = "4534a2890970abb37047"