# on push to the main branch  To create a GitHub Actions workflow that builds a .NET 8.0 console application 
# in Release mode for all major operating systems (Windows, macOS, and Linux), and uploads the build artifacts to the 
# repository for users to download
name: AdHocAgent Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build --configuration Release
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Publish Release Artifact
      run: dotnet publish --configuration Release --output ./publish
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
