name: Process Sign-up Discussion Messages

on:
  discussion:
    types: [created]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}
  REPO: AdHoc-Protocol
  ORG: AdHoc-Protocol
  CATEGORY_NAME: "Sign up"

jobs:
  process-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Get Discussion Category ID for "Sign up"
        id: get_category_id
        run: |
          CATEGORY_ID=$(gh api graphql -f query='
            query($owner: String!, $name: String!, $categoryName: String!) {
              repository(owner: $owner, name: $name) {
                discussionCategory(name: $categoryName) {
                  id
                }
              }
            }
          ' -F owner="$ORG" -F name="$REPO" -F categoryName="$CATEGORY_NAME" | jq -r '.data.repository.discussionCategory.id')

          if [[ -z "$CATEGORY_ID" ]]; then
            echo "Error: Category ID not found for '$CATEGORY_NAME'" >&2
            exit 1
          fi
          echo "Fetched Category ID: $CATEGORY_ID"

      - name: Collect discussion messages in "Sign up" category
        id: collect_messages
        run: |
          MESSAGES=$(gh api graphql -f query='
            query($owner: String!, $name: String!, $categoryId: ID!) {
              repository(owner: $owner, name: $name) {
                discussions(first: 100, categoryId: $categoryId) {
                  nodes {
                    author {
                      login
                      url
                      avatarUrl
                    }
                    createdAt
                    id
                  }
                }
              }
            }
          ' -F owner="$ORG" -F name="$REPO" -F categoryId="$CATEGORY_ID")

          echo "$MESSAGES" > messages.json
          echo "Collected messages in 'Sign up' category."

      - name: Collect Unique Messages
        run: |
          # Parse the messages.json file and remove duplicates
          jq -r '.data.repository.discussions.nodes 
          | unique_by(.author.login) 
          | .[] 
          | "\(.author.login), \(.author.url), \(.author.avatarUrl), \(.id)"' messages.json > unique_messages.txt
          
          echo "Collected and processed unique messages in '$CATEGORY_NAME' category."

      - name: Get Organization ID
        id: get_org_id
        run: |
          ORG_ID=$(gh api graphql -f query='
            query($organization: String!) {
              organization(login: $organization) {
                id
              }
            }
          ' -F organization="$ORG" | jq -r '.data.organization.id')

      - name: Process Unique Messages
        run: |
          while IFS=',' read -r login url avatarUrl id; do
            # Check if a project with title "$login" exists in the organization
            PROJECT_EXISTS=$(gh api graphql -f query='
              query($organization: String!, $login: String!) {
                organization(login: $organization) {
                  projectsV2(first: 1, query: $login) {
                    totalCount
                  }
                }
              }
            ' -F organization="$ORG" -F login="$login" | jq -r '.data.organization.projectsV2.totalCount')

            if [[ "$PROJECT_EXISTS" == "0" ]]; then
              echo "Creating new project for $login..."
              NEW_PROJECT_ID=$(gh api graphql -f query='
                mutation($ownerId: ID!, $title: String!) {
                  createProjectV2(input: {ownerId: $ownerId, title: $title}) {
                    projectV2 {
                      id
                    }
                  }
                }
              ' -F ownerId="$ORG_ID" -F title="$login" | jq -r '.data.createProjectV2.projectV2.id')

              echo "Created project with ID: $NEW_PROJECT_ID"

              README_CONTENT="# [$login]($url)  \n\n![image]($avatarUrl)"
              
              gh api graphql -f query='
                mutation($projectId: ID!, $readme: String!) {
                  updateProjectV2(input: {projectId: $projectId, readme: $readme, public: false}) {
                    projectV2 {
                      id
                    }
                  }
                }
              ' -F projectId="$NEW_PROJECT_ID" -F readme="$README_CONTENT"

              echo "Updated README for project: $login"

              # Add a note to the new project with text "$id" (discussion ID)
              gh api graphql -f query='
                mutation($projectId: ID!, $title: String!) {
                  addProjectV2DraftIssue(input: {projectId: $projectId, title: $title}) {
                    projectV2DraftIssue {
                      id
                    }
                  }
                }' -F projectId="$NEW_PROJECT_ID" -F title="$id"

              echo "Added note with discussion ID: $id to project: $login"
          
              # First, get the user ID from the login
              USER_ID=$(gh api graphql -f query='
                query($login: String!) {
                  user(login: $login) {
                    id
                  }
                }
              ' -F login="$login" --jq '.data.user.id')
              
              # Now, add the collaborator to the project with read-write access
              gh api graphql -f query='
                mutation($projectId: ID!, $userIds: [ID!]!) {
                  updateProjectV2Collaborators(input: {projectId: $projectId, collaborators: $userIds , role: WRITE}) {
                    projectV2 {
                      id
                    }
                  }
                }
              ' -F projectId="$NEW_PROJECT_ID" -F userIds="[\"$USER_ID\"]"

              echo "Invited $login to project $login with read-write access"
            else
              echo "Project for $login already exists, skipping..."
            fi
          done < unique_messages.txt

      - name: Delete Processed Messages
        if: success()
        run: |
          cut -d',' -f4 unique_messages.txt | while read id; do
            gh api graphql -f query='
              mutation($id: ID!) {
                deleteDiscussion(input: {id: $id}) {
                  clientMutationId
                }
              }
            ' -F id="$id"
          done
