name: Process Enter Discussion Messages

on:
  discussion:
    types: [created]
  workflow_dispatch:

jobs:
  process-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Get discussion messages in "Enter" category
        id: fetch_discussions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DISCUSSION_CATEGORY_ID="42610297"  # Use the actual category ID
          MESSAGES=$(gh api graphql -f query='
            query($owner: String!, $name: String!, $categoryId: ID!) {
              repository(owner: $owner, name: $name) {
                discussions(first: 100, categoryId: $categoryId) {
                  nodes {
                    author {
                      login
                      url
                      avatarUrl
                    }
                    createdAt
                  }
                }
              }
            }
          ' -F owner="$GITHUB_REPOSITORY_OWNER" -F name="$GITHUB_REPOSITORY_NAME" -F categoryId="$DISCUSSION_CATEGORY_ID")
          echo "$MESSAGES" > messages.json
          cat messages.json  # This prints the file content into the console
